### ISSUE TITLE
Center DataGridRow Icons Within Columns

### ISSUE THREAD

**Issue by EukalyptenHD** [duke7553/files-uwp#101]
Instead of keeping the column name blank, maybe implement some sort of dropdown menu when you click on it for actions like "sort by x _(type, size, etc)_".

<details>
<summary>Also, the icons should be centered within the column when the width is reduced.</summary>
<br>

![icons_not_aligned](https://user-images.githubusercontent.com/44278658/57767691-e1e40300-7701-11e9-99bd-bd09b20bca53.png)
</details>

**Comment by duke7553** [comment]
DataGrid sorting is on my road map, so I'll rename this issue accordingly.

**Comment by duke7553** [comment]
Changes for the centered icons are now in newui. Snapshot including these will come soon.

**Comment by duke7553** [comment]
Snapshot has been released. Closing this issue.
