### ISSUE TITLE
Requesting Access To File System

### ISSUE THREAD

**Issue by EukalyptenHD** [duke7553/files-uwp#105]
In terms of user experience, I think it would be better to request permission during installation or at-least the first time you open the application instead of when you open your first directory and be granted with a pop-up.

**Comment by yaichenbaum** [comment]
Since this will be downloaded from the store and installed in the background there is no way to include such an option for permission.
Some directories work before giving permission so it is better (in my opinion) to give the user a bit of a feel for the app before displaying pop-ups.

**Comment by duke7553** [comment]
For this one, I put myself in agreement with @EukalyptenHD . It would be impossible for a user to grant this during the install.
