### ISSUE TITLE
Everything Disappears Apart From The Tab Section

### ISSUE THREAD

**Issue by EukalyptenHD** [duke7553/files-uwp#106]
Whenever I hold `CTRL` and click on a tab whilst already on it, it's visibility toggles back and forth.

Goes back to normal when I open a new tab or go to a different one.

![1be4c0bc118cf0e1ede7f9cb116fd091](https://user-images.githubusercontent.com/44278658/58172189-c479e080-7c8f-11e9-9339-8afe28ac07bc.png)

**Comment by duke7553** [comment]
@EukalyptenHD This is actually a bug with the toolkit TabView, so I filed an issue report with them, so we can wait on the fix. I'll incorporate it as soon as they release the fixed version.

**Comment by duke7553** [comment]
Of course, I could have played this one off as a [hide "homework" folder from mom] feature. ;) In all seriousness, I am currently attempting to fix this. Since this bug seems to only be noticeable to a small number of users, I'll demote it to low-priority for now.

**Comment by duke7553** [comment]
This bug is fixed in master now with commit b304f53e73e9ecce067cd6bfa81c2b98c5464b92
