### ISSUE TITLE
When only one tab is open closing it from the tab does not work right

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#107]
If only one tab is open, closing it from the 'x' on the tab just loads the favorites page.

**Comment by duke7553** [comment]
Yes, this is by design. The one tab left actually does close, but it opens a new one immediately after.

**Comment by yaichenbaum** [comment]
I kind of expected it to work the same way tabs do in Edge for example...

**Comment by duke7553** [comment]
@yaichenbaum Good point. I guess since that's what people are used to, I can make that change.

**Comment by yaichenbaum** [comment]
@duke7553 I believe you addressed this issue, correct?

**Comment by duke7553** [comment]
Yes, with commit https://github.com/duke7553/files-uwp/commit/88805878d5cdd5878c69713c547796a176ca14b5
