### ISSUE TITLE
Items get cut off and overlap when app is sized small

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#109]
A few things can help solve this.

- Search box should get smaller when the app is resized.
- Labels on app bar buttons hide when app is sized smaller. (You would want to add tool-tips to the commands since only the icon would be showing)
- Items go in to overflow menus.

![image](https://user-images.githubusercontent.com/39923744/58187024-fc7b2680-7c83-11e9-93ed-4e9b6d03876c.png)

**Comment by Poopooracoocoo** [comment]
I think it's a good idea to get rid of the search box completely and only show an icon when it's that small.

I also think that the padding between the back, forward and refresh icons should be reduced (not just when small).

**Comment by yaichenbaum** [comment]
Padding between the back, forward and refresh will be reduced when #148 is done.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/70591444-2fdfbd00-1ba4-11ea-81a1-f70e76b91fda.png)
@Poopooracoocoo Padding has been reduced between those button and the ribbon in general is more responsive when resizing it. There is still some work to do for the search icon but at least some of the changes will be included he next release (v0.7).

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).

**Comment by yaichenbaum** [comment]
> I think it's a good idea to get rid of the search box completely and only show an icon when it's that small.
> 
> I also think that the padding between the back, forward and refresh icons should be reduced (not just when small).

Thank you for your feedback, the search box is now hidden behind a button and the padding and overall design has been improved. These changes will be included in the next update.
