### ISSUE TITLE
Right Clicking Does Not Clear Highlight

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#11]
Right clicking on multiple files/folders one after the other does not clear the previous selection.

**Comment by duke7553** [comment]
This bug is now fixed with this [commit](https://github.com/duke7553/files-uwp/commit/34eb9effd1c26b50a640209155d95908fbe91d18) and will likely be included in the next preview. Please reopen if you can reproduce this bug again once the preview is released.
