### ISSUE TITLE
Button not aligned with search box

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#110]
The button next the the search box is a few pixels shorter then the search box is.
![image](https://user-images.githubusercontent.com/39923744/58187799-7e1f8400-7c85-11e9-9702-3be834901bc7.png)

**Comment by duke7553** [comment]
I fixed this annoyance today. The change will come very soon in the next snapshot.

**Comment by yaichenbaum** [comment]
Thanks.

**Comment by duke7553** [comment]
![Annotation 2019-05-28 160224](https://user-images.githubusercontent.com/20365014/58508454-132cec00-8162-11e9-8e80-6798e3e449f6.png)
![Annotation 2019-05-28 160225](https://user-images.githubusercontent.com/20365014/58508455-132cec00-8162-11e9-9202-dff43fcee18e.png)

**Comment by yaichenbaum** [comment]
Perfect!
