### ISSUE TITLE
There should be priority labels added to issues in the repository

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#111]
I am adding lots of issues to this repository yet many of them are small UI stuff or low priority. Adding a priority label to different issues may help sort through them.

**Comment by yaichenbaum** [comment]
Is there a way for me to add labels to issues I open or only @duke7553  have access to do that?

**Comment by duke7553** [comment]
I'm pretty sure that I only have access to that. Sorry. If you think an issue is critical or something, please let me know in the issue report and I'll evaluate that claim.

**Comment by duke7553** [comment]
Closing this now, as I will add the priority labels to the issues.

**Comment by duke7553** [comment]
@yaichenbaum There is now a way to flag a bug as high/critical priority.
