### ISSUE TITLE
Files UWP doesn't recognize .ink files

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#112]
.ink files (aka shortcuts) are not shown inside Files UWP

**Comment by duke7553** [comment]
Unless someone can prove me wrong, I'm pretty sure it's impossible to display these files with Windows.Storage APIs. Marking this as wontfix unless someone can provide this info.

**Comment by yaira2** [comment]
This feature is now available. You can download the latest version of Files from our website https://files.community/download
