### ISSUE TITLE
Cannot Open .exe

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#12]
Looking at your post in Reddit, I see you're already aware of this.

Files cannot open .exe files, but everything else seems to work fine.

**Comment by ashikns** [comment]
I've added a implementation for this. You can see it at https://github.com/ashikns/files-uwp/tree/exe-launcher. I haven't opened a PR though since it involves adding a new project and all. Check it out when you get a chance and if it looks good to you I'll open a PR.

**Comment by duke7553** [comment]
This looks really promising, and I will checkout this code to test and get back to you regarding the PR. From what I've seen, it looks like a method I didn't think of.

**Comment by duke7553** [comment]
Done! https://github.com/duke7553/files-uwp/pull/34 Please review this new PR

**Comment by duke7553** [comment]
This will be resolved for v0.4.8, and the changes are already in master. Closing this issue.
