### ISSUE TITLE
Hovering over tabs should not change the background color to be as dark as the active tab

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#120]
When you hover over a tab in dark theme for example it should not make it be black, black should be only for the active tab, maybe a light black or gray would be better.

**Comment by SOI7** [comment]
Alternatively, if assigning a different tint to the hovered tab is too tricky, you could simply add a horizontal colored line with the system accent color on the top of the active tab

![Annotazione 2019-07-28 171746](https://user-images.githubusercontent.com/50930970/62009119-ccf10a80-b15b-11e9-9f7d-558a69da4abc.jpeg)

**Comment by yaichenbaum** [comment]
@SOI7 It should not be too difficult to assign a different tint but I really like your idea.

**Comment by yaichenbaum** [comment]
Looking in to it further it gets a little more complicated since the hover even goes for the actual selected tab as well so your idea is probably how were going to need to go for this one.

**Comment by duke7553** [comment]
I haven't been able to reproduce this anymore with the new tab strip
![image](https://user-images.githubusercontent.com/20365014/69882520-5e08f700-129e-11ea-8268-84982fffa2ac.png)

**Comment by yaichenbaum** [comment]
I think it still exists in the latest version in master, however it seems to be solved with the acrylic title bar change.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
