### ISSUE TITLE
Crash on Windows 10 (1903)

### ISSUE THREAD

**Issue by gurpreetshanky** [duke7553/files-uwp#122]
![Annotation 2019-05-29 022032](https://user-images.githubusercontent.com/26076066/58534129-6762bb00-81b8-11e9-8a6d-eac8a66b2486.jpg)

**Comment by duke7553** [comment]
Hey, thanks for reporting this. I narrowed down the issue and fixed it in a recent commit (commit b225575ccbbab49021c6d3599ca2591ba9a21d04). The change will appear in the upcoming snapshot.

**Comment by gurpreetshanky** [comment]
Thanks 😊

**Comment by Magangel** [comment]
For me, the app crash when I try to select a pdf for open the context menu and select de option “open with”.
By the way, it would be great if you add a “View tab” in the ribbon for select between different display mode.(for example, big icons, tiny icons, list, content) And the option(inside the tab of course) of select by defaut the display mode.
Greetings and thanks for the grear work.
