### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by formula409** [duke7553/files-uwp#123]
I am getting this issue. I have developer mode enabled in a fresh install of Windows 10 build 1903 64bit.

Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

I tried installing the certificate by hand but i still cannot install.

This is happening with both Files UWP v0.5.0-newui_snapshot 1 and 2

**Comment by yaichenbaum** [comment]
Which file did you run?

**Comment by duke7553** [comment]
@yaichenbaum @formula409  BTW, I uploaded Files UWP to the store today as a free download. (of course) It is currently being approved, but I will let you know when it can be downloaded. That should resolve all installation issues.

**Comment by yaichenbaum** [comment]
I was waiting for this! It might take some time to be approved because of the restricted capabilities included.

**Comment by duke7553** [comment]
Yes, that is why I went ahead and started the review process early.

**Comment by yaichenbaum** [comment]
Good luck!

**Comment by formula409** [comment]
> @yaichenbaum @formula409 BTW, I uploaded Files UWP to the store today as a free download. (of course) It is currently being approved, but I will let you know when it can be downloaded. That should resolve all installation issues.

Thanks

**Comment by dariomadeira** [comment]
Not Install in Windows May 2019 Update, certificate error!

**Comment by duke7553** [comment]
Since I really can't fix this behavior, I'll close this. The eventual Store release will fix this problem.
