### ISSUE TITLE
Crashing when switching tabs

### ISSUE THREAD

**Issue by Nyanekoy** [duke7553/files-uwp#126]
![image](https://user-images.githubusercontent.com/40134023/58687238-62049c80-8381-11e9-91bf-2e7e67e9c4ed.png)

**Comment by duke7553** [comment]
I was able to reproduce and fix this behavior with commit https://github.com/duke7553/files-uwp/pull/96/commits/359ace3b80d0cfa45a7db03f570744d5bcb8845e

It will be available in an upcoming release. In the meantime, don't try to create a new tab until the current directory is finished loading.
