### ISSUE TITLE
ExecutableLauncher depends on .NET Core 3

### ISSUE THREAD

**Issue by woachk** [duke7553/files-uwp#127]
Hi,

ExecutableLauncher seems to depend on .NET Core 3.0-preview, which isn't released yet. Can the executable launcher be made in C++ to avoid needing a .NET Core OS-wide install?

Thanks,

**Comment by duke7553** [comment]
@woachk The project requires .NET Core 3.0-preview because this allows for ExecutableLauncher support on ARM and ARM64. After 3.0 is finalized and released, Files UWP will only adopt the subsequent LTS .NET Core releases.

**Comment by woachk** [comment]
@duke7553 The right solution here is to have it in C++, as having a whole .NET desktop-like runtime in addition to the UWP one for just an launcher is a bad idea.
