### ISSUE TITLE
Multiple window support

### ISSUE THREAD

**Issue by MahdiGhiasi** [duke7553/files-uwp#13]
It would be nice to be able to have multiple windows open, by right clicking an item and clicking Open in New Window.

**Comment by z0oinks** [comment]
You can open another window by right clicking the icon in the Taskbar and clicking "Files".

I agree that a more intuitive way of opening a new window would be nice. Control+N for example.

Tabs too.

**Comment by MahdiGhiasi** [comment]
@z0oinks Thanks. I also think that a "Open in New Window" option in the right click context menu of folders is nice to have. I use that option quite often in Windows Explorer.

And yeah, tabs too.

**Comment by Tatitooo** [comment]
I would love to help a little bit with this proyect, i'm spanish and i'm learning CSharp

**Comment by yzhang-gh** [comment]
Tabs too.

![tabview](https://docs.microsoft.com/en-us/windows/communitytoolkit/resources/images/controls/tabview/overview.gif)

https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview

**Comment by duke7553** [comment]
I do think tabs should be added to my roadmap as sets seemingly won’t be here anytime soon.

**Comment by duke7553** [comment]
Instance tabs seem hard to implement, but I'm sure I'll find a way. Here's a screenshot so far:
![Annotation 2019-04-28 155954 (2)_LI](https://user-images.githubusercontent.com/20365014/56869520-ca054300-69cf-11e9-8a39-57defd1921e2.jpg)

**Comment by duke7553** [comment]
Since tabs are nearing completion in `newui`, I'll close this. At last, another pre-release will come soon.

**Comment by BaRRaKudaRain** [comment]
I have one question. Will be the ARM64 builds?

--
----------------------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by duke7553** [comment]
@BaRRaKudaRain  I am 90% certain there will be ARM and ARM64 builds.
