### ISSUE TITLE
Deleted files still visible

### ISSUE THREAD

**Issue by watermarkhu** [duke7553/files-uwp#132]
Some files and folders that I had deleted 2 weeks ago are somehow still visible. Explorer on the same folder shown on the left. 
![image](https://user-images.githubusercontent.com/18556882/59023635-7b5d8b00-8850-11e9-89bc-49e859ceaa93.png)
Clicking on these deleted files or folders results in _File Not Found_. Deleting them again results in 0x80070002.

**Comment by duke7553** [comment]
This sounds like an OS-level problem. Possibly search indexer corruption

**Comment by duke7553** [comment]
@watermarkhu You may want to try rebuilding the Windows search index to see if this issue persists.

**Comment by SaturnSoftware** [comment]
i'm also having this issue

**Comment by yaichenbaum** [comment]
@SaturnSoftware Thank you for reporting, did rebuilding the Windows search index help?

**Comment by SaturnSoftware** [comment]
it did, is there any way the files app could do this automatically?

**Comment by yaichenbaum** [comment]
At the moment no, we are working on many improvements to the app so it is likely we will take care of this annoyance in the future.

**Comment by SaturnSoftware** [comment]
fair enough
