### ISSUE TITLE
Can't Open Downloads Folder From Favorites By Default

### ISSUE THREAD

**Issue by UltimateSky** [duke7553/files-uwp#134]
Hello, I cannot open my downloads folder from the Favorites menu. When I click, it shows the below error:

![image](https://user-images.githubusercontent.com/13856563/59054009-5ec55100-8858-11e9-89c0-37ea13340155.png)

I started to think that this was related to the fact that my Downloads folder has been moved from the default Windows location to a second HDD but it seems like this is the only folder affected as Pictures, Videos, Documents, etc all work as expected. I can also manually navigate through the folder path to where the Downloads folder is stored and open it that way.

Edit: after looking in the settings it looks like the app was looking for my Downloads folder in the default windows directory but it was picking up the other folders correctly.

As you can see, I have my settings correct in Windows:

![image](https://user-images.githubusercontent.com/13856563/59054417-41dd4d80-8859-11e9-8081-69578222a0fd.png)

Looks like a detection error maybe? This is repeatable for me by disabling Custom Locations in the settings.

**Comment by duke7553** [comment]
Yes, the Windows setting for Downloads folder target location only applies to explorer. You'll need to enable custom locations and enter your desired location that way.

**Comment by UltimateSky** [comment]
Why is it that only the Downloads folder is affected? I have all of my media folders in a non-default location and those are fine without custom locations. Is it just a Windows limitation?

**Comment by duke7553** [comment]
While the “tools” that Microsoft provides the app to find your libraries work a certain way, the Downloads folder is one of the exceptions because of how the app has to find it. Sorry for the inconvenience.

**Comment by duke7553** [comment]
Luckily, the app now has Custom Locations. Previously accessing other locations in place of the default Downloads path was impossible.
