### ISSUE TITLE
Can't Install latest v0.5

### ISSUE THREAD

**Issue by gh0sti** [duke7553/files-uwp#135]
Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by rupertkhan** [comment]
Same issue here. Developer mode on, installed certificate prior to installation. Getting the same error.

**Comment by gh0sti** [comment]
Figured it out you gotta run the powershell script then install the package.

**Comment by rupertkhan** [comment]
I right clicked the file Add-AppDevPackage, run with powershell, then installed the certificate and ran the msix file, but still the same error. Do I have to install the certificate in a particular directory?

> 
> 
> Figured it out you gotta run the powershell script then install the package.

**Comment by yaira2** [comment]
@rupertkhan a signed installer is available on our website https://files.community/download
