### ISSUE TITLE
New App Icon Concept

### ISSUE THREAD

**Issue by duke7553** [duke7553/files-uwp#136]
![Annotation 2019-06-07 144600](https://user-images.githubusercontent.com/20365014/59127236-13cd3b80-8935-11e9-8083-1bf1de30693c.png)
The metaphor I'm trying to convey is a file with it's top-left corner folded down. Of course, taking inspiration from the modern Office icons. Please let me know what you think and what direction you want to see the icon design move towards.

**Comment by duke7553** [comment]
This is after I tweaked it for clarity.
![Annotation 2019-06-07 235040](https://user-images.githubusercontent.com/20365014/59141889-e0190280-8982-11e9-923c-c5b676b0fab4.png)

**Comment by kumarharsh** [comment]
Hey, the project's a nice effort (came here from HN)

Don't follow the office icons, IMO. Use some version of a folder (or look at the icons for Thunar, Nautilus, etc for inspiration)

**Comment by kumarharsh** [comment]
Or if you do want to follow the office style, try putting a folder in the bg. This looks kinda similar to MS Word.

**Comment by EukalyptenHD** [comment]
Simple and rounded _(taking @kumarharsh's suggestion on something that represents a folder)_. 

![image](https://user-images.githubusercontent.com/44278658/59153368-9518f100-8a4f-11e9-8b46-fb35806cad39.png)

**Comment by zhangzp9970** [comment]
@kumarharsh I think the new office icon is OK, it looks beautiful and unified.:smiley:

**Comment by yusrilibnu** [comment]
I always monitor this project, I think this is a good prospect. I am a graphic designer and I want to help. This is a slight revision of the existing concept. if you like it please contact me.

![fix icon-100](https://user-images.githubusercontent.com/50422465/59165971-a3e5cd80-8b4d-11e9-9c7b-2846841bc75a.jpg)

**Comment by yusrilibnu** [comment]
and this another concept based on basic uwp icon
![Artboard 2-100](https://user-images.githubusercontent.com/50422465/59166272-122c8f00-8b52-11e9-9176-da2033af5092.jpg)

**Comment by duke7553** [comment]
I really like these. The community can can consider them when leaving feedback.

**Comment by duke7553** [comment]
After seeing the feedback so far, I'm leaning towards a folder-shaped icon. My reasoning is that "utility apps" like file explorers, etc. need certain icons because they're what we're trained to look for.

**Comment by kumarharsh** [comment]
Taking a leaf out of the fluent design icons... How does this look?

![files-icon](https://user-images.githubusercontent.com/760112/59189785-acafc100-8b98-11e9-93c5-7f563504262c.png)

**Comment by chrisquim** [comment]
in my own opinion, i think its more appealing and smooth transtition if the app icon reflects a close resemblance of the current Windows File Explorer icon. ofcourse with a little bit of twist and some fluent design finishes. just saying. :)

**Comment by kumarharsh** [comment]
Looks delicious!, but I think MS *might* have a problem with an icon looking too similar to theirs? What if you modify the holder into some other form...
Also, the number of tabs might not translate well to lower resolutions, though I haven't tried to scale them myself.

**Comment by chrisquim** [comment]
thanks for the commentary. :)
• yea it could also trigger copyright implications due to close resemblance (if Microsoft will really take a heat on a solo-yet-cool-innovative developer.). Tho a metaphor design and more subtle tweaks can be done for defense.
• Currently i dont have any better alternative idea for the holder., [open for suggestions/modifications].
• I kinda worried to about the tabs representation for lower resolution, i think it can be resolve thru color tweak, custom subtle outline for small icon and pixel-perfect aligning.

nevertheless, its just an initial proposal if the developer might find a taste on this. there's always a room for improvement.

**Comment by yaichenbaum** [comment]
@chrisquim looks amazing! As @kumarharsh pointed out being similar to the file explorer one may cause some issues if Microsoft decides they don't want that. What do you think about removing the holder?

**Comment by SOI7** [comment]
I tried going for a middle ground between all the concepts posted here, what do you guys think?

![files_icon copy](https://user-images.githubusercontent.com/50930970/61188598-cbb2de80-a681-11e9-9d04-9a2ee8fd877e.png)

**Comment by yaichenbaum** [comment]
Really nice, the question that comes to mind with that concept is do we need to have the 'F' there?

**Comment by SOI7** [comment]
I'm not gonna lie, I'm not really into the new MS icons design language, I preferred the old white, minimalistic icons, but since they're going towards that direction... *shrugs*
That said, the F is there for two purposes: 
1) Replacing the handle in the original File Explorer icons
2) Following the new Office icons design, which has the initial of the app in a square above the other icon layers
I mean, it's not mandatory, but I kept it for consistency.

P.S. @yaichenbaum (Hopefully I'm not asking a too personal question) I saw you're the one in charge of the repo now, are you also contributing to the coding as well now that Duke is gone?

**Comment by yaichenbaum** [comment]
I am not in charge, I currently don't have enough experience for that. I have been doing very small changes to the code base that I know will not mess anything up, Duke is still looking for a new lead dev. What I am doing is keeping track of issues and hopefully taking care of the store release when ready.
I am also merging pull requests so please keep them coming.
About the icon, not all of the new icons ie the your phone icon have the initial of the app. Neither does the terminal icon. I think if we end up using your concept there should be a vote if we keep the initial or not.

**Comment by SOI7** [comment]
I'll leave the decision to you guys for the inclusion of the F, then

**Comment by ArtexJay** [comment]
Love that last icon, would look great.

**Comment by yaichenbaum** [comment]
@chrisquim can you see if you can keep the idea but tweak it just a little to look a little more different then the built in file explorer?

**Comment by avknaidu** [comment]
@yaichenbaum @SOI7 why not remove the Black box with "F" completely and use just folder? like Terminal and YourPhone app?

**Comment by SOI7** [comment]
Up to @duke7553 , he had the F box in his original concept and I kept it to be loyal to his idea. If he wants it to go, I can spin off another concept

**Comment by duke7553** [comment]
I've received design feedback that advises not to include the F box because certain utility apps don't need them for recognition

**Comment by SOI7** [comment]
Final verdict, then:

![files_icon_final](https://user-images.githubusercontent.com/50930970/62235246-ccab7600-b3cc-11e9-983f-3486090674b7.png)

**Comment by duke7553** [comment]
@SOI7 That looks incredible. Great work everyone, but I think for now, this seems like the leading choice.

**Comment by duke7553** [comment]
Question to address: Will it blend in well on a dark taskbar?

**Comment by SOI7** [comment]
Thank you! I guess the gradients and the grey should make it neutral for both light and dark modes, but a test should be mandatory to figure it out I believe. 
Side note: in which format and layouts do you need this icon?

**Comment by avknaidu** [comment]
Nope. Terminal icon is also dark shade. but on Dark Taskbar, It looks fine. Because its lighter shades of Black / Grey. And the color choice on this icon is also similar to that of Terminal New Icon. So it should be fine.

**Comment by yaichenbaum** [comment]
I think a holder is important to have, just a plane folder looks like... just a folder, with the holder it indicates its a storage location that can have folders within it.

**Comment by SOI7** [comment]
I won't be at my pc for the following three days, but I was thinking about a possible folder holder with a completely different shape, to stand out more from the Windows Explorer icon. Maybe a semi-triangular holder on the bottom right?

**Comment by duke7553** [comment]
I thought about the designs thus far and I probably would put myself in agreement with @yaichenbaum . Files as an app takes pride in meaningful design choices. So we should add some kind of triangle-shaped folder holding device to the icon. Ideally, with a color that stands out well, but doesn't look too playful.

I'll experiment with this more when I get a chance today.

**Comment by maxxxlarsson** [comment]
> and this another concept based on basic uwp icon
> ![Artboard 2-100](https://user-images.githubusercontent.com/50422465/59166272-122c8f00-8b52-11e9-9176-da2033af5092.jpg)
> 
> ![Artboard 3-100](https://user-images.githubusercontent.com/50422465/59166432-c1b63100-8b53-11e9-91e1-c7de7d1f9a4a.jpg)

I think the bottom icon with almost the same colours as the native File Explorer added would be neat!

**Comment by SOI7** [comment]
I'm back! I had the time to brainstorm two possible holders. One is the triangle shape we thought earlier, the other one is a more complex shape that I tried to do following the shapes of the whole icon for consistency reasons. The color palette is still black/white for neutrality and zero risks of Windows 10 themes conflicts:

![files_icon_final3](https://user-images.githubusercontent.com/50930970/62423316-c57fb300-b6bf-11e9-828e-94bc3b60a81e.png)

![files_icon_final2](https://user-images.githubusercontent.com/50930970/62423317-c9abd080-b6bf-11e9-9d0f-41c8575b5168.png)

Feedback is welcome as always

**Comment by yaichenbaum** [comment]
Both are amazing!

**Comment by duke7553** [comment]
I'd prefer the one with the triangular holder as long as it's shifted more inwards. The holder should almost line up with the edges of the folder, right? Otherwise, it looks like we've found our new icon.

**Comment by SOI7** [comment]
Like this?

![files_icon_final](https://user-images.githubusercontent.com/50930970/62424914-70e73280-b6d5-11e9-95e2-627e0feff038.png)

I'm including also a no-shadow variant, because I guess the shadowed one would be better for the splash screen and this one for the taskbar:

![files_icon_final_noshadow](https://user-images.githubusercontent.com/50930970/62424922-8c523d80-b6d5-11e9-8481-6ab020ff2353.png)

**Comment by yaichenbaum** [comment]
Based off @SOI7 concept but stays a little closer to the existing icon 
![image](https://user-images.githubusercontent.com/39923744/62425276-56966000-b6a7-11e9-8695-9a3e3b5a68ba.png)

**Comment by BaRRaKudaRain** [comment]
I don't like this icon, because Office 2019 icons seems to be ugly IMHO. In my opinion you should not change the icon. It's beautiful as it is. 

-----------------------------------
Outsider and your best friend
Nate (BaRRaKudaRain) Marshall
(1995-present time)

**Comment by yaichenbaum** [comment]
@BaRRaKudaRain the issue with keeping as is, the app is not from Microsoft, by using the same icon it can run in to copyright issues. The idea is to keep it similar but changing the style of the holder for example. If you have any concepts or feedback on the existing ones please share it.

**Comment by duke7553** [comment]
After some discussion, I designed the tweaked version of what we have above. https://drive.google.com/file/d/1YDcD1RCpB0HbdyHsLOIEOm_dt3AjA4rD/view?usp=drivesdk

**Comment by generalguy41** [comment]
I like the office 2019 style theme the best, but that's just me. I'm honestly not a fan of the "traditional" colour theme, and thing it should be something else, maybe just a monotone version. I also like the solid folder holder thing as opposed to one with a hole in it.

**Comment by SOI7** [comment]
Are we allowed to use the Windows 10 File Explorer color palette to begin with? I thought it was not copyright-friendly

**Comment by yaichenbaum** [comment]
@SOI7 I asked about the same question to some other designers and they felt as long as the style was changes somewhat it is ok, if others here feel differently then we can definitely change it.

**Comment by SOI7** [comment]
Well, I did all I could to improve my icons, the last thing I could do is recoloring mines to match the yellow-blue palette, but it's up to you if you want yours or mine. It's your project

**Comment by Henboy10** [comment]
> Well, I did all I could to improve my icons, the last thing I could do is recoloring mines to match the yellow-blue palette, but it's up to you if you want yours or mine. It's your project.
> 
> EDIT: This will be my last iteration:
> 
> ![files_icon_final](https://user-images.githubusercontent.com/50930970/62554555-9a3cc580-b871-11e9-8a09-a52527d427b0.png)
> ![files_icon_final_noshadow](https://user-images.githubusercontent.com/50930970/62554556-9ad55c00-b871-11e9-8a38-7dcc76ec8a9a.png)

I do prefer it with color.

**Comment by kumarharsh** [comment]
@SOI7 the last iteration is the bomb! Ship it!

**Comment by SaturnSoftware** [comment]
maybe it could be based on the new terminal icon?

**Comment by yaichenbaum** [comment]
The two final icons that we are still deciding on is the one from @SOI7 and https://drive.google.com/file/d/1YDcD1RCpB0HbdyHsLOIEOm_dt3AjA4rD/view

**Comment by SaturnSoftware** [comment]
so it's too late to make revisions at this point?

**Comment by yaichenbaum** [comment]
@SaturnSoftware Absolutely not, the icon by @SOI7 and https://drive.google.com/file/d/1YDcD1RCpB0HbdyHsLOIEOm_dt3AjA4rD/view are just the ones we like the most so far, if someone has a better idea then we will definitely look in to it.

**Comment by Efreak** [comment]
Suggestion: The cutoff rectangle on @SOI7 's [post](https://github.com/duke7553/files-uwp/issues/136#issuecomment-517997192) looks like a decent icon for an sdcard. Use an icon that works with overlays, then apply overlays to different drives, like MS itself does. Overlays needed depend on current/future functionality, but could include: desktop, hdd, downloads, docs, pictures, videos, music, network drive, internet, network pc, user folder, cloud storage, favorites, network, etc.

**Comment by SaturnSoftware** [comment]
could i ask what the triangle is supposed to represent?
i don't really understand it's purpose and by further extent i don't think your average user would either

**Comment by yaichenbaum** [comment]
The triangle is meant to represent a file holder. This indicates it is like a cabinet with multiple folders and files.

**Comment by Henboy10** [comment]
> could i ask what the triangle is supposed to represent?
> i don't really understand it's purpose and by further extent i don't think your average user would either

I, personally, got it right away. It's like one of these 
![image](https://user-images.githubusercontent.com/22181579/64219246-58139d80-ce8a-11e9-90e8-cc1e9a458b5b.png)

**Comment by SaturnSoftware** [comment]
oh i've never seen one of those

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64287879-cf9b0880-cf2e-11e9-9ff0-0fc281f8a996.png)

**Comment by Henboy10** [comment]
When will the next version be released? We could get a survey out asking people to select their favorite icon/variation. That winning vote would be the icon on the next Microsoft Store release.

**Comment by yaichenbaum** [comment]
Great idea! I want to keep this issue open for a little longer to give some time for a few more concepts. Once a few finalists are chosen I will create a Microsoft Forms survey to choose from the list. If @duke7553 agrees I would like to choose a deadline for this.

**Comment by duke7553** [comment]
### Community Survey Thoughts and Some Ground-Rules
I think a community survey would be a great idea. We can get the agreed upon app icon as soon as the next update which will be relatively-minor and geared towards bug fixes. No deadlines yet, but we will use the data gathered from the survey to influence the next icon. However, we should hold off on the survey until the contributors in this thread at least agree on our top three or so favorite icons and then include them as survey choices. In the event the community picks an icon we weren't expecting, we'll iterate upon the chosen design to create a "compromise icon."

_**Disclaimer**: By submitting your icon here, you are contributing the entire design to this project. While there will never be a paid version of the app, Files, that includes your icon design submission, the developers and users of Files are under no obligation to give you credit for any uses and/or derivatives. I will provide a "Special Thanks (Credits)" section for the designer(s) who's submission is ultimately voted on. If you have any questions please let me know, or if you no longer agree to these principles for whatever reason, you are responsible for deleting your post and/or notifying me._

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/67162968-9fb99000-f337-11e9-813a-e7f60a7d9513.png)

**Comment by yaichenbaum** [comment]
### Update 10/20/2019
![image](https://user-images.githubusercontent.com/39923744/67163127-3e92bc00-f339-11e9-84d8-0a1cc5b5bad9.png)

I would love to get some feedback which of these icons **you** like better. We love all of the icons shared here and picking one is a hard choice. We would like to start the process on picking a final version that we will fine tune to work in different resolutions.
Thank you.

**Comment by szaimen** [comment]
I Like this one the most:
https://user-images.githubusercontent.com/39923744/64287931-e9d4e680-cf2e-11e9-8924-7f615e09758c.png

**Comment by generalguy41** [comment]
> ### Update 10/20/2019
> ![image](https://user-images.githubusercontent.com/39923744/67163127-3e92bc00-f339-11e9-84d8-0a1cc5b5bad9.png)
> 
> I would love to get some feedback which of these icons **you** like better. We love all of the icons shared here and picking one is a hard choice. We would like to start the process on picking a final version that we will fine tune to work in different resolutions.
> Thank you.

The one on the right

**Comment by Henboy10** [comment]
I prefer the one on the left. Although I'd be happy with either.

**Comment by jeffsieu** [comment]
> ### Update 10/20/2019
> ![image](https://user-images.githubusercontent.com/39923744/67163127-3e92bc00-f339-11e9-84d8-0a1cc5b5bad9.png)
> 
> I would love to get some feedback which of these icons **you** like better. We love all of the icons shared here and picking one is a hard choice. We would like to start the process on picking a final version that we will fine tune to work in different resolutions.
> Thank you.

How about the left "holder" with the right folder?

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/67396070-f65fdd80-f574-11e9-876f-e9f40dfd4231.png)
![image](https://user-images.githubusercontent.com/39923744/67396083-fbbd2800-f574-11e9-8374-8f48eb41ff3d.png)

**Comment by SOI7** [comment]
Fusion of both on the right seems the perfect compromise to me

**Comment by duke7553** [comment]
I like the one on the right, but perhaps the colors for each of the strips (excluding the blue holder) should be slightly tweaked to match that of the left icon.

**Comment by SOI7** [comment]
> I like the one on the right, but perhaps the colors for each of the strips (excluding the blue holder) should be slightly tweaked to match that of the left icon.

![67396113-08da1700-f575-11e9-8229-468e6d64532b](https://user-images.githubusercontent.com/50930970/67477413-4f557180-f65a-11e9-81f3-f2051177375f.png)

Like these?

**Comment by duke7553** [comment]
These look great! Well, then it looks like the consensus is around the second one in the comment above. I suppose we can implement it this weekend.

**Comment by yaichenbaum** [comment]
@SOI7 those look amazing! Do you have versions in smaller sizes as well so we can start tweaking for other resolution's?

**Comment by SOI7** [comment]
> @SOI7 those look amazing! Do you have versions in smaller sizes as well so we can start tweaking for other resolution's?

No, but I can spin them off easily. Which formats/resolutions do you need?

**Comment by yaichenbaum** [comment]
Do you have a Figma file or other source file?

**Comment by SOI7** [comment]
Never heard about Figma before, I made my icons using Gimp

**Comment by yaichenbaum** [comment]
Ok, I will recreate them in Figma for ease of access and sharing between all of us.

**Comment by yaichenbaum** [comment]
https://www.figma.com/file/IGYqLFl38fJvaPH9JbOrJ9/Files-UWP-Icon?node-id=0%3A1

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/67494376-18c22b80-f647-11e9-8da3-84ad0ee3ac0f.png)

**Comment by duke7553** [comment]
Thank you everyone for the amazing feedback that far exceeded my expectations! We've now decided on a brand-new icon for Files that will show up in the next release. This truly great icon was only possible due to the suggestions from the community; especially: @SOI7 @jeffsieu and @yaichenbaum 

![image](https://user-images.githubusercontent.com/20365014/68079512-3a4ab200-fdc1-11e9-98f2-c287c71f80bd.png)
