### ISSUE TITLE
Rapid Back/Forward Navigation Results in Crash

### ISSUE THREAD

**Issue by duke7553** [duke7553/files-uwp#137]
Rapidly pressing these buttons results in crash. Limit this to prevent crashes.

More work on this will be coming soon.

**Comment by EukalyptenHD** [comment]
It crashes if you spam the refresh and "Copy Path" buttons also.

**Comment by EukalyptenHD** [comment]
I tested the "Share" button also in the share section and it ended up doing this after spamming it:

![image](https://user-images.githubusercontent.com/44278658/59153127-7d8b3980-8a4a-11e9-8b59-7615243f1df9.png)

**Comment by duke7553** [comment]
First phase of fixing this.
![image](https://user-images.githubusercontent.com/20365014/59480690-a38c5180-8e2f-11e9-8a4a-0eb0eef58db3.png)

**Comment by duke7553** [comment]
> I tested the "Share" button also in the share section and it ended up doing this after spamming it:
> 
> ![image](https://user-images.githubusercontent.com/44278658/59153127-7d8b3980-8a4a-11e9-8b59-7615243f1df9.png)

Can't reproduce this one.

**Comment by duke7553** [comment]
Well, after a brief QA check for this bug, I think my work here is done. I'll leave this open for 24 to allow more discussion before I close this.
