### ISSUE TITLE
Allow to minimize menu ribbon

### ISSUE THREAD

**Issue by TailyFair** [duke7553/files-uwp#138]
It would be great if it was possible to minimize menu ribbon similar how it's done in regular File Explorer and Office programs, since menu ribbon is not always needed and it takes quite a bit of space.

Double clicking on menu tab would toggle ribbon between minimized and shown.
If minimized, single click on menu tab temporarily show ribbon until further action.

**Comment by duke7553** [comment]
Pro tip: [CTRL + Click] a ribbon header item to minimize the ribbon. Of course I'll work on a toggle button for this as well.

**Comment by yaichenbaum** [comment]
This will be included in the v0.7 release.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
