### ISSUE TITLE
Installation instructions on readme

### ISSUE THREAD

**Issue by Poopooracoocoo** [duke7553/files-uwp#141]
Related: 
#92
https://www.youtube.com/watch?v=1wSA8PYKhpA

**Comment by duke7553** [comment]
There probably won't be a need for this after Files makes it to the Store. About that: The reviewers found a few bugs with Files that need to be fixed before it can be published. These are topping my priority list right now.

**Comment by duke7553** [comment]
I'll add this on a later date.

**Comment by Poopooracoocoo** [comment]
I feel like a link to the youtube video would be good enough for now

**Comment by duke7553** [comment]
@Poopooracoocoo Thank you for your contributions to Files and WinUI!
