### ISSUE TITLE
Tracking Issue for WinUI TabView Control Implementation

### ISSUE THREAD

**Issue by Poopooracoocoo** [duke7553/files-uwp#143]
I understand that WinUI is working on a tab control but I guess it could be tracked here

**Comment by duke7553** [comment]
Yes, I'll update the title to reflect this effort.

**Comment by duke7553** [comment]
- [ ] Rounded Corners
- [ ] Tab Tearing
- [ ] Optimize new tab behavior to free memory

**Comment by duke7553** [comment]
Unless I find any massive problems, this is targeted for the next update.

**Comment by duke7553** [comment]
Changes now in master

**Comment by duke7553** [comment]
![image](https://user-images.githubusercontent.com/20365014/64645322-ac66d200-d3e2-11e9-89a5-5541467d61b4.png)
