### ISSUE TITLE
Fluent reveal effect missing on navigation pane and favorites

### ISSUE THREAD

**Issue by Poopooracoocoo** [duke7553/files-uwp#144]
The edges glow but when the cursor is over an item, there is no effect.

**Comment by duke7553** [comment]
I made some changes to the styling to address this. They're now in master, and especially noticeable in dark mode.
![image](https://user-images.githubusercontent.com/20365014/59554982-98ddd380-8f79-11e9-8749-31343e5ad1bf.png)
