### ISSUE TITLE
Releasing a limited beta to the store

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#145]
#142 Do you think having a beta in the store that is hidden and only people who sign up can access makes sense? That would solve certificate issues as well as making updating to the latest version a little easier, just a though I had...

**Comment by duke7553** [comment]
I still have some issues to fix before the final release, so I definitely think this is how Files will initially enter the store. I'll start this process again for the limited beta this time.

**Comment by yaichenbaum** [comment]
Sounds great.
