### ISSUE TITLE
OneDrive folder confusion

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#146]
I don't get how the OneDrive integration is handled in files UWP. When I navigate the OneDrive folder, I see only two of the folders I have on my account, and I only see files dated 'til 2017. Is this a bug or some limitation due to Files UWP not being able to see some OneDrive file types (like Files On Demand)?
Side Note: OneDrive navigation is also quite unstable and causes crashes, but it could be due to the aforementioned issue

**Comment by yaichenbaum** [comment]
We will be working on tighter OneDrive integration in the future. We will update here when we have more information.

**Comment by yaichenbaum** [comment]
@SOI7 I imagine it has to do with Files loading the wrong path for OneDrive. There is a fix for this in v0.7 that should detect the correct path as well as give you an option to set a custom path in case the one we detect is wrong.
Please reopen if the issue still occurs after we release v0.7.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
