### ISSUE TITLE
Up Button

### ISSUE THREAD

**Issue by amirrammari** [duke7553/files-uwp#148]
Hi, Please add up button
![vs](https://user-images.githubusercontent.com/23485114/59966794-09cf3f00-94d6-11e9-84e9-b15fb6dc35b9.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Dubstepwolf123** [comment]
The left arrow button already performs the same action as the default windows up arrow button does it not? It leaves the current folder and goes back to the parent folder...

**Comment by duke7553** [comment]
Because of the demand for this feature, it will be added soon.

**Comment by duke7553** [comment]
Navigating up is now finished and enabled in master. This will come to everyone in a future update to Files.
![image](https://user-images.githubusercontent.com/20365014/61754823-d573ca80-ad82-11e9-9aba-47d7b22eba24.png)

Commit: https://github.com/duke7553/files-uwp/commit/5aebbc72be9088eafb86c4d0c2571fbb69939fbb
