### ISSUE TITLE
Missing prompt to replace an existing file when copy-pasting

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#149]
We should be able to replace a file if we copy and paste (or cut and paste) a copy of it in the same directory. Right now Files UWP simply creates a copy of the file

**Comment by yaichenbaum** [comment]
We are tracking this issue here #212

**Comment by yaichenbaum** [comment]
We are tracking this in issue #189.

**Comment by yaira2** [comment]
Support for replacing existing items is now available. You can download the latest version of Files from our website https://files.community/download
