### ISSUE TITLE
Properties doesn't show up properly

### ISSUE THREAD

**Issue by armaan115** [duke7553/files-uwp#151]
**Viewing the properties of a file or folder doesn't work as intended.**

Didn't modify installation in any way, just installed Files UWP a few hours ago. Installed version 0.5. Upon viewing the properties of a **file** in Files UWP, the following shows up:

![alt text](https://i.ibb.co/tcd9THP/property-error.png "Property bug for files")

I tried other files to see if it was the file's fault but all the files I tried returned with the same thing.

Now for folders, its a bit different. If you **right click a folder and press 'Properties'**, nothing will show up. But, if you **press Properties from the ribbon,** it will show up the same thing it shows for files.

![alt text](https://media.giphy.com/media/QaXfScI9g6tOGYSuRm/giphy.gif "Property error for folders")

**Comment by yaichenbaum** [comment]
This is not anything you are doing wrong nor is it a bug, it is not done being implemented. This feature is planned to be included for the store release #142
