### ISSUE TITLE
Search bar doesn't work

### ISSUE THREAD

**Issue by armaan115** [duke7553/files-uwp#152]
**Using the search bar in Files UWP doesn't work**

Searching up a file in Files UWP doesn't seem to be working. I was trying to search for some files in a folder but nothing pops up or shows up. Tried searching up in the Favorites tab and other folders but nothing still pops up or shows up.

**Comment by SOI7** [comment]
Iirc it has yet to be implemented

**Comment by yaichenbaum** [comment]
Please see #142

**Comment by yaira2** [comment]
Support for searching items is now available. You can download the latest version of Files from our website https://files.community/download
