### ISSUE TITLE
Unexpected error on launch (1903)

### ISSUE THREAD

**Issue by GuusLieben** [duke7553/files-uwp#157]
When opening the Files UWP on Windows 10 (1903) the following error occurs : 
![image](https://user-images.githubusercontent.com/10957963/60499195-4827e380-9cb8-11e9-9494-b589dd2e841d.png)

This is on the first launch, no changes made. Version 0.5.0.0 x64

**Comment by duke7553** [comment]
Thanks for reporting this issue. Is it still occurring on v0.6.2 with the same drives plugged in? Does the error occur only when the drives/storage devices are plugged in? If so, what are they?

**Comment by GuusLieben** [comment]
Still occurring on 0.6.2 with the same drives plugged in.

**Drives plugged in :**
_Samsung SSD 750 EVO (500GB)
Toshiba MQ01ABF050 (500GB)
Toshiba MQ01ABD100 (1TB)
WDC WD10JPVX-75JC3T0 (1TB)_

None of the drives are using Bitlocker. All carry primary partitions.
The 1TB Toshiba is a Shared drive, but the issue occurs even when it is not shared

**Comment by duke7553** [comment]
This bug is no longer reproducible in v0.6.6 . Please reopen if you still have this problem.
