### ISSUE TITLE
Add option to clear single item from recent items list

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#160]
Sometimes I want to remove one item from the recent item list, right now the only solution is to clear the full list.

The ideal solution would be to add an option to the right click context menu that allows you to remove one item without clearing the full list.

Another idea would be to have a small 'x' all the way at the right of ever item that lets you remove them from the list, this may confuse users though and make them worry they are deleting the file.

![image](https://user-images.githubusercontent.com/39923744/60772437-6af53600-a0c4-11e9-813c-116add44058d.png)

**Comment by RobbyRobbyRobby** [comment]
Hi,
I've got a PR ready if I can be added as a contributor to make a new branch.
Cheers,
Rob.

**Comment by yaichenbaum** [comment]
@RobbyRobbyRobby the best way to do it would be to fork the repository and open a PR from there.

**Comment by duke7553** [comment]
@RobbyRobbyRobby Just click the fork button. You can clone the copy of the repository from your git account, make changes, and open a pull request across the forks
