### ISSUE TITLE
Revert to old design

### ISSUE THREAD

**Issue by Javahase** [duke7553/files-uwp#166]
**Describe the solution you'd like**
I would like to have the old design from version 0.4.9 back or maybe an option to do so.

**Describe alternatives you've considered**
I would downgrade to version 0.4.9 but it's not a long term solution due to the lack of features in this version.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
I want a design like this:
![image](https://user-images.githubusercontent.com/42071641/61145059-d8df9a00-a4d6-11e9-9811-3f7a0bfa9188.png)

**Comment by flimosch** [comment]
Please do this.

**Comment by yaichenbaum** [comment]
What was in the old design that you liked? Perhaps it would be better to adjust the new design based on that you and other users want.

**Comment by Javahase** [comment]
> What was in the old design that you liked? Perhaps it would be better to adjust the new design based on what you and other users want.

First of all, I would like the Acrylic (the transparent) sidebar back. Also, I would appreciate if you could add an option to change the layout of the filemanager. (not of the files)

**Comment by yaichenbaum** [comment]
An option for acrylic on the sidebar can definitely be added as an optional customization, would be great if you opened a separate issue for that.
What do you mean by changing the layout of the file manager?

**Comment by Javahase** [comment]
> An option for acrylic on the sidebar can definitely be added as an optional customization, would be great if you opened a separate issue for that.
> What do you mean by changing the layout of the file manager?

I really dislike all the options being on the top. I would prefer the settings button on the bottom left. I would like to just have the sidebar back like in the screenshot I provided.

**Comment by SOI7** [comment]
I agree about the acrylic sidebar, but removing the ribbon on the top imho would be inconsistent with the current Windows design language, don't forget this File manager is supposed to replace the Win32 app and having all the options hidden inside a Settings button would make it more clunky. That said, I remember Duke planned to add the option to hide the ribbon at a certain point, so that may be the best solution for all of us

**Comment by yaichenbaum** [comment]
An option to hide the ribbon is definitely the plan, in the mean time you can use ctrl + clicking on a header to hide collapse the ribbon.

**Comment by duke7553** [comment]
@Javahase Hey, there are plans for a tablet-optimized layout mode.

**Comment by ByteZ1337** [comment]
> @Javahase Hey, there are plans for a tablet-optimized layout mode.

Will you add back the Acrylic sidebar?

**Comment by yaichenbaum** [comment]
An option to collapse the ribbon as well as turn back on acrylic will be available in the future.

**Comment by ArtexJay** [comment]
Maybe an acrylic ribbon would look very pleasing, but of course have the option to disable it.

**Comment by yaichenbaum** [comment]
There is an open pull request that adds an option to turn on and off acrylic on the side bar #321. Version 0.7 will also include acrylic on the title bar and and option to collapse the ribbon.
