### ISSUE TITLE
Automatically extend columns according to the folder size

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#168]
As shown in the picture, each time a folder is opened, there's a significant gap on the right. 

[https://imgur.com/RZchn6q](url)

You can resize the last column and extend it to the whole length manually, but I think it should actually be expanded on default, like in the second picture:

[https://imgur.com/fKxEfuS](url)

**Comment by yaichenbaum** [comment]
Another option would be to have a preview of selected files in that extra space, what do you think?

**Comment by SOI7** [comment]
I'm indifferent to it as far as it's optional, in that case if the preview is disabled the columns should occpy the whole length, like in the second picture I posted

**Comment by yaichenbaum** [comment]
Changes made with dc28780a05a2f61ea0c531d5ff5f2177f81a26b3
