### ISSUE TITLE
Files Instalation Failed

### ISSUE THREAD

**Issue by vallerydelexy** [duke7553/files-uwp#17]
![image](https://user-images.githubusercontent.com/17786532/52607428-c2da9880-2ea8-11e9-9812-570b849a36d6.png)
App Installer failed to install package dependencies. Ask the developer for Microsoft.VCLibs.140.00.Debug package. 

~\Files_0.4.5.0\Files_0.4.5.0_x64_Debug_Test\Files_0.4.5.0_x64_Debug.appx

**Comment by vallerydelexy** [comment]
![image](https://user-images.githubusercontent.com/17786532/52607628-8ce9e400-2ea9-11e9-9cf4-e06dcee2c7d3.png)
Either a new certificate must be installed for this app package or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain was processed but terminated in a root certificate that isn't trusted (0x800B0109)
~\Files_0.4.5.0\Files_0.4.5.0_x64_Debug_Test\Files_0.4.5.0_x64_Debug.appx
after failing to install once

**Comment by duke7553** [comment]
Yeah, there should be a powershell script which automates the whole side load process. Try running that first, and we’ll reopen if needed.
