### ISSUE TITLE
Design: Black header looks out of place

### ISSUE THREAD

**Issue by matthew4850** [duke7553/files-uwp#172]
The files header beeing pure black looks out of place.

**Comment by duke7553** [comment]
@matthew4850 Were you referring to this: 
![Annotation 2019-07-16 200355](https://user-images.githubusercontent.com/20365014/61337822-e6619080-a804-11e9-9965-cb8eb78d80a2.png)

**Comment by yaichenbaum** [comment]
He means 
![image](https://user-images.githubusercontent.com/39923744/61338059-cf6f6e00-a805-11e9-9265-70e986734d23.png)

**Comment by matthew4850** [comment]
No, in dark mode the header above files that shows name, date, type etc

**Comment by duke7553** [comment]
Oh, the resource that sets that header color is hard-coded in by the creators of the control. There is an open toolkit bug report where they propose allowing us to customize it.

**Comment by duke7553** [comment]
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2373

**Comment by duke7553** [comment]
I have code in place that should change the color properly when this is fixed by the toolkit devs.

**Comment by matthew4850** [comment]
ah ok, thanks

**Comment by Osoted56** [comment]
Hackearon mi cuenta
