### ISSUE TITLE
Auto-detect user folders paths

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#173]
User folders paths are stored in Windows Registry.

You can find them there : `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders`

| Folder | Windows Registry Key |
| --- | --- |
| Desktop | `Desktop`
| Downloads | `{374DE290-123F-4565-9164-39C4925E467B}`
| Documents | `Personal`
| Pictures | `My Pictures`
| Music | `My Music`
| Videos | `My Video`

*([Source](https://www.winhelponline.com/blog/windows-10-shell-folders-paths-defaults-restore/))*

You should be able to get these by using [Microsoft.Win32.Registry.GetValue](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.win32.registry.getvalue).

**Comment by yaichenbaum** [comment]
I believe we are already detecting user paths, the only one that is not using that method at moment is the downloads folder, thank you for the registry key.

**Comment by yaichenbaum** [comment]
@KaKi87 would this work?         `public static string DownloadsPath = string)Registry.GetValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders", "{374DE290-123F-4565-9164-39C4925E467B}", null);`

**Comment by yaichenbaum** [comment]
@KaKi87 Can you verify #209 helps, if not I will need to know what changes to make, thanks.,

**Comment by KaKi87** [comment]
Send me an APPX and I'll tell you

**Comment by yaichenbaum** [comment]
@KaKi87 Are you still on discord?

**Comment by KaKi87** [comment]
I leaved UWP Community.

**Comment by yaichenbaum** [comment]
Ok, try getting it from here https://1drv.ms/u/s!AsMjD6AbL8azjrsBdZBSzqXv7SdY_w?e=c561Be

**Comment by KaKi87** [comment]
I'm not ARM but x64 and the certificate seems not to work. Error code `0x800B0109`

**Comment by yaichenbaum** [comment]
@KaKi87 I will need to create a new package for you, I will try to do it later today.

**Comment by duke7553** [comment]
@KaKi87 This is fixed for the v0.7 release. Thank you for your patience.
