### ISSUE TITLE
Cut doesn't actually cut, but instead copies

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#175]
When you select a file and then select "Cut" from the ribbon, when you paste it in another path the file is actually copied, and the original file is still in its original location. Ntm you can't manually move files either through drag and drop, but I don't know if that's a bug or a UWP limitation

**Comment by duke7553** [comment]
This bug should now be fixed in master with commit https://github.com/duke7553/files-uwp/commit/cedbcc378284c2bf1c14bc00da7842156e06dd36
