### ISSUE TITLE
Go to letter

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#179]
I would like to be able to go to a letter in files listing while pushing a letter
Meaning : select the first file in current list order to start with the letter
Thanks

**Comment by yaichenbaum** [comment]
There is now an open pull request for this feature #266.

**Comment by yaichenbaum** [comment]
This is addressed in v0.7.
@KaKi87 I hope you are happy with the recent improvements to Files UWP. I just want to thank you again for all your feedback which is helping us know what to work on next.

**Comment by KaKi87** [comment]
I'm sorry I didn't take time to test the app again since the first and last time. However, you did the right thing to notify me and I promise to test it soon. 😊

**Comment by yaichenbaum** [comment]
There is still much work to get done but we are trying our best to get the fundamentals taken care of. Looking forward for your feedback.

**Comment by KaKi87** [comment]
I'm sorry I can't find out where to download version 0.7 ?

**Comment by yaichenbaum** [comment]
Version 0.7 is still not published so the only way to access it is to build from the source code. Version 0.6.6 is the latest version release and you can get it in the store.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
