### ISSUE TITLE
Slow file listing

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#180]
I have some folders full of 2-8 GB ISOs, ZIPs and MKVs, listing these files is very slow.
Thanks

**Comment by duke7553** [comment]
This can't be fixed by me and is a heavy limitation with the current way Storage APIs work in UWP. https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/35684371-add-an-api-to-retrieve-all-files-from-a-folder-tha
