### ISSUE TITLE
Problem with cutting and pasting

### ISSUE THREAD

**Issue by Kokonutman** [duke7553/files-uwp#181]
**Is your feature request related to a problem? Please describe.**
When you cut a file and paste it somewhere else, the original file is simply copied rather than cut. This means you have to delete the original file after copying it, as the cut function does not work.

**Describe the solution you'd like**
Adding the ability to delete the original file once it is copied at the destination when the cut function is used

**Describe alternatives you've considered**
If deleting the original file is not possible, then it can be marked for manual deletion.

**Additional context**
I have tried this on my Windows 10 Home 64 bit PC

**Comment by yaichenbaum** [comment]
This has been fixed with 0b9705f, you can either build from the source code or wait for the next release to get the fix for this issue.
