### ISSUE TITLE
Re-direction of UWP design

### ISSUE THREAD

**Issue by mkmukund** [duke7553/files-uwp#185]
Re-direction of UWP UI design is requested as represented in this link....
https://www.behance.net/gallery/74300939/Windows-10-File-Explorer

**Comment by duke7553** [comment]
@mkmukund Thanks for the concept. Files follows Microsoft's Fluent Design trends already. Is there anything specific from that concept you'd like to see in Files? 

Please open an issue report for each one so we can evaluate their individual feasibility.

**Comment by duke7553** [comment]
Closing this in anticipation of your issue reports.
