### ISSUE TITLE
Improve Item Collision Handling

### ISSUE THREAD

**Issue by BothSamuel** [duke7553/files-uwp#189]
When renaming files or folders that know how to differentiate between uppercase and lowercase 

1. Go to 'any folder '
2. Click on 'rename, either file or folder'
3. type a lowercase name and then rename but uppercase.
4. The application does not detect the difference between upper and lower case letters.

Be able to rename files or folders with the same name, but have the application detect the difference between upper case letters.

![Files-UWP-rename](https://user-images.githubusercontent.com/47579807/61983657-7bf7df80-afbe-11e9-9937-8e6e42188472.gif)

 - OS Version: [Windows 10 1903 18362.239]
 - App version: [v0.6.2]

**Comment by yaichenbaum** [comment]
Thank you for reporting this issue.

**Comment by duke7553** [comment]
Thanks for reporting this issue.

**Comment by avknaidu** [comment]
@duke7553 @yaichenbaum  I opened a issue on github docs pages with winrt-api team [here](https://github.com/MicrosoftDocs/winrt-api/issues/1190). Feel free to check for feedback with the team.

**Comment by phanirithvij** [comment]
FYI this also happens in the File Explorer.

![help](https://user-images.githubusercontent.com/29627898/67279234-362cb380-f4e8-11e9-8d4e-bd104a752c73.gif)

**Comment by yaichenbaum** [comment]
@BothSamuel Is this still an issue in the latest release (v0.7.5)?

**Comment by BothSamuel** [comment]
> @BothSamuel Is this still an issue in the latest release (v0.7.5)?

Yes, it works very well. It's getting better and better.

**Comment by yaichenbaum** [comment]
@BothSamuel I tested in v0.7.5 and there is now a dialog that gives you the option to generate a new name or to replace the existing file. If this is still an issue, please let me know.
