### ISSUE TITLE
Not able to delete a file - Maybe System Specific

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#19]
Hey, @duke7553! 
Truly impressed with the attention to detail with the new [fluent ](https://www.microsoft.com/design/fluent/)design adaptation but I have a small but important bug over here. I couldn't delete any files or directories from the application but I could in the OG Windows Explorer. I still don't know if it is system specific or not but I'll soon use a Virtual Machine to check it out. Here is a video clip showing the bug.

[![Bug](https://i.imgur.com/2P8wBXZ.png)](https://i.imgur.com/VJe4Nmy.mp4)

**Comment by duke7553** [comment]
Yes, that will be fixed in the next release. Marking this as unimplemented.

**Comment by KartSriv** [comment]
@duke7553 Just an enhancement, while you're fixing this issue add deleting with the `del` key.

**Comment by duke7553** [comment]
These changes (including keyboard accelerator) are now in master. The next release, 0.4.7, will include this. Closing now.
![deletefunction_filesuwp](https://user-images.githubusercontent.com/20365014/52752598-6b7c1b80-2fc1-11e9-8335-4a48992036b9.jpg)

**Comment by KartSriv** [comment]
Thanks, @duke7553! For considering this issue and all the best!
