### ISSUE TITLE
Introduce Smooth Scrolling to files-uwp please.

### ISSUE THREAD

**Issue by Chara-Reborn** [duke7553/files-uwp#191]
**Is your feature request related to a problem? Please describe.**
I've taken a liking for UWP apps and their smooth scrolling. It's always been so fluent, yet it's missing from files-uwp.

**Describe the solution you'd like**
Introduce application-wide smooth scrolling whenever possible. Having a toggle in the Preferences menu is critical due to people not enjoying Smooth Scrolling, while others do.

**Describe alternatives you've considered**
No alternatives really can be considered for this, as it's a generic request.

**Additional context**
No additional context.

**Comment by yaichenbaum** [comment]
@duke7553 I feel this is more of a Win UI feature, not something that we can control.

**Comment by yaichenbaum** [comment]
WinUI is working on a new `DataGrid` control that we plan to implement when it is ready, this will likely include smooth scrolling.

**Comment by yaichenbaum** [comment]
While WinUI has still not released it's new `DataGrid` control, I just wanted to let you know that the GridView layout in Files UWP already has smooth scrolling. I hope this information is helpful.

**Comment by duke7553** [comment]
@Chara-Reborn Hello and thanks for the feedback.
Although we've done work to improve the performance when loading large directories in all of our layout modes, I understand how sub-par the DataGrid is without inertia and scrolling personality which is characteristic of modern apps. I spent a considerable amount of time last Winter exploring alternatives to the current DataGrid control, but didn't want to sacrifice other work just to reengineer a new control. 

We certainly plan on implementing the WinUI DataGrid when that becomes available in the future, but for now there's nothing else we can do to improve this area.
