### ISSUE TITLE
problem access folder download

### ISSUE THREAD

**Issue by Vinci989** [duke7553/files-uwp#192]
Attempting to enter the folder a message appears asking to give permission to view the files. However, the setting is already active and the problem persists.

- Version of the app 0.6.2
- Windows version 18362.239

**Comment by duke7553** [comment]
Hello. Thank you for this feedback. Can you please define what "certalla" is?

**Comment by Vinci989** [comment]
It meant folder. I'm not good with English. I apologize.

**Comment by yaichenbaum** [comment]
By any chance is the downloads folder set to hidden? This is a possible reason for the issue you are describing, if not we will continue to look in to it.

**Comment by Vinci989** [comment]
It is not hidden. It is set to read only.

**Comment by duke7553** [comment]
We have new changes coming in v0.7 that will auto detect your downloads folder from the Windows Shell. Please reopen if you can reproduce this in v0.7 when it's released.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
