### ISSUE TITLE
Optional Extended Sidebar

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#193]
Just throwing this as a reminder since @yaichenbaum asked to open it as a separate issue in #166

**Comment by yaichenbaum** [comment]
Thanks for the reminder, I added this to the project board.

**Comment by yaichenbaum** [comment]
After talking it over with some friends on the Win UI team and some conversation I had with @duke7553 a while back, it goes against the Windows design language specs to have acrylic on the sidebar, the acrylic affect is meant for transient surfaces and using it the wrong way can take away the wow affect.
This is still an option we can think about when creating a flags page to turn on and off advanced settings but as of now I will be closing this issue.
Thanks for all your feedback and helping make Files UWP the best it can be.

**Comment by yaichenbaum** [comment]
There is now an open pull request with this option #321.

**Comment by yaichenbaum** [comment]
This was implemented and will roll out with v0.7.

**Comment by yaichenbaum** [comment]
Its important to note its still off by default but its just one switch in settings to turn it on.
I want to thank everyone who kept sending feedback asking for this and not letting go until it got added, Files UWP is all about what **you** want and providing the customization you want so please keep sending feedback or comment on existing issues what you want to see next!

Here is a screenshot of the new changes
![image](https://user-images.githubusercontent.com/39923744/71328754-3ba77980-24ea-11ea-92d1-5c2eb9599593.png)

**Comment by ygorcortes** [comment]
This is fantastic! Quick question: is the title bar using acrylic too? It would be great if it is! (I can't be sure from the screenshot)

**Comment by yaichenbaum** [comment]
@ygorcortes The title bar is using acrylic, the only difference is that unlike the side bar the title bar has acrylic on by default and cannot be turned off.

**Comment by Darhagonable** [comment]
Just a thought but when the sidebar is acrylic I kinda would prefer the sidebar to extend all the way to the top like this. It would be cool to have it as an option. I know it's a lot of work for a pretty unimportant thing though but thought i could mention it regardless
![FilesUWP concept layout](https://user-images.githubusercontent.com/14127357/74107785-edbb0380-4b73-11ea-8060-7decadd366b0.png)

**Comment by yaichenbaum** [comment]
@Darhagonable I am not against it and if you want to give a shot at it then go ahead 😊. Otherwise, I will keep it in mind for the future.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).

**Comment by R3voA3** [comment]
@Darhagonable @yaichenbaum The side bar should definitely extent all the way to the top. The more I use Files UWP the more I find the current design irritating and with the acrylic it's even more prominent than before. Most UWP apps have the navigation menu extent all the way from the bottom to the top, so I think Files UWP should also use that design.

**Comment by yaichenbaum** [comment]
@R3voA3 There is a reason we removed Acrylic from the sidebar, in any case, I will be keeping this issue open for some time to gather more feedback.

**Comment by yaichenbaum** [comment]
@R3voA3 Although most UWP apps extend the navigation menu to the top, it's a little different from Files UWP because we have a ribbon and I feel that the current design looks better and keeps a familiar feel to File Explorer.
Another interesting piece of information is that in a few months from now WinUI 3 will be releasing, as a result, we will lose access to the `HostBackdrop` acrylic effect, there is a chance that it will return in future versions of WinUI but until then this whole request might be a little irrelevant.

**Comment by duke7553** [comment]
We will consider your feedback in the future when tailoring Files to future form factors.

**Comment by yaichenbaum** [comment]
@Darhagonable 
![image](https://user-images.githubusercontent.com/39923744/77868181-34d68400-7208-11ea-8ab9-d184a9fa8922.png)

**Comment by ygorcortes** [comment]
@yaichenbaum this seems awesome and I can't wait! Thank you!

**Comment by Darhagonable** [comment]
@yaichenbaum Awesome! thank you!
