### ISSUE TITLE
Cannot open user profile folders that location changed

### ISSUE THREAD

**Issue by Nomyfan** [duke7553/files-uwp#199]
When I clicked the download folder, it alerted that I had deleted the folder, which mainly because I had changed my download folder's location before.  At now my download folder's location is `D:\Downloads`.

![snipaste_20190802_013114](https://user-images.githubusercontent.com/19922814/62314511-c947e580-b4c5-11e9-936a-0c0a238215c6.png)

I have explorered the code and I found that is because a static folder path was defined. 
![snipaste_20190802_011938](https://user-images.githubusercontent.com/19922814/62314816-82a6bb00-b4c6-11e9-86f9-038363fdfc63.png)

In UWP, to operate with these folders, using classes in Windows.Storage namespace instead is a good choice. 

 - OS: [Windows 10 1903 18362.239]
 - App version: [v0.5.0]

**Comment by duke7553** [comment]
Hello,

Universal apps don't have direct access to the dynamic path of the user's download folder which is why Files has to guess where it is. If you want to override where Files checks, turn on Custom Locations in the Settings page.

Please try this and report back.

**Comment by Nomyfan** [comment]
OK, solved.
