### ISSUE TITLE
No way to sort from DataGrid

### ISSUE THREAD

**Issue by ZekromInfinity** [duke7553/files-uwp#20]
(Bugs)
- Feedback doesn't work so here I am.

- Music starts with the 1st name in alphabetical order no matter which I click or what order the folder is sorted on, after the first time, it will work normally. Also, it will always highlight the name or whatever the data is in a white box every time I click something.

- Opening downloads crashed the app.

(A question)
- Is it a common problem with UWP apps to crash or is it just me? I am asking because I have used windows phone and windows store apps on pc and they seem to crash, almost all of them. Please give me some insight into it.

Thank You

**Comment by ATecSolution** [comment]
About your question I find that uwp apps crash more then win 32 ones, more often in larger apps. But I do find that every Windows update improves the quality and decreases the amount of crashes.

**Comment by duke7553** [comment]
Sorting is unimplemented at the moment. This will be added in future release.

**Comment by carlosrfernandez** [comment]
There seems to be an unhandled exception when opening the Downloads folder. I'm also getting this.

**Comment by duke7553** [comment]
Quick question. Have you guys granted the app permission to access your filesystem? In my testing, it displays a prompt upon first access that transfers the user to a Settings page for this permission. Also, what windows version?

**Comment by duke7553** [comment]
(Version number of Windows 10) Example: 1803, 1809, or 1903

**Comment by carlosrfernandez** [comment]
In my case, I'm on 1809, I am compiling from source, I also targeted the SDK that comes with 1809 so it might be related to that. 

To answer your question: yes, I gave the app permission to access the filesystem.

If I have time I'll try to understand what is causing it and provide a fix.

**Comment by duke7553** [comment]
Thanks for the information. I can't seem to replicate this issue, but the app should load every non-pictures directory the same. Does it do this with other directories? Is it a certain type of file? 
Maybe try creating a folder in Windows Explorer and move each file into there until it loads properly in Files. That way, we can narrow things down.

**Comment by carlosrfernandez** [comment]
It happens in other directories as well, so far the exception is being thrown on PNG files, but I can't tell if it's ALL png files, or just some.

Another thing, after opening one of the problematic files' properties using Windows Explorer, it stopped failing, my guess is flag is set at OS level or something. Very weird.

**Comment by duke7553** [comment]
That is weird, but it should be handled now to prevent a crash.

**Comment by duke7553** [comment]
I'll change the title of this now to reflect recent changes.

**Comment by ZekromInfinity** [comment]
> 
> 
> Quick question. Have you guys granted the app permission to access your filesystem? In my testing, it displays a prompt upon first access that transfers the user to a Settings page for this permission. Also, what windows version?

yes i did because i am able to access other directories without any crashing

**Comment by duke7553** [comment]
@ZekromInfinity There will be some changes to handle this in the next release.

**Comment by ZekromInfinity** [comment]
> 
> 
> @ZekromInfinity There will be some changes to handle this in the next release.

Happy to know that, also I appreciate the work you do. I am GUI freak so I can't stand the sight of the legacy file manager that was released by Microsoft on store app and your work is actually 'Fluent' for the ecosystem too XD.

**Comment by duke7553** [comment]
I've got a lot of cool stuff planned for subsequent releases!

**Comment by yaichenbaum** [comment]
Changes made with #247.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
