### ISSUE TITLE
Open Terminal/CommandPrompt/PowerShell from current folder

### ISSUE THREAD

**Issue by calloncampbell** [duke7553/files-uwp#200]
**Is your feature request related to a problem? Please describe.**
It would be great if you could easily open up one of the supported console apps (Command Prompt, PowerShell and Windows Terminal) from any given folder. You can currently do this in Windows Explorer by typing "cmd" in the address bar.

**Describe the solution you'd like**
It would be great if you could easily open up one of the supported console apps (Command Prompt, PowerShell and Windows Terminal) from any given folder. This can be explicit button/menu command or support to parse the address bar for new input + enter key.

**Describe alternatives you've considered**
No alternatives exist for this app. 

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment]
This is easy to implement since the last changes that I made. Work on is in progress for opening a folder in cmd until arguments are supported in Windows terminal.

**Comment by duke7553** [comment]
The "Open in Terminal" option will now work when using a build from the master branch, but I still plan on giving users a setting to choose between CMD and Powershell by default.

**Comment by watermarkhu** [comment]
How about the new Windows Terminal?  Since we're all going UWP here....

**Comment by amirrammari** [comment]
Now I can open Command Prompt on the current folder.
Please add [Windows Terminal](https://github.com/microsoft/terminal) support.

![Files UWP](https://user-images.githubusercontent.com/23485114/72199991-eca19400-3458-11ea-970f-9ceca3f89174.png)

**Comment by duke7553** [comment]
@amirrammari I'm pretty sure we're still waiting on Windows Terminal to support arguments for the wt.exe command. Also, new changes coming soon will allow users to register custom terminals!

**Comment by yaichenbaum** [comment]
@lampenlampen Can you comment on this?

**Comment by lampenlampen** [comment]
So https://github.com/microsoft/terminal/pull/4023 adds support for Windows Terminal.

With this profile you should be able to open Windows Terminal.

``` json
{
      "id": 3,
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d \"{0}\"",
      "icon": ""
    }
```

PS: As far as i can tell, does the latest version of Windows Terminal not include this feature. You will need to build and install Windows Terminal from the master branch.

We should wait until a release version of Windows Terminal is available, until we support it out of the box.

**Comment by yaichenbaum** [comment]
@lampenlampen https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-9-release/

**Comment by lampenlampen** [comment]
1. Users with old `terminal.json`-files don't get the updated version automatically, because we don't override existing ones.

2. Powershell and Windows Terminal profiles are deactivated by default.

**Comment by lampenlampen** [comment]
We should consider creating a wiki page, where we collect the different terminal profiles.

**Comment by lampenlampen** [comment]
We should consider creating a wiki page, where we collect the different terminal profiles.

**Comment by yaichenbaum** [comment]
@lampenlampen What profiles do we support?

**Comment by lampenlampen** [comment]
cmd:
``` json
{
      "id": 1,
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "/k \"cd /d {0} && title Command Prompt\"",
      "icon": ""
}
```

Powershell:
``` json
{
      "id": 4,
      "name": "PowerShell",
      "path": "powershell.exe",
      "arguments": "-noexit -command \"cd '{0}'\"",
      "icon": ""
}
```

Powershell Core:
``` json
{
      "id": 2,
      "name": "PowerShell Core 6",
      "path": "pwsh.exe",
      "arguments": "-WorkingDirectory \"{0}\"",
      "icon": ""
}
```

Windows Terminal:
``` json
{
      "id": 3,
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-d \"{0}\"",
      "icon": ""
}
```

**Comment by yaichenbaum** [comment]
@lampenlampen Don't we add them automatically to the drop-down?

**Comment by lampenlampen** [comment]
If the profiles are in the `terminals.json` file, but only the cmd is enabled by default, because we don't know if powershell or Windows Terminal is installed.

**Comment by yaichenbaum** [comment]
Why don't we add logic for that? We already have something similar in place for detecting if QuickLook is installed so I imagine we can do the same here.

**Comment by lampenlampen** [comment]
QuickLook is a lot simpler to detect, because it creates a named pipe, which we can check for existence.

I spontaneously do not know of a way to detect, if a certain program is installed.

**Comment by szaimen** [comment]
I guess this is not possible (because you cannot run powershell and access the registry)?
https://keestalkstech.com/2017/10/powershell-snippet-check-if-software-is-installed/

**Comment by lampenlampen** [comment]
Technically we can run powershell and access the registry, because we have the `runFullTrustProcess`-permission.

The thing is, is it worth?
We surely can detect some or many cases, where pw or wt are installed, but i think not all.
For example what about a portable installation?

So I think especially pre version 1, it's not worth, because you simply have to copy and paste a profile into `terminals.json`.

**Comment by szaimen** [comment]
Okay, and then why not checking if the app is installed and if it wasn't found for whatever reason, ask the user to copy and paste the profile into terminals.json, if the user wants to use that feature?

**Comment by lampenlampen** [comment]
But we don't know in advance which profile a user wants to use.

So we end up asking every user, where we don't find for example Windows Terminal (due to not found or not installed) to select the exectuable. Even if the users wants to have nothing to do with Windows Terminal.

**Comment by szaimen** [comment]
That's why I would suggest asking and checking for the installation only if the user interacts with the "open in powershell/commandPrompt". As long as he doesn't use that feature I wouldn't ask him for the installation.

**Comment by duke7553** [comment]
If we know the package id of a uwp app, can't we query it? I feel like there was a way

**Comment by yaichenbaum** [comment]
@lampenlampen You can actually get read access to the registry without a FullTrustProcess.

**Comment by lampenlampen** [comment]
@yaichenbaum Are you sure? I thought every UWP app has it's own registry.
@duke7553 But PowerShell or Windows Terminal are not uwp apps.

I thought about it a little more:
We don't need the path at all, because the install location must be on the "Path"-variable.
So we can launch powershell and only have to recognize if it succeeded or not.

**Comment by yaichenbaum** [comment]
@lampenlampen Absolutely, we already do that to detect the path for the user folders.

**Comment by duke7553** [comment]
For v0.8 we'll work on detecting terminal emulator apps, so users won't have to add the profile each time.

**Comment by yaichenbaum** [comment]
I am excited to report that #542 adds support for launching terminal applications from the navigation bar. This will let you enter the name of any terminal in your profile and it will launch the terminal with the current path you are working in.
#543 includes a change that will automatically add a profile for Windows Terminal if it's installed. Detection for other popular terminal apps will be added in the future as well.

**Comment by yaichenbaum** [comment]
This issue should be fully addressed with the latest changes in the `develop` branch.
