### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by TalibDota** [duke7553/files-uwp#203]
**Taskbar Icon**
I love how the taskbar icon similar to Search, Timeline buttons, however, it is a bit bigger. Can you resize it the same as the built-in File Explorer size?

**OneDrive Integration**
Also, OneDrive integration would be useful. I am missing the Share, View offline, Always keep on this device, and Free up space in the context menus.

**Zoom**
The current view is a bit bigger for me. I hope there will be a feature to zoom in/zoom out the view.

**This PC**
We need an overview of all the drives just like how This PC in File Explorer does.

**Homepage**
When Sets was introduced by Microsoft, the new tab page in Microsoft Edge was useful. It shows the recent files, the drives and other contents. Hopefully you will consider this one.

Other than these, Files UWP is a very good app for a pre-release software. Looking forward to replace the built-in and outdated File Explorer with this one!

**Comment by duke7553** [comment]
Thank you for the feedback. However, it really helps us to have separate reports for each issue, so please search the existing issues for one that matches. If it doesn't exist yet, we'd be very happy if you could open up a new one for each of the items listed above. 

Closing this one in anticipation of separate, non-duplicate reports.
