### ISSUE TITLE
Files UWP

### ISSUE THREAD

**Issue by SeI7H** [duke7553/files-uwp#205]
![image](https://user-images.githubusercontent.com/43141352/62399797-f56e6f80-b574-11e9-8a7a-21ac3e2b6797.png)

**Comment by yaichenbaum** [comment]
Thank you for reporting, what were you trying to do when this happened?

**Comment by yaichenbaum** [comment]
@SeI7H What is the version number that you are using? You should be able to check it by going to settings > about.

**Comment by duke7553** [comment]
@SeI7H Please let us know what needs to be done to reproduce this bug. Did you interact with the PathBar before this occurred? 

Otherwise, I'll close this bug soon.
