### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by d2dyno006** [duke7553/files-uwp#208]
**Bug**
Error while starting application

**To Reproduce**
1. Download ZIP
2. Open Solution File
3. Set starting project to ProcessLauncher
4. Click Start

**Screenshots**
![Error2](https://user-images.githubusercontent.com/53011783/62423706-3d4fdc80-b6c4-11e9-9a5c-34c248e90448.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18362.267

**Comment by yaichenbaum** [comment]
Thanks for trying out Files UWP! The reason it wont load is that component is meant to open executable files, it gets the file name from the main component. To open correctly try using FilesUWP.Package. Please reopen this issue if this does not help.

**Comment by d2dyno006** [comment]
> Thanks for trying out Files UWP! The reason it wont load is that component is meant to open executable files, it gets the file name from the main component. To open correctly try using FilesUWP.Package. Please reopen this issue if this does not help.

Thanks! I had to deploy first and then build, it's working now!
