### ISSUE TITLE
Couldn't paste in any directory

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#21]
Hey, @duke7553! Sorry for another issue but when I try to copy a file it works by storing the location variable in the clipboard but when I paste it then I couldn't because there is no space to right click other than the files and directories icons. **I could still paste it somewhere else in the OG Explorer.** You're doing great but just as a fellow programmer it's a piece of advice.

**Comment by duke7553** [comment]
Does clicking paste in the "three dots" menu work?

**Comment by KartSriv** [comment]
@duke7553 Nope, It's not working. I still could copy the files but not paste it because the paste button is greyed out.
![image](https://user-images.githubusercontent.com/25691607/52894070-e3b52d80-31c9-11e9-8286-3fda810b25f6.png)

**Comment by KartSriv** [comment]
@duke7553 The new version has the fix. Thanks!
