### ISSUE TITLE
ctrl + v should focus on the pasted item or items

### ISSUE THREAD

**Issue by avknaidu** [duke7553/files-uwp#211]
**Describe the bug**
When using Copy + Paste to same folder, the file gets created. However the focus is still not on the new file instead on the original one. 

**To Reproduce**
1. Go to Specific File to copy
2. Click on Copy
3. Click on Paste
4. File is created but focus is still on original

**Expected behavior**
Focus should go to Newly created file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 1809
 - App version: [v0.5.0]

**Comment by yaichenbaum** [comment]
@avknaidu Is this something you would be interested in working on?

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by yaichenbaum** [comment]
This has been resolved with #574, it will be included when v0.7.6 rolls out.
