### ISSUE TITLE
Copying with Ctrl+C and Ctrl+V creates two copies of the file

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#212]
If you copy-paste a file in the same directory with the keyboard shortcuts Ctrl+c and Ctrl+v, instead of a single copy you get two copies of the original file. It doesn't happen with the ribbon buttons or the right-click commands, though

Version: 0.6.2
Windows: 1903

**Comment by yaichenbaum** [comment]
There are a few things we need to keep in mind
- Someone is pasting a file with the same name as one that already exists, in this case we should ask if they want to replace the file or keep both files, there should also be an option to cancel. Keeping both files should add a number to the end of the file name.
- Someone is pasting a folder with the same name as one that already exists, the options should be to replace existing files (it should still paste files that are not in the destination path yet). There should be an option to cancel and of course an option to keep both folders which will add a number to the end of the copied folder.

**Comment by duke7553** [comment]
A potential fix for this behavior is being tested for v0.7. Thanks for your patience.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
