### ISSUE TITLE
a better way to load Thumbnails

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#213]
When looking up files in a folder, the process of creating thumbnails takes too long.
I would suggest creating a unique hash for each file that won't change if the file was moved or renamed. Create the thumbnail of this file and save it in the app folder under the hash of the associated file.
When opening a folder:
1- look up all the files and load them into the UI under a generic icon based on the file type.
2- check if the file with the thumbnail hash name already exist - if it does load the thumbnail from app folder to replace generic icon, if not create new one, load it into the UI and save it for later use.

For convenience and fast operating you can save folder view data that takes too long to load like folder size

**Comment by duke7553** [comment]
Thanks for bringing this to our attention. I can't promise that I'll implement it this way, but I will investigate which aspects of thumbnail retrieval cause the slowdowns. In the meantime, do you have any data/measurements to back up your claim regarding slow file thumbnail retrieval? 

We are currently prefetching them to avoid the known performance penalty, but may be doing it incorrectly as the documentation is scarce.

**Comment by duke7553** [comment]
@moutasem1989 There are changes in master which should slightly improve thumbnail retrieval.

**Comment by yaichenbaum** [comment]
@duke7553 Is this something you are working on?

**Comment by yaichenbaum** [comment]
@duke7553 What is the status of this issue?

**Comment by duke7553** [comment]
This is something that will be addressed in the future.

**Comment by yaichenbaum** [comment]
Please check out the latest [release](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0) and make sure to let us know if you find this experience has been improved.
