### ISSUE TITLE
Implement layout modes

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#214]
When pressing CTRL + scroll layout view in the opened window should change accordingly so is wit the pinch in to zoom in and pinch out to zoom out

**Comment by yaichenbaum** [comment]
This will come when the different layout modes are available.

**Comment by yaichenbaum** [comment]
Layout modes will be be available when the v0.7.3 release rolls out.

**Comment by MarcAnt01** [comment]
Hi, was about to open a ticket about the possibility to adjust the dimensions of the contents of a folder with touchpad zoom. Is that linked to this issue?
