### ISSUE TITLE
Folder size in list view

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#215]
It is as it sounds

**Comment by duke7553** [comment]
This isn't possible with the way NTFS works, but we will have this available on an individual basis in Properties.

**Comment by szaimen** [comment]
Wouldn't it be possible to show the filesize when [caching](https://github.com/duke7553/files-uwp/issues/270) the files and also the file size of files and so when a file changes, the size get updated immedeately?

**Comment by yaira2** [comment]
@moutasem1989 this feature is now available under `Settings > Folders > Calculate folder sizes`. You can download the latest version of Files from our website https://files.community/download
