### ISSUE TITLE
Offer appx file on releases page

### ISSUE THREAD

**Issue by Gaming4LifeDE** [duke7553/files-uwp#216]
**Is your feature request related to a problem? Please describe.**
I want to install Files UWP on a system where the store is disabled by group policy but sideloading is enabled

**Describe the solution you'd like**
Just provide the .appx file on the releases page

**Describe alternatives you've considered**
i tried to grab the store bundle from [here](https://store.rg-adguard.net) but it doesn't provide the .appx file for Files UWP, just it's dependencies.

**Comment by yaichenbaum** [comment]
Starting with the next release we will start providing appx files again.
