### ISSUE TITLE
Open in new tab or new window

### ISSUE THREAD

**Issue by gh0sti** [duke7553/files-uwp#218]
There should be an option to open a folder in a new tab or new window.

Can files support multiple windows like file explorer?

**Comment by yaichenbaum** [comment]
Thank you for the feedback, in face Files UWP already supports opening multiple windows at a time. The option you are asking for is not yet ready. We will update this issue when it is.

**Comment by duke7553** [comment]
These changes will be in master shortly for v0.6.4
