### ISSUE TITLE
Split the files of the installer into x64, x86, ARM. Don't compress all the files into one zip file.

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#22]
Hey, @duke7553! I hope this is the last issue I am putting (_I am so sorry_). Just split the files of the installer into **x64, x86, ARM**. Don't compress all the files into one zip file because rather than having an installer with a size of **26.91 MB** (Repo Size), your installer file size is **156 MB**. Why do you pack the software for all architecture in one file? You can make **convenient software** for the users by having a lightweight program. _It is just a humble request to you! Thanks for bearing with all my issues._

**Comment by KartSriv** [comment]
You can tag it as an enhancement.

**Comment by GitMoDu** [comment]
I understand 150 MB is quite hefty, but this is still a beta release. Final packing on Store will only download the appropriate version.

**Comment by duke7553** [comment]
Since download sizes are a struggle for some people, I’ll split them up next release. Good thought!

**Comment by KartSriv** [comment]
Thanks, @duke7553! By the way great code!

**Comment by duke7553** [comment]
Done!
