### ISSUE TITLE
Bugs/missing features

### ISSUE THREAD

**Issue by mik3y64** [duke7553/files-uwp#222]
First of all, thank you so much for such a sleek and modern looking apps. I just discovered this and started using it. It's so beautiful!

**Some bugs or features missing**

1. Files UWP's fonts are slightly blurry compared to native file explorer. Image icons (on the left of each item) are significantly more blurry

2. The UI is a little lag 

3. Missing important file navigation/access features, compared to native Windows file explorer, these important navigation features are missing/not working

- Forward/Back to documents button can't be accessed via mouse-side button (alt + left/right arrow work fine, but not mouse side button). No response when mouse-side button is clicked.

- Single click to open at item (see image below). Configured via Menu bar > View > Options > Click item as follows > Single-click to open an item

![pic](https://user-images.githubusercontent.com/44294991/63071012-c1c21b00-bf60-11e9-9ce3-b6b4f47ef6b2.jpg)

**Desktop (please complete the following information):**
 - OS Version: Windows 10
 - App version: [v0.5.0]

**Comment by yaichenbaum** [comment]
Thank you for trying out the app and logging the feedback here. It will be a lot easier to sort through the feedback and fix them if you open a separate issue for each feedback.
Closing this in anticipation of your future feedback.
