### ISSUE TITLE
"Share" tab is redundant

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#224]
Right now the "Share" tab in the ribbon has only one button, "Share", which feels redundant. I'd suggest either to merge the Share button in another tab, or implement in that tab other buttons in the future. In the Win32 File Explorer the Share tab has also entries for Zip files and Print, so maybe you could look into them

**Comment by yaichenbaum** [comment]
We are working on an option for "zip" so we will definitely look in to adding this to the Share tab.

**Comment by yaichenbaum** [comment]
I am going to close this issue since it will be resolved once more options are added to the tab. We can't wait for you to continue sharing your feedback and ideas!
