### ISSUE TITLE
Option to choose if to show file extensions or not

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#225]
As the Win32 File Explorer does

**Comment by J-Cake** [comment]
this is required!!

**Comment by KaKi87** [comment]
Indeed, the ability to see file extention goes with the ability to change it.

**Comment by duke7553** [comment]
Thank you for reporting this issue.

**Comment by duke7553** [comment]
@SOI7 This is now fixed in the develop branch.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
