### ISSUE TITLE
ctrl+w to close tab

### ISSUE THREAD

**Issue by SaturnSoftware** [duke7553/files-uwp#226]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ctrl + w doesn't close the tab.

**Describe the solution you'd like**
ctrl +w to close the tab

**Describe alternatives you've considered**
ctlr+shift+w if there's some conflict, but there shouldn't be.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
Windows shell uses ctrl+w to close explorer windows.

**Comment by yaichenbaum** [comment]
Thank you for taking the time to give this feedback, we are tracking this issue over here and definitely will take care of this in a future update. https://github.com/duke7553/files-uwp/issues/9#issuecomment-464833796.
