### ISSUE TITLE
More Acrylic Concept

### ISSUE THREAD

**Issue by Henboy10** [duke7553/files-uwp#227]
Not a priority, but...
I found this design by designer [Michael West](https://dribbble.com/shots/6167926-File-Explorer-navigation-and-list-view?utm_source=Clipboard_Shot&utm_campaign=itsmichaelwest&utm_content=File%20Explorer%20navigation%20and%20list%20view&utm_medium=Social_Share). Maybe a design similar to this could be implemented into Files UWP? I love Fluent Design, and I love Acrylic. I need more! 😁 I was thinking the sidebar could use some more acrylic.
![image](https://user-images.githubusercontent.com/22181579/64308195-0f2d1900-cf5e-11e9-8813-03f8fee213ca.png)

**Comment by yaichenbaum** [comment]
Hey, thanks for bringing this up. In the past there was acrylic on the sidebar but was removed since it can distract users. We are going to add an option for it however to turn it back on. #193.
And by the way, a large part of the design was inspired by Michael's concept.

**Comment by Francisco820** [comment]
> Gracias por mencionar esto. En el pasado había acrílico en la barra lateral, pero se eliminó ya que puede distraer a los usuarios. Vamos a añadir una opción para que sin embargo, para volver a encenderlo. #193.
> Y por cierto, una gran parte del diseño se inspiró en el concepto de Michael.

Seria de gran utilidad un acceso rápido a la papelera de reciclaje

Quick access to the recycle bin would be very useful

**Comment by yaichenbaum** [comment]
@Francisco820 you can already pin the recycle bin to the side, just navigate to it, right click and press pin to side bar.

**Comment by duke7553** [comment]
@yaichenbaum Actually, navigating to the recycle bin may be impossible.

**Comment by tomyan112** [comment]
It would be nice that recycle bin is pinned to the side bar by default.
