### ISSUE TITLE
Display preview when hovering over an image

### ISSUE THREAD

**Issue by Francisco820** [duke7553/files-uwp#229]
Al pasar con el cursor por los archivos de (videos, imagenes, etc) aparezca una vista previa

Hovering over files (videos, images, etc.) displays a preview

![Anotación 2019-09-11 195943](https://user-images.githubusercontent.com/55201857/64741669-b6b2ca00-d4cf-11e9-8f44-bb4cdc138d87.png)

**Comment by duke7553** [comment]
Quick Look integration is planned for v0.7

**Comment by yaichenbaum** [comment]
QuickLook integration has been [released](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0). Make sure to check it out and let us know if there are any issues.
