### ISSUE TITLE
Crash when switching access to file system

### ISSUE THREAD

**Issue by rogama25** [duke7553/files-uwp#23]
When you go to Windows' settings, privacy, file system and you enable or disable the permission for Files to access file system, the program crashes. It also happens when you first run it and the program asks for permissions.

Windows 10 1809, Files UWP 0.4.6.0

**Comment by duke7553** [comment]
Hey. Unless someone can prove otherwise, this is intended behavior. Simply restart the app.

**Comment by yaira2** [comment]
@rogama25 the latest version of Files no longer requires granting access to the file system. You can download the latest version of Files from our website https://files.community/download
