### ISSUE TITLE
Translate for other languages

### ISSUE THREAD

**Issue by erickpaluan** [duke7553/files-uwp#230]
Hi!

Could you translate the app to other languages?
I can help translate to pt-br :)

**Comment by yaichenbaum** [comment]
Absolutely! We plan on doing this closer to the launch. At the moment we are constantly making changes and it would not make sense to translate yet since many strings are not set yet. We will update this issue when the app is ready for this.

**Comment by erickpaluan** [comment]
Nice! Let me know if you need any help. I'm UI/UX designer :D

**Comment by moutasem1989** [comment]
i could help with German / Arabic

**Comment by yaichenbaum** [comment]
@moutasem1989 Thank you so much for the offer, we will have more to share on this in the coming months.

**Comment by yaichenbaum** [comment]
I am going to continue tracking this issue on #37 moving forward.
