### ISSUE TITLE
Some designs I made for inspiration and ideas

### ISSUE THREAD

**Issue by OnishaX** [duke7553/files-uwp#231]
Hey!

You've done such an amazing job so far :D Keep it up!
Over time ive made some designs and thrown together some ideas and I wanted to code them myself but i cant program HAHA BUT then i foudn your app and thought that maybe you'd like some of the ideas i had.

1. Progress bars on drives in the sidebar to display free space.

2. Separate cloud drives, favourites, network drives and drives in the sidebar.

3. Categorised "New Item" context menu. EG: New > Microsoft Office > Word Document.

4. Copy, and move windows.

5. Compress options.

I really hope these can inspire some ideas and that you continue the great work you're doing on this awesome app 😄 ❤️ 😄 

![Desktop - List View](https://user-images.githubusercontent.com/31225806/64842762-420a9780-d657-11e9-89b8-3070b8359e1f.png)
![Moving](https://user-images.githubusercontent.com/31225806/64842763-42a32e00-d657-11e9-979d-28d1bcacdc92.png)
![Copying](https://user-images.githubusercontent.com/31225806/64842765-433bc480-d657-11e9-9137-3594769cc6ab.png)
![Menu - New – Office](https://user-images.githubusercontent.com/31225806/64842766-433bc480-d657-11e9-8e0f-07232b68d27c.png)
![Menu - New – Compressed Folder](https://user-images.githubusercontent.com/31225806/64842768-43d45b00-d657-11e9-82ab-e5b6fc37f27c.png)

**Comment by OnishaX** [comment]
I also made an icon if you want ❤️ 

![Icon](https://user-images.githubusercontent.com/31225806/64842998-fd333080-d657-11e9-9f99-ef5a7713953f.png)

**Comment by yaichenbaum** [comment]
@OnishaX you can take a look at the thread we created for a new icon here #136
