### ISSUE TITLE
Preview panel on the right like in explorer for pictures and audio and video

### ISSUE THREAD

**Issue by oddxends** [duke7553/files-uwp#234]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
Duplicate of #130 Please subscribe to that issue for updates.

**Comment by yaira2** [comment]
Support for previewing files is now available. You can download the latest version of Files from our website https://files.community/download
