### ISSUE TITLE
Add a way to replace this as the default file explorer

### ISSUE THREAD

**Issue by CrankySupertoon** [duke7553/files-uwp#236]
It can be doen with the registry but UWP apps i dont think have EXEs or do they. I know they are installed by a APPX but that i dont think outputs a EXE

**Comment by yaichenbaum** [comment]
Do you have a link how it can be done from the registry? Its not something possible at the moment since there is no exe but having a link for reference can help for the future.

**Comment by CrankySupertoon** [comment]
https://www.ghisler.ch/board/viewtopic.php?t=47997#

**Comment by yaichenbaum** [comment]
Thank you! I will be keeping this issue open and will update later on if this will be a possibility.

**Comment by J-Cake** [comment]
You could create a *proxy* executable file in like C++ and add that to the registry. Every time you then open the explorer, the exe file opens the app?

**Comment by yaichenbaum** [comment]
If you want you can try adding that, at the moment we have been working on nailing the basics and haven't gotten a chance to look at this yet. This would need to be completely optional and off by default.

**Comment by yaichenbaum** [comment]
@CrankySupertoon With the latest [release](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0) there is an executable file included. If you want you are welcome to try to modify the registry to launch Files UWP, however modifying the registry can be risky and we take no responsibility if something goes wrong.

**Comment by yaichenbaum** [comment]
@CrankySupertoon [Here](https://github.com/duke7553/files-uwp/wiki/Replacing-File-Explorer-with-Files-UWP) is a guide on how to replace File Explorer with Files UWP.

**Comment by 1333481** [comment]
> 
> 
> @CrankySupertoon [Here](https://github.com/duke7553/files-uwp/wiki/Replacing-File-Explorer-with-Files-UWP) is a guide on how to replace File Explorer with Files UWP.

Where did it go?

**Comment by yaichenbaum** [comment]
@1333481 It's been moved to [here](https://files-community.github.io/docs/#/articles/replace-file-explorer).
