### ISSUE TITLE
Various buttons not functioning

### ISSUE THREAD

**Issue by Spyromaniac31** [duke7553/files-uwp#243]
First, I love that you're taking the time to make a nice-looking File Explorer

When right-clicking on a column name, the Edit Columns and Size All Columns to Fit buttons do nothing. Also, when I go into Layout Mode and try to change to icons, nothing happens, even after restarting Files UWP.

 - OS Version: Windows 10 1903 18362.418
 - App version: v0.5.0

**Comment by duke7553** [comment]
Thanks for the great feedback. These features aren't implemented yet, so their buttons act as placeholders for now.

**Comment by duke7553** [comment]
This is a duplicate of https://github.com/duke7553/files-uwp/issues/8

**Comment by yaira2** [comment]
These options are now available. You can download the latest version of Files from our website https://files.community/download
