### ISSUE TITLE
Can't open .exe files

### ISSUE THREAD

**Issue by ariestai** [duke7553/files-uwp#244]
**Describe the bug**
As the title, I can't open any of .exe files in files UWP.

**To Reproduce**
1. Download any kind of .exe file on the internet.
2. Open files UWP
3. Double click on the .exe file.
4. Nothing happens.

**Expected behavior**
I expect to see the .exe file opens up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows v1903
 - App version: [v0.5.0]

**Comment by duke7553** [comment]
This should be fixed in the next release

**Comment by Lolihunter1337** [comment]
@duke7553 Tried the new version and still cannot open them

**Comment by yaichenbaum** [comment]
@Lolihunter1337 Did you give permission for Files UWP to access the file system from the privacy settings in Windows 10?

**Comment by Lolihunter1337** [comment]
@yaichenbaum yes i did

**Comment by yaichenbaum** [comment]
What does it say as the version number in the about page in settings?

**Comment by Lolihunter1337** [comment]
0.6.5.0

**Comment by yaichenbaum** [comment]
@duke7553 any idea why this is happening?

**Comment by ashikns** [comment]
I tried with v0.6.5 and exe files open fine for me. I did notice that applications requiring UAC elevation do not work, and there's no proper error message for this.

**Comment by yaichenbaum** [comment]
@ashikns Do you have any ideas of a work around that will allow these applications to work?

**Comment by ashikns** [comment]
Interactive elevation is not permitted in a uwp context, and iirc it's also not possible to run uwp app with admin privileges on launch. I did originally help write the exe launcher helper that files-uwp uses, I'll try and see if there's some way to acquire privileges from that helper.

**Comment by ashikns** [comment]
Okay so short answer - yes it's possible. In the exe launcher project, you have to set StartInfo.Verb = "runas" and UseShellExecute to true. I verified that this does indeed launch the exe.

To do it properly you have to check whether the exe requires uac elevation and then elevate only if needed. I can work on this but it might take me a while (even though it's a relatively simple affair), feel free to take it up in the meantime.

**Comment by duke7553** [comment]
This behavior should be corrected with commit https://github.com/duke7553/files-uwp/commit/f53a6e08d3a39154d631362ac38604a2643df0c9  to the v0.7-changes branch

**Comment by duke7553** [comment]
Please reopen if this is still an issue

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
