### ISSUE TITLE
I would love to make more use of this but there are a few issues:  First, this is targeting finger and pen, so the buttons icons and other items should be a big bigger or more spaced out. Second, the items listed should only require a single tap to enter. Finally there needs to be Thumbnails for the listed items... I would suggest consulting the OneDrive App.... They've got a lot of this stuff figured out already... In fact I would love to be able to just use that single app for all files, online and local

### ISSUE THREAD

**Issue by bnunya** [duke7553/files-uwp#248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
You left the content to default template here on GitHub. I see you wrote it as the title, would you mind fixing this up to make it more friendly to read?

**Comment by duke7553** [comment]
@bnunya Please make this more readable. Thanks.
