### ISSUE TITLE
Crash after connecting smartphone (0.4.6.0)

### ISSUE THREAD

**Issue by p0nkr4t** [duke7553/files-uwp#25]
Can't access connected smartphone's storage.
When I open it, it freezes for like 10 seconds and then crashes.

**Comment by duke7553** [comment]
Smartphones require extra attention. (MTP support) Thus, I'm disabling their visibility for now to prevent crashes.

**Comment by yaira2** [comment]
@p0nkr4t this issue appears to be fixed in the latest version of Files, but if you're still having trouble, please open a new bug report so we can investigate.
