### ISSUE TITLE
Add support for hidden files & folders

### ISSUE THREAD

**Issue by Krip4us** [duke7553/files-uwp#26]
I cannot view the hidden folders and files

**Comment by Krip4us** [comment]
> I cannot view the hidden folders and files

**Comment by ATecSolution** [comment]
Would be great to have it as an option...

**Comment by duke7553** [comment]
As nice as it would be, UWP API limitations do not allow for this.

**Comment by KaKi87** [comment]
Couldn't you bypass that limitation by executing a file listing command from shell for example ?

**Comment by yaichenbaum** [comment]
It is technically possible with a Win32 component, we will revisit this issue in a couple of months after some of the other basics are taken care of.

**Comment by szaimen** [comment]
@yaichenbaum I think this is someday needed so maybe also adding this to the backlog?

**Comment by yaichenbaum** [comment]
This is not on our roadmap right now, we will revisit after launching the app.

**Comment by duke7553** [comment]
I'm going to move this item to #177

**Comment by yaira2** [comment]
Support for viewing hidden items is now available, you can download the latest version of Files from our website https://files.community/download.
