### ISSUE TITLE
Add option to file explorer right click context menu 

### ISSUE THREAD

**Issue by ATecSolution** [duke7553/files-uwp#27]
Would be nice to be able to right click on a folder or file in file explorer and have an option to view it in files-uwp....

**Comment by z0oinks** [comment]
Why? What purpose would this serve?

**Comment by ATecSolution** [comment]
It would make jumping to a location inside of files uwp easier.

**Comment by ATecSolution** [comment]
Thinking about this further it would not be so simple to implement and is not such a priority so I am closing it for the time being.
