### ISSUE TITLE
Caching of files and folders

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#270]
**Is your feature request related to a problem? Please describe.**
It seems, that when entering any folder, Files UWP is reloading the files and folders, that are contained inside this folder every time. Also navigating back and forth results in reloading the contained files and folders every time.

**Describe the solution you'd like**
I would like them to get cached, so that it is much faster to enter folders. (and I hope the slow loading animation is also gone afterwards.)

**Describe alternatives you've considered**
Also if e.g. a file or folder is added via another program or file explorer, Files UWP should show the new files or folders inside the folder instantly without having to reload the whole folder.

**Additional context**
The file explorer is able to do that, so it feels much faster then the current Files UWP.

I don't know, if this behaviour is meant with #213 so I opened this feature request.

**Comment by yaichenbaum** [comment]
Please fill out the info in the comment of your proposal.

**Comment by szaimen** [comment]
> Please fill out the info in the comment of your proposal.

@yaichenbaum Sry, but I don't understand what you want me to do, because I have filled out the whole feature request template as you can see...

**Comment by yaichenbaum** [comment]
It must be I wrote my comment before your changes went though, thanks!

**Comment by duke7553** [comment]
Virtualization for items is something I would definitely want to implement. Unfortunately, there doesn't exist documentation on this feature for the Toolkit DataGrid, so I assume the control doesn't support it. @yaichenbaum Can you verify whether the DataGrid supports virtualization?

**Comment by duke7553** [comment]
My mentality is: "Sure, the Windows.Storage namespace is slow, but users never really need to retrieve the properties of all filesystem items at once" That's where random-access virtualization would come in, but the DataGrid, to my knowledge simply doesn't support it.

**Comment by yaichenbaum** [comment]
As far as I know it does not but I believe it was requested for the new Win UI DataGrid control.

**Comment by szaimen** [comment]
> As far as I know it does not but I believe it was requested for the new Win UI DataGrid control.

@yaichenbaum Do you have a link? I would like to read about that.
Or is [this](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2858) what you are refering to?

**Comment by yaichenbaum** [comment]
@szaimen I am talking about [this ](https://github.com/microsoft/microsoft-ui-xaml/issues/1500 )one.

**Comment by szaimen** [comment]
Would be really nice, if that would provide a way to show the size of folders.
Alternatively I imagine that if you right-click on one or more folders (after selecting a few folders and right-click then), then you could show an option in the right-click menu to calculate the current size (and show it directly in the list), so that you are able to sort all files and folders based on their size for the current directory afterwards. (until you change something inside the folders and then reset the calculated size)
Shall I open a new issue for this idea or does it fit here?

**Comment by duke7553** [comment]
@szaimen Probably add that suggestion to https://github.com/duke7553/files-uwp/issues/259

**Comment by duke7553** [comment]
@szaimen We did work to prevent reloading the extended properties of a storage item if it's not scrolled into view. Since performance has improved from these changes, I do not believe caching items is particularly useful.

**Comment by duke7553** [comment]
Please re-open this if you can find a technical rationale for for caching files and folders. For instance, what properties should be cached and how would it benefit performance?

Thanks for the great feedback. Please keep it coming!
