### ISSUE TITLE
Further customizability

### ISSUE THREAD

**Issue by J-Cake** [duke7553/files-uwp#272]
It's the little things like customisability that inspire me, so this app is brilliant, I only have a few issues: The app tends to be fairly slow, even if it isn't, it feels sluggish. Other than that, I'd like a way to remove the preset favourites and replace them with my own as well as being able to add FTP based network locations and a way to hide files prefixed with `.` or to add options to *soft-hide* the files, so they're not actually hidden, just aren't shown in the explorer. It's only small, but just enough to make me not fall in love. Albeit, The app is brilliant, works well, looks nice and is feature rich. I really like that.

**Comment by yaichenbaum** [comment]
By slow, do you mean that loading large directories takes some time?

**Comment by duke7553** [comment]
@J-Cake Thanks for this feedback. Can you please elaborate on what specifically you're noticing performs slowly?

**Comment by szaimen** [comment]
Maybe he notices [this](https://github.com/duke7553/files-uwp/issues/270) missing feature which is resulting in the app feeling sluggish?

**Comment by J-Cake** [comment]
@duke7553 while I am finding that, yes, opening directories takes significant time, if there's a loading screen indicating its loading, this is tolerable, however, what I was originally referring to was the feel of the UI, I can't quite tell, but it seems that some elements in the UI take notable amounts of time to complete their animations, this, added up will result in sluggish feel even though the application can repsond to IO at decent speeds.

**Comment by yaichenbaum** [comment]
@J-Cake Here is some good news, we are working on refining the UI and will take in to account how long elements take to load. In addition we have made some changes that will make launching the app a lot faster.
Overall things are pretty snappy in my experience when I build straight off of master. It would be helpful if you could share the exact places where you find the animations too slow or annoying so that we can look in to improving the experience.

**Comment by J-Cake** [comment]
@yaichenbaum I love the enthusiasm, I was actually working on trying to build it myself, once I have succeeded with that, I'll report the new feel of the app and a thorough speedtest etc.

**Comment by yaichenbaum** [comment]
If you are going to build the app yourself I will mention that you should build in release mode rather then debug, the reason for that is debug mode will take a lot longer to load the app then it will if you build it in release mode.

**Comment by J-Cake** [comment]
@yaichenbaum Noted. Thank you

**Comment by yaichenbaum** [comment]
@J-Cake I was just going over this issue again and noticed you want a way to add FTP locations, while we don't have any special support for that right now you should be able to pin any location to the side bar.
I hope this information helps.

**Comment by yaichenbaum** [comment]
@J-Cake I have some good news, @duke7553 has managed to improve the speed of loading large directories by over 75%, I do not have any release date but if you build from the `develop` branch you will be able to take advantage of the new changes.

**Comment by J-Cake** [comment]
@due7553 , thanks so much for responding, I'm yet to have a look, but I'll
let you know what the experience is like.

**Comment by yaichenbaum** [comment]
I believe the issues with files taking a long time to load has been addressed. In recent versions, it is also possible to pin custom locations to the sidebar. There is an open issue for supporting hidden files #25.
If you one into any problems make sure to open an issue or upvote an existing one.

**Comment by J-Cake** [comment]
I've just seen this change. Thanks so much for addressing this.

**Comment by yaichenbaum** [comment]
@J-Cake I am happy to hear these changes helped.

**Comment by J-Cake** [comment]
I went on a total customisation rampage. I've got custom everything. And now this explorer is capable of replacing the default one. Windows is decent once again... :P
