### ISSUE TITLE
Por que no actualizan la app?

### ISSUE THREAD

**Issue by Francisco820** [duke7553/files-uwp#273]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
Please fill out the details so we can understand what you want.

**Comment by szaimen** [comment]
@yaichenbaum I have translated the issue title and it seems like the issue creator is asking why the app doesn't get Updates?

**Comment by yaichenbaum** [comment]
In that case the answer is the app is still in very early alpha. We are constantly updating the code base and we are actually ready to ship a new update with many new features and bug fixes. The reason this update has not gone out yet is we haven't been able to compile an update package and we are still working on figuring this one out.
