### ISSUE TITLE
Selection options

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#274]
Please add these ribbon options for selection:

- [x] Select all
- [x] Select none
- [x] Invert selection

Would be really helpful especially for touch input.

This is how it is currently implemented in the file explorer:
![image](https://user-images.githubusercontent.com/42591237/68471809-47332f80-021f-11ea-8823-62fdb017f9a5.png)

**Comment by yaichenbaum** [comment]
Select all and clear all are already options. Since the idea is straightforward I will go ahead and approve this issue.
![image](https://user-images.githubusercontent.com/39923744/68482367-6b831200-0207-11ea-87ef-b88be6baa829.png)

**Comment by szaimen** [comment]
I just don't know, if these option are fitting well in the "Layout" category. But that is a discussion for another time.

**Comment by yaichenbaum** [comment]
Selection options are fully implemented with v0.7.6.
