### ISSUE TITLE
When clicking on specific folders in the path, the highlighting in the navigation bar on the left doesn't change

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#275]
**Describe the bug**
When clicking on specific folders in the path, the highlighting in the navigation bar on the left doesn't change.

**To Reproduce**
1. Go to Downloads -> "Downloads" is highlighted
2. Click on a folder inside downloads -> highlighting on the left changes to "Local Disc"
3. Click on "Downloads" in the path-bar -> highlighting doesn't change back to "Downloads" but remains on "Local Disc"

**Expected behavior**
highlighting should change to "Downloads" like it does when navigating back with the button or navigating to the parental directory with the button.

**Screenshots**
"Downloads" should be highlighted but "Local Disc" is highlighted:
![image](https://user-images.githubusercontent.com/42591237/68484634-f0891e00-023d-11ea-9349-be15dd6845c9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903
 - App version: [v0.5.0]

**Additional context**
Does this problem occur again after restarting the app? YES!
I haven't found any issue that addresses this so I opened a new one.

**Comment by szaimen** [comment]
BTW: I wonder if it wouldn't be better to remain the highlight on downloads when navigating into a folder inside the downloads folder? (Sounds somehow more intuitiv to me but isn't the current behavior of file explorer)

**Comment by yaichenbaum** [comment]
This is great feedback, thank you for bringing it to our attention.

**Comment by szaimen** [comment]
@yaichenbaum Do you have any thoughts on: https://github.com/duke7553/files-uwp/issues/275#issuecomment-551854144 ?

**Comment by yaichenbaum** [comment]
I agree with your comment.

**Comment by szaimen** [comment]
Okay, then the same behavior should probably get applied to all other items as well to be consistent.
Shall I open a new issue for that to track it seperately?

**Comment by yaichenbaum** [comment]
I think this issue covers everything so there is no need for another one.

**Comment by duke7553** [comment]
We've made changes for v0.7.3 that will make this behavior more consistent.

**Comment by yaichenbaum** [comment]
This should be fixed when the v0.7.3 release rolls out.
