### ISSUE TITLE
Improvements to file selection

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#276]
**Is your feature request related to a problem? Please describe.**
In file explorer you are currently able to select a specific amount of files in a custom order but not in Files UWP.

**Describe the solution you'd like**
When I have marked a few files and press after the last one ctrl+shift, I then be able to select a few files in a row additionally. Currently in Files UWP it is deselecting the former selected files when doing that, so I cannot choose more files in a row.

When selecting a few files it looks like this: (the last one selected is the lonely selected pdf file)
![image](https://user-images.githubusercontent.com/42591237/68485486-adc84580-023f-11ea-869e-2c2a2bc4a8a8.png)

When I know press ctrl+shift and click on the certificat file, this happens: (it resets the current selection and restarts the selection from the pdf file)
![image](https://user-images.githubusercontent.com/42591237/68485760-1ca59e80-0240-11ea-85ed-30e2c8d27413.png)

But it should look like this afterwards:
![image](https://user-images.githubusercontent.com/42591237/68485893-51195a80-0240-11ea-9665-73aa4450c5df.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, unfortunately, this is out of control and it's a behavior of the Windows Community Toolkit DateGrid control. The good news is WinUI is working on a brand new DataGrid control that will improve the behavior in many areas. I am linking to the issue [here](https://github.com/microsoft/microsoft-ui-xaml/issues/1500#issuecomment-582248175) so you can add your feedback about what you would like to see in this new control.

**Comment by szaimen** [comment]
@yaichenbaum would you suggest to like the comment that you have linked? So is the comment already covering this issue here? 
Or should I add a comment there?

**Comment by yaichenbaum** [comment]
@szaimen You should probably add a comment there.
