### ISSUE TITLE
Make the Window draggable at the whole top of the window bar

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#279]
**Is your feature request related to a problem? Please describe.**
Currently a files uwp window is not draggable at the very top of it, so I cannot reach to the top in fullscreen and drag the window to minimize it: I have to grab it a few pixels below which is annoying.

**Describe the solution you'd like**
Please make the Window draggable at the whole top of the window bar.

**Describe alternatives you've considered**
Maybe if just one tab is open in a window you could also drag a window by dragging the tab? (while probably also making it possible to drag this tab onto another open window?)

**Additional context**
At these orange areas is the window currently not draggable: (of course also below the action buttons on the right, but there it don't have to be draggable imo.)
![image](https://user-images.githubusercontent.com/42591237/68498880-3a7efd80-0258-11ea-8733-b804a779770c.png) 
Afterwards the window should be also draggable at those sections.

**Comment by szaimen** [comment]
Alternatively you could expand the tabs to be as big as in Microsoft Edge: (so that on the left and above the tabs is no space -> then they are also easier to grab...
![image](https://user-images.githubusercontent.com/42591237/68499636-f2f97100-0259-11ea-8c8d-17510ba5ab60.png)

**Comment by yaichenbaum** [comment]
@duke7553 Is already working on this one so I will just assign him to the task to keep track.

**Comment by szaimen** [comment]
I recently updated to 0.6.5 and the window is draggable now on the red marked section:
![image](https://user-images.githubusercontent.com/42591237/68853252-cfab4780-06d9-11ea-940d-c92a4469252b.png)
Now I think only this is missing: https://github.com/duke7553/files-uwp/issues/279#issuecomment-551929631

**Comment by yaichenbaum** [comment]
We are currently working on having the tabs stretch to the top when the app is maximized.

**Comment by szaimen** [comment]
> We are currently working on having the tabs stretch to the top when the app is maximized.

Why not stretching them always to the top?
Because when not, I think the window should then be draggable in this section (above the tab, just as I have colored it in orange.)

**Comment by yaichenbaum** [comment]
It definitely should be draggable when not maximizes, we will work on that as well.

**Comment by duke7553** [comment]
I think since we've fixed most of this bug by shifting the tabs up, there's no need to put any more time into it. Also, we designed the app to have a drag region always visible to the left of the caption buttons.

**Comment by szaimen** [comment]
I would like to test this out. How long will it take until 0.7.2 is available over the store?

**Comment by duke7553** [comment]
@szaimen The update is currently in certification, so this may take anywhere from 1-2 days.

**Comment by szaimen** [comment]
I've tested 0.7.2 and this behaiour hasn't changed since 0.6.5 version:

> I recently updated to 0.6.5 and the window is draggable now also on the red marked section:
> ![image](https://user-images.githubusercontent.com/42591237/68853252-cfab4780-06d9-11ea-940d-c92a4469252b.png)
> Now I think only this is missing: [#279 (comment)](https://github.com/duke7553/files-uwp/issues/279#issuecomment-551929631)

But if you think that are enough spaces to grab te window, then I am fine with it. 👍
