### ISSUE TITLE
Enhancing the design of Selections

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#284]
**Is your feature request related to a problem? Please describe.**
I don't know if it is a bug or feature but when selecting files, I can see the dividing line between items that are not visible in the list view at all.

**Describe the solution you'd like**
Maybe don't show the dividing lines or remove them completely?

**Describe alternatives you've considered**
Maybe just leave it as it is (when it is ment to be this way)

**Additional context**
Look at this screenshot:
![image](https://user-images.githubusercontent.com/42591237/68514260-7b3d3d80-027d-11ea-8ca1-be0c57d7c4e8.png)
Can you see the dividing lines in the selection? don't know if they shouldn't be visible.

**Comment by yaichenbaum** [comment]
This is how it is meant to be, in fact if you take a look at File Explorer it has the same behavior.

**Comment by szaimen** [comment]
Yes, I agree that it is the same behavior in file explorer.
But what is the reason for that?
Doesn't this look much better to your eyes as well?
![image](https://user-images.githubusercontent.com/42591237/68549011-c11c1200-03f3-11ea-96eb-c19d990b0752.png)

**Comment by yaichenbaum** [comment]
Actually, I can't reproduce that it shows the lines in Files UWP, I am not sure why you are seeing it like this.

**Comment by szaimen** [comment]
Maybe because I am using the old, current Microsoft Store release? 🤔

**Comment by yaichenbaum** [comment]
I am not sure, @duke7553?

**Comment by generalguy41** [comment]
I can confirm I see the lines on the Store version as well.

**Comment by szaimen** [comment]
This bug is fixed in 0.6.5
