### ISSUE TITLE
Tree view in the sidebar

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#289]
**We are looking at enhancing the sidebar experience**

We are debating is if a tree view is necessary for our user base, on the one hand it could make working deep in a directory easier since you can just click on an item in the tree view to go back. On the other hand you can use the path par to click on any of the directories there to navigate, additionally you could just click the button that goes up one directory and navigate that way.

There are advantages of having a tree view over the alternatives I mentioned above,
You can interact with the directory, for example right click and use any of the options there such as properties or opening in a new tab or window.

One reason not to use a tree view is the simplified layout of  the nav menu currently in the Files creates a much cleaner design.

Please keep this issue on topic, for any other request about the side bar please take a look at existing issues or create a new one if the issue has not been brought up yet.

**Comment by szaimen** [comment]
I don't if a Tree view in the sidebar is really needed. I think the current implementation is much cleaner.
So I think this should definitely be optional. (or just remaining collapsed if not actively used).

Also if  the two shortcuts pressing "Left" for "going up" and "Right" for "opening folder/file" is implemented for the list view (as I proposed [here](https://github.com/duke7553/files-uwp/issues/9#issuecomment-551957010)), you can easily navigate with the error keys in the list view as easy as in the proposed tree view for the sidebar.

**Comment by SOI7** [comment]
Maybe as an optional mode, like the iOS column mode referenced in #147 ?

**Comment by yaichenbaum** [comment]
@SOI7 That technically, is something we can do but we are trying to figure out what has the most value to **our** users. We want to hear the needs of you and if the current version satisfies them. If they don't then what can we do to meet them.

**Comment by generalguy41** [comment]
Personally I never really go deeper than one or two levels at most for the sidebar tree view, so I don't really mind not having it, but it's always nice to have the option.

**Comment by yaichenbaum** [comment]
The general opinion seems to be that a regular list with no tree view is enough. We will continue improving the sidebar in future updates based on your feedback. If there are any questions or comments please make sure to let me know.

**Comment by Xelit3** [comment]
Hi all,

Not sure if it will be enough to reopen this debate or not, but something really interesting of having a Tree view, is for quickly moving files from the opened folder to another one in the whole folder system structure without. This is something that I really use a lot.

Another one is to navigate quick in deeper folders without refreshing the entire view one by one. (as initially explained by @yaichenbaum )

I agree that the current view is more simple and enough for most of scenarios, but, for deep usage is something really useful.
In that line, perhaps I am aligned with @SOI7 having it as an optional configuration.

Thanks for reading it, and best regards :)
