### ISSUE TITLE
No visibility for minimize, maximize or the close button in light theme

### ISSUE THREAD

**Issue by sandarbhasthana** [duke7553/files-uwp#29]
Hi,
I just installed this great app but found out that there's no visibility for the title bar buttons (Min, Max, Close) in light theme unless hovered. 
But all the buttons are clearly visible in dark theme.
Thanks!

**Comment by PoorPocketsMcNewHold** [comment]
Surprisingly, That's the opposite for me. I've got no visibility on the Dark theme only instead as you may see. https://framapic.org/LHgiRvC0OH3T/Tl9SN3KX9imY.gif
But the white theme seems to have some issues however with his dark counterpart. https://framapic.org/orBEdkxlqud1/t6stQZbGcWB6.gif

**Comment by ATecSolution** [comment]
I cant make the changes to the repository right now but whoever wants add this code to files in the app load event to change the buttons forecolors to fix the visibility issue.

`//Make the minimize, maximize and close button visible in dark mode 
ApplicationViewTitleBar titleBar = ApplicationView.GetForCurrentView().TitleBar;
titleBar.ButtonForegroundColor = Colors.White;`

`//Make the minimize, maximize and close button visible in light mode 
ApplicationViewTitleBar titleBar = ApplicationView.GetForCurrentView().TitleBar;
titleBar.ButtonForegroundColor = Colors.Black;`

**Comment by duke7553** [comment]
Thanks everyone!
