### ISSUE TITLE
Setting multiple folders for downloads, documents, etc? And adding other pinned folders on the left side?

### ISSUE THREAD

**Issue by piereligio** [duke7553/files-uwp#292]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
You should already be able to pin folders to the sidebar, can you confirm you are running the latest version of Files UWP?

**Comment by piereligio** [comment]
I just downloaded it from the Microsoft Store, maybe so it's not the latest one? In that case, I'm sorry

**Comment by piereligio** [comment]
I noticed I'm on 0.5.0, which doesn't seem to be the latest. How do I subscribe to the preview in the microsoft store?

**Comment by szaimen** [comment]
How are you trying to add folders to the navigation bar? Through pulling or through right-klicking on the folder you want to add?

**Comment by yaichenbaum** [comment]
@piereligio There should be a newer version in the store, can you try updating and see if you have the option? If not then the feature should be rolling out with the next update.

**Comment by generalguy41** [comment]
Store version for me (Canada) is 0.5.0

**Comment by piereligio** [comment]
> @piereligio There should be a newer version in the store, can you try updating and see if you have the option? If not then the feature should be rolling out with the next update.

Ok this is strange. In the about page it's written 0.5.0, but the store says 0.6.4 (so I believe I've 0.6.4). How should I add the folders to sidebar?

**Comment by yaichenbaum** [comment]
There is a bug in that version that he settings page didn't show the correct version. If you navigate to the parent directory of the folder you want to pin then you should be able to right click on a folder and press pin to sidebar.

**Comment by piereligio** [comment]
Yes you're right, sorry

**Comment by yaichenbaum** [comment]
Is there anything else or can I close this issue?

**Comment by piereligio** [comment]
You can close it thank you
