### ISSUE TITLE
Add multiple languages

### ISSUE THREAD

**Issue by themoiFR** [duke7553/files-uwp#293]
**Is your feature request related to a problem? Please describe.**
I'm a french guy and I like when all the application I use is in french. I'd like to contribute if possible to add this.

**Describe the solution you'd like**
Adding a String folder to add string languages.
Adding a possibility to change the language in the settings.

**Describe alternatives you've considered**

**Additional context**

**Comment by yaichenbaum** [comment]
@themoiFR We are tracking this issue over at #230.
When you say you would like to add this, do you mean to set up to strings or just translating in to french? Either way make sure to let us know on #230.
