### ISSUE TITLE
Look at this UI Concept

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#294]
This [UI Design Concept for UWP File Explorer](https://www.behance.net/gallery/74300939/Windows-10-File-Explorer?tracking_source=search-all%7Cwindows%2010) is just breath taking !

[File Transfer UI Redesign](https://www.behance.net/gallery/83322777/Windows-10-File-Transfer-UI-Redesign-(Fluent-Design)?tracking_source=search-all%7Cwindows%2010) is also great !

**Comment by yaichenbaum** [comment]
We are going to be working on a file transfer dialog, however the one linked looks very unfinished and will require multiple changes to match the Fluent guidelines put out by Microsoft.

**Comment by duke7553** [comment]
We're looking to implement something like this: <img src="https://media.discordapp.net/attachments/599017746562547742/650036311616389151/unknown.png?width=1192&height=671">

**Comment by yaichenbaum** [comment]
@moutasem1989 We are planning on including the dialog shown above with the next update, are there any options you would like to see included with it?

**Comment by moutasem1989** [comment]
a way to see a tree view structure of the folders i am exploring. Gallery view option for music and pictures libraries would be helpful

**Comment by yaichenbaum** [comment]
Gallery view options should come when we add layout modes. I think an option to pause or cancel a file operation is important as well.

**Comment by R3voA3** [comment]
In that mock up, one can see the OneDrive ribbon in the footer of the navigation view. 
![image](https://user-images.githubusercontent.com/17484252/71642137-347d2a00-2ca7-11ea-8ae1-fde3264ae5c7.png) 
It would be nice if we could have the paper bin attached to the footer in a similar matter. It would show the current number of files and their total size and could be emptied by right-clicking on it.

This would remove the need to attach the paper bin to the start menu or leave it on the desktop. It's an important tool in the explorer and in my opinion should therefore be part of it, nice integrated.

Keep up the good work btw ;)

**Comment by yaichenbaum** [comment]
@R3voA3 I am pretty sure we cannot access recycle bin from a UWP app, we are exploring workarounds and will investigate for integrations when we get a workaround.

**Comment by R3voA3** [comment]
That's too bad, but simply opening the recycle bin should be possible, shouldn't it?

**Comment by yaichenbaum** [comment]
I am not sure if you can since it is not a regular directory, in any case we will try to find a work around.

**Comment by szaimen** [comment]
maybe [this](https://superuser.com/questions/395015/how-to-open-the-recycle-bin-from-the-windows-command-line/395140) helps?

**Comment by yaichenbaum** [comment]
I should of updated this issue, Duke found that same solution earlier today as well and is seeing if he can implement it.

**Comment by duke7553** [comment]
Please open a specific feedback item for each issue in the future, thanks!
