### ISSUE TITLE
When searching for Files UWP the old icon is shown

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#298]
**Describe the bug**
When searching for Files UWP the old icon is shown

**To Reproduce**
1. press the windows key
2. search for "files uwp"
3. See the screenshot

**Expected behavior**
The new icon should be shown like in the task bar and start menu

**Screenshots**
![image](https://user-images.githubusercontent.com/42591237/68853397-32044800-06da-11ea-93b9-34416cdd03a6.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903
 - App version: v0.6.5

**Additional context**
I deinstalled and reinstalled the app from the store but the same happens again.

**Comment by szaimen** [comment]
Also is the dark background in the program list and startmenu intended or shoulnd't it be also the default colour?
![image](https://user-images.githubusercontent.com/42591237/68864342-430c8380-06f1-11ea-87df-bd469f12fea8.png)

**Comment by yaichenbaum** [comment]
This is because the store can take a while to update all the assets, the dark background is intended so that the blue holder stands out.

**Comment by szaimen** [comment]
> This is because the store can take a while to update all the assets

So will I just have to wait or will I have to reinstall the app later on?

Otherwise, you can close this issue.

**Comment by yaichenbaum** [comment]
You will just have to wait, reinstalling the app wont help for that asset. Sorry about this inconvenience.
