### ISSUE TITLE
[Feedback] Some better color and layout usage

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#303]
First of all, I like the direction the app is taking in terms of functionality. UI wise it didn't change much, but I know it's not your top priority since you're focusing on making it work as flawlessly as possible. That said, I'd like to point out some areas that could benefit some touch-ups.

First of all, the left pane highlights. Right now Files highlights the selected pin/favorite with a dark/light (depending on the theme) rectangle. This design, however, has been deprecated in most MS apps, which now show a colored rectangle on the left side that follows the system accent color:

![Annotazione 2019-11-14 174756](https://user-images.githubusercontent.com/50930970/68879838-6859bb80-070a-11ea-9c56-5c34238ced86.png)

Secondly, the title bar. In the previous version the title bar used acrylic and retained the light/dark color of the theme. Now the title bar is a solid white/black color, but I guess that's because the tabs pane is using the new WinUI libraries. However, the new Edge browser based on Chromium is using them and it follows the system accent color:

![Annotazione 2019-11-14 175013](https://user-images.githubusercontent.com/50930970/68879963-a6ef7600-070a-11ea-8669-fcfb98786de1.png)

This is a serious issue to me, because the big amount of white in the app makes it harder on the eyes, I know there's dark mode but it's not enough sometimes, so I think the system accent color should be used more where possible. The amount of white affects the left pane as well. Back in the day it had acrylic, and we have long discussed about making it optional so I won't bring this topic back, however it could at least benefit of a different shade of grey in both modes. I know the Win32 File Explorer has the left pane white, but oddly enough in dark mode it is different:

![Annotazione 2019-11-14 175753](https://user-images.githubusercontent.com/50930970/68880223-24b38180-070b-11ea-89bb-1819c0d08a22.png)

I like also how the Win32 Explorer has pin icons on the right of the pinned folders, although I'd make them visible only for the folders you manually add and you can remove.

There's also another feedback about the icons and text alignment of the favorites buttons in the home screen, but that's more a nitpick than anything. I just find odd that in the Win32 Explorer and in the Settings app you have the icon and the title on the same line, but on Files UWP the title is below:

![Annotazione 2019-11-14 175304](https://user-images.githubusercontent.com/50930970/68880343-5f1d1e80-070b-11ea-8b3a-ae3cd5f57c8e.png)

And, lastly, the black background of the tile in the start menu feels... eh. I think it should follow the system accent theme or have a different tint:

![Annotazione 2019-11-14 181022](https://user-images.githubusercontent.com/50930970/68880405-7cea8380-070b-11ea-91fb-d08b3040fab2.png)

So, collecting this feedback, I made a mockup of how the app could look with these changes:

![mockup](https://user-images.githubusercontent.com/50930970/68880452-955a9e00-070b-11ea-8bfb-b3889b2a96d2.png)

The changes aren't that big and the app still retains the core aspects, but it's also easier on the eyes and more inline with the most recent Fluent Design lines.

Hope I didn't write too much, this is just a share of suggestions and you're not forced to include them 🙂

**Comment by duke7553** [comment]
Thanks for this feedback!

**Comment by duke7553** [comment]
This will be addressed soon, so I'll close this now. If you noticed anything not mentioned here, please open a feedback item for it. Thanks!
