### ISSUE TITLE
Pretty simple: Icon is in a black box.

### ISSUE THREAD

**Issue by lukasi2000** [duke7553/files-uwp#305]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
That is to help the blue colors stand out, I agree it looks a little off. Do you have any suggestions how we can improve it?

**Comment by generalguy41** [comment]
@yaichenbaum Honestly, I wouldn't worry about the blue standing out. I think it should just match the system colour. Alternatively, I think some apps allow you to customize the live tile through settings (though I can't remember which right now). Could be something to consider.

**Comment by duke7553** [comment]
@lukasi2000 Would it look better if we used a lighter grey?

**Comment by SOI7** [comment]
Why not having the tile background as the system accent color, but giving to the icon an outer shadow?

**Comment by yaichenbaum** [comment]
This has been addressed with #319, the icon will now use the system accent color as the background.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
