### ISSUE TITLE
Shortcuts that not always work

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#307]
**Describe the bug**
Some shortcuts don't alwas work.
I don't want to spam https://github.com/duke7553/files-uwp/issues/9, so I opened this new issue.

**To Reproduce**

-  ctrl+[shift]+tab to switch tabs
-  CTRL + TAB to cycle between tabs

sometimes work but just after I create a new tab or after I select a one-click option from the Homescreen (one of the Favorites or recent Items.) If I click on one item in the navigation bar on the left or click on an item or the list-filed or just on an empty space in the list in e.g. downloads (after opening it from the Homscreen, the shortcut don't work any longer until I reselect one of the tabs or open a new tab.)

A kind of similar behavior is happening with:
- ALT + LEFT , ALT + RIGHT for history navigation

It works most of the time but not if I create a new tab or click on a tab in the tab row or if I open or select a folder. (That doesn't apply to accessing folders/files from from the homescreen, just after pressing after entering e.g. downloads and clicking on a file/folder. To make it work again, I have to click on an item in the navigation sidebar or deselect my current selection through clicking elsewhere on an empty space in the list.

**Expected behavior**
each shortcut should always work despite of what I am currently doing or have done and despite of where I have clicked or where I am clicking on.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903
 - App version: [v0.6.5]

**Comment by yaichenbaum** [comment]
This is fixed and should roll out with v0.7.1.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
