### ISSUE TITLE
New Item Wizard Doesn't Refresh After Creation of Item

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#31]
Hey, @duke7553! Whenever I try to create a new File or Folder via the wizard(Which it tough, btw) I couldn't click any of the buttons. it's not only the underdevelopment buttons but all the buttons. 
![image](https://user-images.githubusercontent.com/25691607/52894133-cd5ba180-31ca-11e9-8a43-c6fd326272bf.png)

**Comment by duke7553** [comment]
Hey, the latest release fixed this today

**Comment by duke7553** [comment]
Try it out and come back!

**Comment by KartSriv** [comment]
@duke7553 Oh, snaps! I'll just install that one in a jiffy.

**Comment by KartSriv** [comment]
@duke7553 Whenever I create a file, It's not showing up but when I refresh it works. I'll close the issue but it's still not an elegant fix. Anyways, thanks!

**Comment by duke7553** [comment]
Reopening so I can investigate this auto-refresh bug.

**Comment by KartSriv** [comment]
Thanks, @duke7553!

**Comment by duke7553** [comment]
New changes are now in master, and will be released soon.
