### ISSUE TITLE
The underline animation when switching from File, Home, Share and Layout seems to have lost some animations compared to before while when you go in Settings the underline under Personalization, Preferences and About still is fine.

### ISSUE THREAD

**Issue by astalavista5000** [duke7553/files-uwp#314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by duke7553** [comment]
Hello. this is a limitation with the current control for the Ribbon which we are using. I'm closing this since it's 90% likely that future enhancements to the Ribbon will address this.
