### ISSUE TITLE
Make network locations available in the sidebar

### ISSUE THREAD

**Issue by jamescadd** [duke7553/files-uwp#317]
It would be nice if there was a way to view network mounted drives in the sidebar.  Perhaps that could be visible under "This PC" as others have suggested, or it would be great if they were just listed below the custom locations.  This could also be addressed by allowing custom locations to be more flexible, for example I don't use "my videos" so I could rename that and use it to point to a network share.

**Comment by duke7553** [comment]
Hello James,

I'm certainly looking to implement this functionality very soon, and displaying network-mounted drives shouldn't be that difficult considering the recent improvements to the Drives list.

Thanks for the feedback.

**Comment by FinlayDaG33k** [comment]
Hii there,

I don't want to sound rude but is there any ETA on this?  
I want to give it a good spin but since most of the things I do are done on network drives, I can't currently do so :(

**Comment by yaichenbaum** [comment]
@FinlayDaG33k Thank you for letting us know this is important for you. We currently have 80 open issues and are working as fast as we can to address them. We don't have any timeline on this feature, but we will update this issue when it's available.

**Comment by duke7553** [comment]
@jamescadd @FinlayDaG33k We recently changed the way we access storage items for better performance, and (in my testing) locations mapped through Windows explorer should work on v0.7.3 and appear in the sidebar. 

We're looking to improve this experience, so testing v0.7.3 once it makes it to the Store will really help us.

Thanks!

**Comment by FinlayDaG33k** [comment]
Great to hear that this hasn't gone unnoticed :)  
I'll be waiting for 0.7.3 and see if it will show me what I need.  

Anyhow, thanks for making this project, I don't like the default explorer (it's slow and keeps becoming unresponsive yay)

**Comment by duke7553** [comment]
@FinlayDaG33k The Store version should now be updated if you wanted to give us feedback 😀

**Comment by FinlayDaG33k** [comment]
My machine has downloaded the new update (`0.7.5.0`) but unfortunately, it doesn't show my network drives yet.  

Here is a side-by-side screenshot of my drives:
![image](https://user-images.githubusercontent.com/13424273/78789645-b6b77180-79ad-11ea-9167-38afefcb08fa.png)

**Comment by yaichenbaum** [comment]
@FinlayDaG33k Make sure to give Files UWP access to the file system on Windows 10. To do this you can go to the settings app on Windows > Privacy > File system. Click the toggle for Files UWP to give it permission to access your files.

**Comment by FinlayDaG33k** [comment]
That seemed to work yes :)  
I'll be giving the app a spin and open new issues as they arrise.

**Comment by yaichenbaum** [comment]
@jamescadd Can you confirm if this is fixed for you as well?

**Comment by jamescadd** [comment]
@yair100 I'm not seeing the list of apps to allow FS access in Settings at the moment, likely because I'm on an internal build.  May be an internal issue so as long as you see this working in production it should be good.  Thanks for doing this!

**Comment by duke7553** [comment]
@jamescadd Hi James. The issue you've descibed isn't specific to MSFT-Internal builds because they made the decision starting with v2004 to hide fullTrust apps from the filesystem permission list. The permission should be granted automatically to Files now on these versions.
