### ISSUE TITLE
Couldn't rename any files.

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#32]
Hey, @duke7553! I couldn't rename any files. nuff said.

**Comment by duke7553** [comment]
Does this still apply?

**Comment by KartSriv** [comment]
@duke7553 Yes. it does. Checked in the current update.

**Comment by ATecSolution** [comment]
I can rename files just fine.

**Comment by duke7553** [comment]
@ATecSolution If you're using master, there have been some recent changes since the last update.

**Comment by ATecSolution** [comment]
Ok, good.

**Comment by duke7553** [comment]
@KartSriv 0.4.8 is out now containing many fixes. Please give it a try, and reopen if you find it still not working.

**Comment by KartSriv** [comment]
Thanks, @duke7553!
