### ISSUE TITLE
Can't open document directly when enter the file path in the address bar

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#324]
If I input D:/123.pdf in the address bar
In classic file explorer 
It will open the pdf
In files uwp
![image](https://user-images.githubusercontent.com/9064351/69952768-d8ea4000-1532-11ea-911c-85fa96908f88.png)

**Comment by yaichenbaum** [comment]
A fix should roll out with v0.7.2, we will make sure to let you know when that happens.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
