### ISSUE TITLE
Expand and Collapse Folders on side bar

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#327]
![image](https://user-images.githubusercontent.com/9064351/70119224-c2fc8c80-16a4-11ea-9847-4c87ba87dc0a.png)

**Comment by yaichenbaum** [comment]
This would only make sense with a tree view, we are discussing this over here #289.

**Comment by yaichenbaum** [comment]
At the moment we are going to be sticking with the current Navigation Pane. However when we implement classic mode then it include this behavior.

**Comment by yaichenbaum** [comment]
@tomyan112 Instead off adding a full tree view, we are planning on separating the items in the side into three sections that can be expanded or collapsed. The three sections would something like,
- Pinned
- Libraries
- Drives.

For more information and to add your input, make sure to check out #692.
