### ISSUE TITLE
Show free space in drives

### ISSUE THREAD

**Issue by lionnesquaer** [duke7553/files-uwp#329]
Hello!
Please make a bar of free space usage of drives in menu. Like this:
![Desktop Screenshot 2019 12 05 - 08 25 24 65](https://user-images.githubusercontent.com/39178626/70207412-c4c55f00-173b-11ea-85f5-ffcdeb6b0a8a.png)

**Comment by yaichenbaum** [comment]
If we add a page to see all your drives as shown in #210 would that solve this issue?

**Comment by lionnesquaer** [comment]
Im look on your concept of this drive page, yes, it would be good. Please make it!

**Comment by yaichenbaum** [comment]
I will close this issue and we will continue tracking the issue in #210. It is something we got a lot of requests for and is part of the plans for the future.
