### ISSUE TITLE
Comments on xaml code

### ISSUE THREAD

**Issue by d2dyno006** [duke7553/files-uwp#334]
The UI code is quite complex I have to say, and it would have been nicer if the code had comments on the elements describing their purpose. Comments really help finding your way in the code!

**Comment by yaichenbaum** [comment]
Absolutely and this is something we are working on little by little to improve the code base. We are starting by modularizing the application and are taking a few days at a time to focus on different areas. If you have any questions about a specific part let us know and we will do our best to explain it.

**Comment by d2dyno006** [comment]
That's great! Nice to hear it!

**Comment by yaichenbaum** [comment]
Make sure to let us know if you have any questions while we work on improving it.
