### ISSUE TITLE
Addons for files uwp

### ISSUE THREAD

**Issue by SpardDEV** [duke7553/files-uwp#335]
Hi! I always like to see a program like this, that boring and ugly windows Explorer is stoneaged.

I love the tab system, but tô bem perfect, How about put two or more in the same page? Like a Button tô grid the tabs, or pull a tab in another tô join. Sometimes se want tô work in two pastes.

The context menu can vê tweak by the user, like to add function like 7zip and more. Maybe stealing forms or comands that already exists on the Explorer? It is possible? And for that we Mark down what we want tô not pollut this awesome app.

The left bar can be hide, like a Right bar can be show, and a plus tô write secret notes about a file. Put a link tô somewhere, visualizer a file. Hide when not is click. 

Maybe the user can choose more colora? I really hate blue ahahahaha 

For now i think is that. I only have to say one thing. You have a master piece in your hands, don't giveup! I am your fan! Continue with this project! Is awesome!

**Comment by yaichenbaum** [comment]
Quick Look integration was added and will roll out with the next update, to follow our plans for more integrations please see #343.
