### ISSUE TITLE
Rearange right click context menu

### ISSUE THREAD

**Issue by MadafakinRio** [duke7553/files-uwp#336]
I just can't get used to the order of the context menu when right clicking ceran items.

In Windows Explorer, delete and rename are below copy and paste, but in FilesUWP it's the other way around and it just seems so weird. 
Have you thought about changing the order?

![image](https://user-images.githubusercontent.com/26349936/70484488-44f91500-1aec-11ea-97e3-11b34345b6e8.png)

![image](https://user-images.githubusercontent.com/26349936/70484504-52160400-1aec-11ea-9d05-0de713e674b2.png)

**Comment by yaichenbaum** [comment]
I think we should be able to address this with the next release.

**Comment by yaichenbaum** [comment]
This has been addressed with #319 and will be released with the v0.7 update.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
