### ISSUE TITLE
Getting Files And Folders

### ISSUE THREAD

**Issue by d2dyno006** [duke7553/files-uwp#337]
How does the application gets the files and folders? 
Where is the specific piece of code located?

**Comment by yaichenbaum** [comment]
@duke7553 Can you answer this question?

**Comment by duke7553** [comment]
@d2dyno006 Thanks for your interest. We're currently using the Windows.Storage APIs which you can view our implementation in the ItemViewModel class.

**Comment by d2dyno006** [comment]
Thank You for answering! I just couldn't get around this! :smiley:
