### ISSUE TITLE
Please allow user to change OneDrive address because I have change my OneDrive address

### ISSUE THREAD

**Issue by Alex-coder251** [duke7553/files-uwp#339]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
This is done with v0.7.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
