### ISSUE TITLE
OneDrive not found with custom location

### ISSUE THREAD

**Issue by MGMehdi** [duke7553/files-uwp#345]
My OneDrive folder is on my D: drive and Files not found it

**To Reproduce**
1. Set a different location for OneDrive
2. Open Files 
3. Go tab OneDrive

**Expected behavior**
Open OneDrive folder

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909]
 - App version: [v0.6.6.0]

**Comment by yaichenbaum** [comment]
This should be fixed with v0.7. In addition there is now a setting to set a custom location for OneDrive from Files UWP as well.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
