### ISSUE TITLE
"Applications" can't be launched.

### ISSUE THREAD

**Issue by lampenlampen** [duke7553/files-uwp#347]
**Describe the bug**
"Applications" can't be launched.

### Reason:
I'm a german user. 
"Applications" have the filetype "Anwendung". The german word for Application.
So the check if a clicked item is an application fails:
https://github.com/duke7553/files-uwp/blob/7fe319b0673a1dc6b8a0902a084fc0bb0448a2e5/Files%20UWP/Interacts/Interaction.cs#L450

**Screenshots**
![Files_Bug_LaunchingApplications](https://user-images.githubusercontent.com/26199386/71044593-5b2d5380-2132-11ea-9707-c15f5f049c1a.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.535]
 - App version: [v0.6.6.0]

**Comment by KaKi87** [comment]
There would definitely be a lower-level solution to detect executables more efficiently.

**Comment by jeffsieu** [comment]
Right now the fileType is taken from [StorageFile.DisplayType](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.displaytype#Windows_Storage_StorageFile_DisplayType). Might be better to use [StorageFile.ContentType](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.contenttype#Windows_Storage_StorageFile_ContentType).

**Comment by yaichenbaum** [comment]
@jeffsieu I saw this on stackoverflow https://stackoverflow.com/questions/3693891/how-to-determine-if-a-file-is-executable, not sure if it would be useful for us.

**Comment by yaichenbaum** [comment]
A fix for this will be included in v0.7.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
