### ISSUE TITLE
QuickLock Integration

### ISSUE THREAD

**Issue by lampenlampen** [duke7553/files-uwp#348]
# QuickLock integration

https://github.com/QL-Win/QuickLook

I have a early working [prototype](https://github.com/lampenlampen/files-uwp/tree/feat/QuickLockIntegration).

At the moment i can toggle QuickLock by launching an application. So it's basically possible.

## Things to Do

1. Communication between App and Launcher. At the moment i misuse the "Launching Application" signal for toggeling QuickLock. I would appreciate some input on how the communication should be designed.
2. Settings UI, where you can enable the Integration.
3. How QuickLock should be launched (key stroke, context menu, etc.). Most comon way is by pressing spacebar. Is there anything against using spacebar?

**Comment by yaichenbaum** [comment]
By using the space bar it would be by holding it down for a few seconds?

**Comment by szaimen** [comment]
@yair100 IMO, pressing the spacebar once (not holding it down) should open QuickLook. So that it is like on macos. 

(Pressing the spacebar once again while QuickLook is open should close it and refocus the latest FilesUWP Tab. But that is probably an issue that QuickLook has to solve...)

**Comment by yaichenbaum** [comment]
I imagine this will only be if QuickLook is installed so I guess it wont affect regular users.

**Comment by FelixZacher** [comment]
QuickLock provides a NamedPipe, where you can send the toggle-Command.

At first toogle-Command the preview window is shown, at the second-command the preview window is closed again or shows a new file preview, if a new path is send.

@yair100 I would include a settings option, where you have to turn the feature on, if you want to use it and if you have QuickLock installed.

**Comment by yaichenbaum** [comment]
I wouldn't bother with the setting for it, if the user has it installed then it should work without any extra setup from the user.

**Comment by yaichenbaum** [comment]
Thank you @lampenlampen for the amazing job you did with this!

**Comment by lampenlampen** [comment]
# Icon

QuickLook has an [icon](https://github.com/QL-Win/QuickLook/blob/master/QuickLook/Resources/app_black.png) we can use.

I'm no expert in license stuff. For me it seems that QuickLook is under the GPL 3, which gives us the permission to use it.

**Comment by yaichenbaum** [comment]
I am fairly sure we can use it as long as we credit the source, the about page in the app would probably be the best place to reference it.

**Comment by yaichenbaum** [comment]
Just pointing out that the way Files is setup right now is that new features in the right click context menu need to be added to the photo view as well as the standard list view. In the future this will be changed in to one control but until then it needs to be implemented twice.
