### ISSUE TITLE
Detect executable files

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#351]
`.exe` isn't the only executable format out there, and there's no fixed list, but the information is available in the file's metadata, so Files should be able to detect it.

**Comment by yaichenbaum** [comment]
Can you give an example of another format that I can use to test?

**Comment by KaKi87** [comment]
Well, like I said, there is no fixed list, because the file extension isn't relevant to indicate if a file is executable or not. For example, a file without extension could be executable.
But, for example : `bat`, `cmd`, `com`, `vbs`

**Comment by yaichenbaum** [comment]
As a temporary fix I can add in manually for the common ones you listed. Ideally we would want to check correctly and that should should fix #347 as well. It may be necessary to use a Win32 component but we will do whatever it takes.

**Comment by yaichenbaum** [comment]
I took a closer look and we need to actually modify the launcher since it runs command line hidden so my temporary change would not display the terminal if you open a batch file.
I am hoping to have this addressed with v0.8.

**Comment by KaKi87** [comment]
> As a temporary fix I can add in manually for the common ones you listed

Please don't.

I prefer this feature to be available later but properly implemented than sooner but messy.

Thanks

**Comment by yaichenbaum** [comment]
Absolutely, we will wait to get it right 😊. Thank you for your patience.

**Comment by takase1121** [comment]
I think the app should look for the magic sequence of the executables(for those who had it like PE) instead of relying of the file extension

**Comment by lampenlampen** [comment]
I think this problem and this (#347) can be solved (partially), if we generally call `Process.Start()` for every file and let the OS handle the execution. This would only work for files with file extensions.

**Comment by yaichenbaum** [comment]
@duke7553 Came up with a solution, it should be included with v0.7.

**Comment by yaichenbaum** [comment]
@lampenlampen I think it is only expected to support files with extensions. In any case in the future we will have an even better way to detect executable files that should work even without extensions.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
