### ISSUE TITLE
Natural Sorting

### ISSUE THREAD

**Issue by fxha** [duke7553/files-uwp#352]
**Is your feature request related to a problem? Please describe.**

File names should be compared by the Win32Api `StrCmpLogicalW ` function to get the default Windows behavior. It's somehow strange to get the name `abc10` listed between `abc1` and `abc2`.

File names should be shown as:

```
2string
3string
20string
st2ring
st3ring
st20ring
string2
string3
string20
```

but not as (currency)

```
20string
2string
3string
st20ring
st2ring
st3ring
string2
string20
string3
```

**Describe the solution you'd like**

File names should be listed like in the first example.

**Comment by yaichenbaum** [comment]
@jeffsieu tagging you since you worked on this feature.

**Comment by yaichenbaum** [comment]
@jeffsieu any ideas about why this is happening?

**Comment by jeffsieu** [comment]
Oh hey, it's because the orderBy function uses a standard compare function.

A solution will be to define an IComparer as an argument in
 `OrderBy<TSource,TKey>(IEnumerable<TSource>, Func<TSource,TKey>, IComparer<TKey>)`, whenever the list is being ordered by name.

Like in https://github.com/duke7553/files-uwp/blob/0e93b99db46c2aeb0e7839229f74c67b94b2caad/Files/Filesystem/ItemViewModel.cs#L457

**Comment by duke7553** [comment]
@jeffsieu The Win32 function specified above cannot be used in a UWP app through PInvoke, so we'll have to wait on this until someone can find a good natural sorting helper class.

**Comment by jeffsieu** [comment]
@duke7553 I did manage to get it to work though, using the following helper class:
```cs
internal static class SafeNativeMethods
{
	[DllImport("shlwapi.dll", CharSet = CharSet.Unicode)]
	public static extern int StrCmpLogicalW(string psz1, string psz2);
}

public class NaturalStringComparer : IComparer<object>
{
	public int Compare(object a, object b)
	{
		return SafeNativeMethods.StrCmpLogicalW(a.ToString(), b.ToString());
	}
}
```

then using `NaturalStringComparer` in the relevant function calls.

![image](https://user-images.githubusercontent.com/8487294/79045498-0b711b80-7c3e-11ea-9fc3-004eacf9185f.png)
