### ISSUE TITLE
Cannot Build nor Deploy solution

### ISSUE THREAD

**Issue by d2dyno006** [duke7553/files-uwp#354]
Bug occurs while building the application. 
The bug is located in ...\Files.Uwp.Package\Package.appxmanifest
(As image shows:)
![bug](https://user-images.githubusercontent.com/53011783/71327836-eb421300-250d-11ea-8506-37a565c08cc8.png)

**To Reproduce**
1. Download latest version of Files UWP from GitHub
2. (If needed) Set the Build -> Advanced... -> Language version to C# 7.1 on UWP project
3. Build Solution

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18362.535
 - App version: [v0.6.6.0]

**Comment by lampenlampen** [comment]
Had the same problem with the master branch. A temporary solution for me was to exclude the "assets" folder from the "Files.Package" project.
