### ISSUE TITLE
Bug when opening Files UWP

### ISSUE THREAD

**Issue by d2dyno006** [duke7553/files-uwp#356]
JK. No Bugs! I just wanted to wish you all, community, contributors, devs Merry Christmas! 🎄 🎁 ☃️ 🎊 😄  (I'll remove it later)

**Comment by yaichenbaum** [comment]
You can expect many new features as we refine the app in the coming year!!

**Comment by d2dyno006** [comment]
Really, can't wait!

**Comment by duke7553** [comment]
@d2dyno006 Thank you! Happy holidays
