### ISSUE TITLE
Cannot open a Folder containing a File with a name that is too long !

### ISSUE THREAD

**Issue by moutasem1989** [duke7553/files-uwp#357]
i tried to download a file using Edge Chromium but the download process was interrupted and Files UWP couldn't open the Downloads Folder anymore. It keeps crashing

EDIT: So i looked into the problem and i found that the name of the file is causing the error.
the name is:

> The Good Place Season 1 Episode 1.comdocssecurescha0ro937gcuc7l7deffksulhg5h7mbp1adq0s6g481s9c3b9bg47ji333nb86mak1576951200000123433425475413313031jsdzrnoycpa7wpbhezebzg7nkuj5jiz9

**Comment by yaichenbaum** [comment]
Would you be able to share the file so I can do some testing?

**Comment by moutasem1989** [comment]
The file in question is in this archive ... 
[The Good Place Season 1 Episode 1.zip](https://github.com/duke7553/files-uwp/files/4001997/The.Good.Place.Season.1.Episode.1.zip)

**Comment by tomyan112** [comment]
It may be due to the 260 character length limit.
https://mspoweruser.com/ntfs-260-character-windows-10/

**Comment by yaichenbaum** [comment]
Interesting, we will need to look in to this and if there is a way around it.

**Comment by duke7553** [comment]
@moutasem1989 Just tested this in the next version of Files (v0.7.2) due to enter the Store, and it looks like we fixed this. Please reopen if you can still reproduce this after v0.7.2 enters the Store.
