### ISSUE TITLE
Allow the use of mouse 4 and 5 for foward and back

### ISSUE THREAD

**Issue by dkgameplayer** [duke7553/files-uwp#36]
Hey, I just came from reddit and this app is super cool! As feedback, I normally use mouse 4 as a back button and I think that would be a good feature to add. Thanks.

**Comment by duke7553** [comment]
Thanks for your help in reporting this. I'm tracking this feature request in another issue, so I'll close this one.

**Comment by yaira2** [comment]
@dkgameplayer this feature is now available. You can download the latest version of Files from our website https://files.community/download
