### ISSUE TITLE
Certain file types have type names like "pngfile" when more obscure file formats don't

### ISSUE THREAD

**Issue by Spyromaniac31** [duke7553/files-uwp#360]
**Describe the bug**
Under the Type column, PNGs, JPGs, and TXTs have the names pngfile, jpegfile, and txtfile, whereas more obscure formats like .ev3 have descriptive names like "LEGO Mindstorms EV3 Project". 
Edit: The one place this doesn't occur is my Downloads folder. There, file types are listed as PNG File or JPG File. It is located on the same drive as my Desktop and Documents, which do have the issue.

**To Reproduce**
Simply open any folder that contains PNGs, JPGs, or TXTs in the Details layout.

**Expected behavior**
Type names such as Portable Network Graphic or just PNG File.

**Screenshots**
![2019-12-30](https://user-images.githubusercontent.com/55723056/71606039-fb1faf80-2b2a-11ea-8152-8c5b899878f8.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19536.1000 (Insider build)
 - App version: 0.6.6.0

**Comment by duke7553** [comment]
This should be fixed in v0.7.1
