### ISSUE TITLE
Issue about display of file extension

### ISSUE THREAD

**Issue by Matt98** [duke7553/files-uwp#363]
**Describe the bug**
If the file is in the system disk (local disk C:), the file extension could be displayed, while if it is in other disk, the file extension disappears.

**Screenshots**
In local disk C:, the file extension could be displayed.
![image](https://user-images.githubusercontent.com/56995193/71642076-fdc40580-2ce0-11ea-9f20-7c7a7231ac28.png)

While in disk D:, the file extension disappears.
![image](https://user-images.githubusercontent.com/56995193/71642067-cbb2a380-2ce0-11ea-8b59-e9b13b741430.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10
 - App version: 0.6.6.0

**Comment by yaichenbaum** [comment]
Thank you for reporting this issue, we will take some time to investigate the cause and how to fix it in one of the next updates.

**Comment by lukeblevins** [comment]
@Matt98 @yair100 FYI: the improvements made to item loading should make the extensions be displayed more consistently. Marking this as fixed. Please re-open if this regresses or is still problematic after the next Store release.

**Comment by yaichenbaum** [comment]
v0.7.1 is in the process of rolling out.
