### ISSUE TITLE
Can I make a YouTube video on this application?

### ISSUE THREAD

**Issue by vasanthdeveloper** [duke7553/files-uwp#365]
Hello, I have a YouTube channel called [Vasanth Developer](https://vasanth.tech/youtube) in which I make technical videos. I just found this project like an hour ago and sadly, couldn't find any social media links for @duke7553 So, I decided to raise an issue here and ask @duke7553 if I have the permission to make a video about this project. Here are some of the videos I made for open-source UWP apps:

Notepads: Better Notepad!
https://youtu.be/7GXDrehNWb8

Blueflap : A Great Browser For Windows
https://youtu.be/Vbtw20h5oQQ

Thank you 🙂

**Comment by yaichenbaum** [comment]
The final call is up to @duke7553 but if you do end up making one, please make sure to stress that it is a very early beta and that many changes are planned. It would also be nice if you could mention that we are always looking for more developers to contribute.

**Comment by vasanthdeveloper** [comment]
Sure, I will keep track of this issue until the video is published. As I have a few more videos to be released before I get to this time. There is more than 2 weeks of time of @duke7553 to respond to us, before I start production for this video.

If there is anything else you would like to suggest to be included in the video, please drop a comment on this issue thread.

**Comment by yaichenbaum** [comment]
Sounds good, although this is slightly off topic if you want I can share a list of some other great UWP apps as well.

**Comment by vasanthdeveloper** [comment]
Oh, that could be awesome! You can join my Discord server and directly talk to me (visit https://vasanth.tech/discord to get a personal invite), or Tweet me at @vasanthdeveloper  🙂

**Comment by duke7553** [comment]
Of course! No need to ask permission 😀

**Comment by vasanthdeveloper** [comment]
@duke7553 Please keep this issue open as I will post the video link once I publish it. Further discussion for this video can happen here :)

**Comment by yaichenbaum** [comment]
@vasanthdeveloper Can we get an update on the video?

**Comment by vasanthdeveloper** [comment]
I have been using the FIles app on my production computer from the time I opened this issue. The problem is that right now, we are upgrading my workstation. So, there is a gap in production. Really sorry, but I am still on my point of making a video for the app.

**Comment by vasanthdeveloper** [comment]
As soon as we are back in production, this will be the first video I publish.

**Comment by yaichenbaum** [comment]
@vasanthdeveloper Do you have a time-frame?

**Comment by vsnthdev** [comment]
@yair100 The plan was to get new equipment by April 6th. But :frowning_face: due to COVID-19 both India & America are under lockdown and I can't ship my new equipment. Really :cry: disappointed to say this. But I can't make the video in the near future. Although I am watching the app development.

I am closing the issue now as I will notify you once I get back into production :frowning:

**Comment by yaichenbaum** [comment]
@vasanthdeveloper Thank you for letting us know.
