### ISSUE TITLE
Could this app add support for Chinese? I will be able to help translate it

### ISSUE THREAD

**Issue by Shomnipotence** [duke7553/files-uwp#369]
Could this app add support for Chinese? I will be able to help translate it

**Comment by SOI7** [comment]
Translations have yet to be implemented, you can follow the discussion in this issue: #37

**Comment by yaichenbaum** [comment]
I would recommend doing what @SOI7 suggested, we are tracking translations in #37. It is something we really want to do and we are almost ready for it.
