### ISSUE TITLE
For pictures format, Add Right click set as desktop background

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#371]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
Hey, thank you for opening this issue. This feature is on our roadmap and we are tracking it over at #78. Feel free comment there if you have any questions or comments on this feature.
