### ISSUE TITLE
Add item vs New, should be consistent

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#373]
**Describe the bug**
In the toolbar, the button to add a new item is called "Add item", however, in the right click context menu, it's simply called "New".

**To Reproduce**
1. Check the toolbar
2. Right click in a folder

**Expected behavior**
Both options should be called "New", same as in the old explorer.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Comment by yaichenbaum** [comment]
Thank you for creating this issue, would you rather we go with "Add Item" or "New"?

**Comment by R3voA3** [comment]
I think it makes sense to go with "New". That's how it's called in the default explorer and it's shorter.

**Comment by yaichenbaum** [comment]
There are changes in `v07.1-changes` that address this issue.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
