### ISSUE TITLE
folder with unicode character is not shown

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#374]
**Describe the bug**

**To Reproduce**
I have a folder with a unicode character ₂ is not shown in the file explorer

**Expected behavior**

**Screenshots**
Classic
![image](https://user-images.githubusercontent.com/9064351/72045423-ff995480-32f0-11ea-97b7-3bf33b360a03.png)
File UWP
![image](https://user-images.githubusercontent.com/9064351/72045448-0e800700-32f1-11ea-9c33-9fdfd1e7253a.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.1]
 - App version: [v0.6.6.0]

**Comment by yaichenbaum** [comment]
@tomyan112 Thank you for this report! I am adding it to our list of things to fix.

**Comment by yaichenbaum** [comment]
@tomyan112 Can you check if you can still reproduce this? I haven't been able to reproduce this in the upcoming v0.7.3 release.

**Comment by tomyan112** [comment]
> @tomyan112 Can you check if you can still reproduce this? I haven't been able to reproduce this in the upcoming v0.7.3 release.

It has been fixed.

**Comment by yaichenbaum** [comment]
@tomyan112 Thank you for the update.
