### ISSUE TITLE
Custom location for OneDrive

### ISSUE THREAD

**Issue by SimoneRaspagni** [duke7553/files-uwp#375]
**Is your feature request related to a problem? Please describe.**
Yes.. Actually my OneDrive path is D:\OneDrive
and when launch OneDrive from FilesUWP i receive this error message:

_Did you delete  this folder?
The folder you've navigated to was removed_

(Because app search OneDrive on C:\users\...)

**Solution**
So, in settings>preferences it would be useful add option to replace common OneDrive location

Windows 1809 build 17763.134
App version: 0.6.6.0

Thanks

**Comment by yaichenbaum** [comment]
Version 7 adds this option. We hope to roll out v7 very soon.

**Comment by SimoneRaspagni** [comment]
wow, perfect! :)

**Comment by yaichenbaum** [comment]
@SimoneRaspagni Sorry about the wait, we ran in to some issues that delayed the update and it might be another few weeks until it is sent out, make sure to keep an eye the release [page](https://github.com/duke7553/files-uwp/releases) to find out when the update is released.

**Comment by SimoneRaspagni** [comment]
Ok, thanks. No problem ;)

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
