### ISSUE TITLE
Right click - open file location

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#377]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@tomyan112 where exactly would you like the option to right click and open the file location?

**Comment by R3voA3** [comment]
I guess it makes sense to add it to the context menu of each item.

**Comment by yaichenbaum** [comment]
The thing is why would you want that on every item if you are already in the file location? Where I do see a use is once search is implemented but we haven't done that yet so I am curious what @tomyan112 is asking for.

**Comment by R3voA3** [comment]
That's a good point. Why not put it into the "Home" toolbar then?

**Comment by generalguy41** [comment]
Isn't this typically only used on shortcuts? So it could be added to the context menu for shortcuts only.

**Comment by tomyan112** [comment]
> The thing is why would you want that on every item if you are already in the file location? Where I do see a use is once search is implemented but we haven't done that yet so I am curious what @tomyan112 is asking for.

It came to my mind because it is not available in files in Recent Items. It would be handy for future shortcut files.

**Comment by yaichenbaum** [comment]
@generalguy41 We haven't added support for shortcuts yet but when we do then we can add it to their right click context menu.
@tomyan112 We already added this option for recent files and it should roll out when v0.7 is released.

**Comment by duke7553** [comment]
Closing this now.

**Comment by yaichenbaum** [comment]
@duke7553 It's fine to close this issue, we just need to keep in mind to add this to shortcuts and to the search results page when implemented.
