### ISSUE TITLE
Pivot menu suggestions

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#379]
**Is your feature request related to a problem? Please describe.**
Currently the file menu of the pivot view serves no real purpose. Putting the app settings in that category makes no sense, because they have nothing to do with files directly. 

Additionally, the "Open new window", would better fit into the layout page.

Furthermore, the options "Select all" and "Clear all" can be found in the layout page. They would better fit into the home page next to "copy" and "paste" etc. since these are file operations.

**Describe the solution you'd like**
* Remove file page

* Move the setting button into it's own pivot view page or to the footer of the nav. view as many Microsoft apps do it

* Move "Open new window" to the layout page

* Move "Select all" and "Clear all" into home menu

**Comment by yaichenbaum** [comment]
I am going to share what is changing in this area with the next update so you can adjust your feedback
![image](https://user-images.githubusercontent.com/39923744/72227753-1b5d5e80-356e-11ea-94fa-43f1468a85aa.png)
![image](https://user-images.githubusercontent.com/39923744/72227763-3a5bf080-356e-11ea-9193-eef8769b7915.png)

**Comment by R3voA3** [comment]
Alright, I like the new visual appearance of the menu.

My feedback about the layout menu (view in the next version) stays the same.

About the File menu. What about renaming it to Files UWP. That way it's clear to the user that this menu has options which interact with the app itself, like closing it, opening a new instance, or adjusting its settings.

**Comment by tomyan112** [comment]
> I am going to share what is changing in this area with the next update so you can adjust your feedback
> ![image](https://user-images.githubusercontent.com/39923744/72227753-1b5d5e80-356e-11ea-94fa-43f1468a85aa.png)
> ![image](https://user-images.githubusercontent.com/39923744/72227763-3a5bf080-356e-11ea-9193-eef8769b7915.png)

This version is cleaner than the current one.

**Comment by SOI7** [comment]
> I am going to share what is changing in this area with the next update so you can adjust your feedback
> ![image](https://user-images.githubusercontent.com/39923744/72227753-1b5d5e80-356e-11ea-94fa-43f1468a85aa.png)
> ![image](https://user-images.githubusercontent.com/39923744/72227763-3a5bf080-356e-11ea-9193-eef8769b7915.png)

May I suggest, since now the "File" section is just a button for a drop-down menu and not a ribbon area anymore, to make it a colored square like in the Win32 File Explorer, instead of giving it the colored underline?

**Comment by yaichenbaum** [comment]
> May I suggest, since now the "File" section is just a button for a drop-down menu and not a ribbon area anymore, to make it a colored rectangle like in the Win32 File Explorer, instead of giving it the colored underline?

@duke7553 This is something to consider when we work on improving the ribbon control.

**Comment by yaichenbaum** [comment]
@SOI7 I took a look at Microsoft Office and it looks like it doesn't have a rectangle around the file button. I am thinking that we should follow that design as well, do you have any specific to change it from the way it is right now?

**Comment by SOI7** [comment]
@yair100 I wouldn't really look at Office tbh since that app has a different purpose and the UI has to reflect that (Even the titlebar is different), I was suggesting to change the "File" button mainly for three reasons: 1) Familiarity with the Win32 Explorer 2) Better show it's not a ribbon section anymore, but a drop-down menu 3) Add more color to the current UI

**Comment by yaichenbaum** [comment]
@SOI7 I tested this change and it looked out of place. I don't plan on making any changes to that specific button but we will be improving the ribbon in other areas.

**Comment by yaichenbaum** [comment]
In the upcoming release, we will be replacing the ribbon with a modern navigation toolbar. This new toolbar is still in its early stages and will see improvements in future releases. With the new changes, this issue is no longer relevant. You can get an early look at these new changes with the included screenshot.

![image](https://user-images.githubusercontent.com/39923744/78294706-d0ae0b80-74f8-11ea-8df9-bbd74f2f41a0.png)
