### ISSUE TITLE
opening folder from recent items results in error popup

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#383]
**Describe the bug**
When trying to open a folder from recent items an error pops up.

**To Reproduce**
1. Open folder from recent items
2. See error

**Expected behavior**
The folder to open

**Screenshots**
https://cdn.discordapp.com/attachments/335088049170022401/671753977578389544/unknown.png

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: v0.6.6.0

**Comment by yaichenbaum** [comment]
Folders are going to be removed from the recent items list in the next update so you should not have this issue once that ships, we are also working on redesigning the home page experience #366.
