### ISSUE TITLE
Wrong Downloads folder location

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#384]
**Describe the bug**
Files UWP automatically managed to figure out the location for the Documents, Pictures , Music and Videos folders but for some reason it failed to do so with the Downloads one. All these folders including the Downloads one are straight on my E: drive.
I am aware one can manually change where these folders are located in the settings but since the automatic detection works for the other folders I'd consider it a bug that still should be fixed.

**To Reproduce**
1. Have custom location for downloads folder since before.
2. Install and run Files UWP.
3. Click on "Downloads".
4. See it take you to the default/standard location instead of the custom one.

**Expected behavior**
Expected it to show me the custom location automatically since it worked with all the other folders with custom location.

**Desktop:**
 - OS Version: Windows 10 1909 18363.535
 - App version: v0.6.6.0

**Comment by duke7553** [comment]
Hello there. Thank you for submitting this feedback. Starting in v0.7, we will auto-detect all common locations from the registry which should improve their accuracy. 

Marking this as implemented.

**Comment by Darhagonable** [comment]
This is still an issue for me on version 0.7.5

**Comment by yaichenbaum** [comment]
@Darhagonable More changes to address this will be included with v0.7.6 when it's released.

**Comment by Darhagonable** [comment]
> @Darhagonable More changes to address this will be included with v0.7.6 when it's released.

v0.7.6 still has the same issue. It works perfectly for all the other folders except for Downloads. 
Looking at the difference between the folders the only thing i can tell is that my downloads folder has it's target location with a special swedish letter in it's name "ä" and that it has a space in it if any of those could cause this.
![image](https://user-images.githubusercontent.com/14127357/79322226-d221ff80-7f0c-11ea-90d4-cc950287526a.png)

It should take me to "E:\Hämtade filer" but instead Files UWP takes me to "C:\Users\darha\Downloads"

**Comment by yaichenbaum** [comment]
@Darhagonable v0.7.6 is still in certification.
