### ISSUE TITLE
[Not urgent] Include instructions for building from source here on GitHub

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#385]
Not a high priority thing, but many projects on GitHub include in their readme instructions to build the app from source, or at least they specify the dependencies required by the solution. I tried building from source indeed, but I gave up because I couldn't figure out what's missing and what not

**Comment by yaichenbaum** [comment]
I added instructions to the [readme ](https://github.com/duke7553/files-uwp/blob/develop/README.md) file.
Thank you @lampenlampen for writing them up!
