### ISSUE TITLE
option to disable/hide OneDrive from Files UWP

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#386]
Title says it all. I don't use OneDrive and therefore would want the option to disable it or at least hide it

**Comment by yaichenbaum** [comment]
@Darhagonable thank you for creating this issue, this is definitely an option we can add in the future.

**Comment by yaichenbaum** [comment]
@Darhagonable An option for hiding OneDrive has been added in the `develop` branch, I don't have a release date yet but I will make sure to let you know when I have one.

**Comment by Darhagonable** [comment]
I just tried it out and it works but found a bug.
turning of pinned onedrive hides it but when turning it on again two of them appear instead of just one
![image](https://user-images.githubusercontent.com/14127357/74107097-e93f1c80-4b6c-11ea-9b3c-aa1153cfdfb9.png)

**Comment by yaichenbaum** [comment]
@Darhagonable Thanks for reporting the issue, its something we know about and working on resolving.

**Comment by duke7553** [comment]
@Darhagonable This should be fixed in the next Store release. Thanks for your patience.

**Comment by yaichenbaum** [comment]
v0.7.1 is in the process of rolling out.
