### ISSUE TITLE
Better controls

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#387]
The biggest issue I find with the usability of Files UWP is the missing controls that I'm used to.

these are the controls I'd like to see added:
- Back and forward buttons on the mouse to be integrated.
- Middle click (clicking scroll wheel) to open in new tab.
- CTRL+MiddleClick or Shift+MiddleClick to open in new window.

**Comment by yaichenbaum** [comment]
Can you try building off the `v07.1-changes` branch and see if the back and forward mouse button is working?

**Comment by Darhagonable** [comment]
I'm running it from MS Store and not by building it in visual studio. I attempted it but got some error so I guess i can't really do that.

**Comment by yaichenbaum** [comment]
There are plans to write instructions on running from Visual Studio in the future. What error did you get when you tried?

**Comment by Darhagonable** [comment]
When building:
https://media.discordapp.net/attachments/335088049170022401/672108379199766531/unknown.png?width=959&height=155

When trying to run anyways
https://cdn.discordapp.com/attachments/335088049170022401/672107230400741376/unknown.png

**Comment by yaichenbaum** [comment]
From the build menu try to clean and then rebuild.

**Comment by Darhagonable** [comment]
Doing so made it build without any errors but trying to run it gave me the same error.
https://cdn.discordapp.com/attachments/335088049170022401/672121283865083914/unknown.png

**Comment by yaichenbaum** [comment]
What branch are you on?

**Comment by Darhagonable** [comment]
v07.1-changes as you told me. maybe I should have opened it some other way. I just "clone or download", download zip. extracted the zip and opened Files.sln in visual studio

**Comment by yaichenbaum** [comment]
You did it correctly, can you try giving file permissions in the settings app for Windows?

**Comment by yaichenbaum** [comment]
Oh, I just realized whats happening. Make sure to select the correct project to build from.
![image](https://user-images.githubusercontent.com/39923744/73379900-19470f80-4291-11ea-8f2a-38f1e4c8e174.png)

**Comment by Darhagonable** [comment]
Oh my bad, that was it lol.
And regarding the back and forward button the mouse. Files UWP treats them as normal left click instead of going back the previous page.

**Comment by R3voA3** [comment]
Maybe merge this issue with #9 ?

**Comment by yaichenbaum** [comment]
I moved it over to #9, @Darhagonable make sure to subscribe to that issue so you will get updated when the changes are made.
