### ISSUE TITLE
Crash when changing custom folder locations in 0.7

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#388]
After building from source the branch 0.7.0, I ran the app in Debug mode. It launched fine, so I immediately went to the Settings>Preferences tab, and enabled custom folder locations. After clicking on the toggle, the app crashed. This is what Visual Studio showed me:

![Annotazione 2020-01-29 231821](https://user-images.githubusercontent.com/50930970/73402492-b3d53c00-42ed-11ea-85c8-7673cdce6230.png)

Then, I stopped the app and tried restarting it, and I noticed it kept crashing on startup, with a different error:

![Annotazione 2020-01-29 231143](https://user-images.githubusercontent.com/50930970/73402540-d23b3780-42ed-11ea-9317-955a3ff05385.png)

The only way to fix it is to uninstall the app and recompile it again. File system is enabled already

**Comment by yaichenbaum** [comment]
Please use the 0.7.1 branch.

**Comment by SOI7** [comment]
@yair100 Yeah, the issue doesn't seem to appear on 0.7.1, my bad. However, I expected 0.7 to be the most stable branch, since it's the current release candidate. How is that? (legit confusion lol)

You can close this issue I guess

**Comment by yaichenbaum** [comment]
Because we were waiting on a bug in Visual Studio to be fixed we never shipped 0.7. We are actively working on 0.7.1. I am happy to hear you got it working 🙂

**Comment by SOI7** [comment]
Ah, so I guess you're skipping 0.7 and releasing directly 0.7.1. Now that makes sense.
Yeah, it took me the whole day to understand how to build from source haha
