### ISSUE TITLE
Is anyone interested in contributing?

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#389]
Both @duke7553 and myself have been spending a lot of time working Files UWP and the feedback everyone is sending is great! Lately it has been getting harder for both of us to keep up with all the feedback and adding new features.
We both look forward and plan on continuing work on Files UWP but we are calling on the community to help us out, we are accepting pull requests and are available to help anyone get started with the code-base, looking forward to seeing some more help 🙂

**Comment by R3voA3** [comment]
I would like too, but I am not sure I am of much help since the project is has already become quite complex.

**Comment by duke7553** [comment]
@R3voA3 Are there any issues in particular you wanted to tackle? Just tag me on one, and I can try to guide you

**Comment by generalguy41** [comment]
> and are available to help anyone get started with the code-base

Where would you recommend starting? Are there tutorials you'd suggest? Or is this kind of a "we hope you have experience with this, and we'll explain our codebase"? I've wanted to dabble in some Windows development, so maybe this would be a good starting point.

**Comment by yaichenbaum** [comment]
@generalguy41 
>Where would you recommend starting?

I would recommend starting with some of the smaller issues and features, if you would like to try that then let me know and I can point you to some issues and features.

>Are there tutorials you'd suggest?

Right now the code base is a little messy but we have been working on cleaning it up, the goal is follow the MVVM pattern and there is a great tutorial [here](https://code.tutsplus.com/tutorials/how-to-use-mvvm-in-a-universal-windows-app--cms-25582) on how to use it.

>Or is this kind of a "we hope you have experience with this, and we'll explain our codebase"?

We would like anyone to be able to contribute even if they don't have so much experience, I have been improving as I work on this app but I am very much a beginner myself. Since the code base is a little messy right now it might require some help from @duke7553 or myself in getting started but we are willing to work with anyone on features and to answer your questions.

>I've wanted to dabble in some Windows development, so maybe this would be a good starting point.

This can be a great starting point and we would love for you to start helping! If you need any help getting started with Git and GitHub let me know 🙂

**Comment by generalguy41** [comment]
@yaichenbaum Thanks for the references, I'll take a look! I actually have my git and whatnot set up, and have experience with other languages (working right now as a *very* junior software dev using primarily Java). I'll see what I can do!
