### ISSUE TITLE
Can't open "properties" for any file

### ISSUE THREAD

**Issue by bingeitall** [duke7553/files-uwp#39]
Right Click on any file > Properties

( no action assigned )

**Comment by duke7553** [comment]
I'm marking this as a discussion because I would potentially like to get some mockups from the community for a Properties experience. 
![548963d1-bf40-4cba-9876-1a48e7089c21 png](https://user-images.githubusercontent.com/20365014/53528425-8f5a5980-3ab7-11e9-9cf8-7408eb64209c.jpg)

The current (in explorer) one looks like this, but I wanted to modernize it by reducing or potentially removing the many, dense tabs on top.

**Comment by PoorPocketsMcNewHold** [comment]
![Microsoft UWP file explorer](https://i.boring.host/RCIMQIN.gif)
To take some inspiration, Here's how Microsoft styled it, with the UWP Mobile file explorer. Still pretty simple, space taking (Doesn't open a separate window), and not Fluent design styled.

**Comment by PoorPocketsMcNewHold** [comment]
![propertiespanel concept](https://user-images.githubusercontent.com/13170204/53552837-94152100-3b3c-11e9-8341-b4b077b5ceea.png)

**Comment by duke7553** [comment]
@PoorPocketsMcNewHold This looks pretty good. I'm going to work on one that incorporates some of these design elements.

**Comment by yaichenbaum** [comment]
I would use a pivot control rather then a side menu.

**Comment by duke7553** [comment]
![Annotation 2019-05-27 200753](https://user-images.githubusercontent.com/20365014/58442732-29cc3800-80bb-11e9-9c47-e457060e5591.png)
This is the design I'm going for so far, still a work in progress so things will definitely change.

**Comment by duke7553** [comment]
Also, some things are broken in this screenshot.

**Comment by yaichenbaum** [comment]
I think this is a great design as it is similar to the existing version and will be familiar to users. About using rounded corners how far should they be users? Should they be on buttons and text boxes too?

**Comment by duke7553** [comment]
@yaichenbaum Short answer: Yes, but very subtle applications are key.

I'm currently updating Files to use the in-progress specification documented [here](https://github.com/microsoft/microsoft-ui-xaml-specs/tree/user/chigy/roundedcorner/active/RoundedCorner)
and elaborated upon [here](https://github.com/mrlacey/microsoft-ui-xaml-specs/blob/RoundedCornerVisualizations/active/RoundedCorner/ImageFiles/index.md)

**Comment by yaichenbaum** [comment]
Got it, so for buttons and text boxes it's mainly 2px?

**Comment by duke7553** [comment]
Yes that’s correct. However, flyouts will use 4px, while some controls like TabView don’t support CornerRadius property yet.

**Comment by yaichenbaum** [comment]
I think I will work on some buttons and text boxes then, is flyouts content dialogs?

**Comment by duke7553** [comment]
To my knowledge flyouts are technically context menus or small notification banners, but context dialogs also fall under this 4px category.

**Comment by yaichenbaum** [comment]
Perfect, I am trying to build from Master and I am getting `Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	ExecutableLauncher	C:\Program Files\dotnet\sdk\2.1.700\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	
`

**Comment by yaichenbaum** [comment]
Just installed .NET Core 3 hope this fixes it.

**Comment by duke7553** [comment]
![{1B82D93F-C4C1-49AF-9418-4D433110963D}](https://user-images.githubusercontent.com/20365014/59478391-1cd37680-8e27-11e9-905f-a76853443c3a.png)
I decided to remove the pivot control for the initial implementation. It will likely return when more properties are supported. I'll have this hooked up to the code behind very soon. Sorry for the delay.

**Comment by duke7553** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
Good idea for now, once the initial release is ready it should be simple to scale up this page.

**Comment by avknaidu** [comment]
@duke7553 I don't think so much space between each property item is necessary. You can decrease the top and bottom margins by atleast 6px and fit more properties in the same window. Just a suggestion.

**Comment by yaichenbaum** [comment]
This has been addressed in 722f9ef640716b744cd3989a25ff2cb85a7e75f6
