### ISSUE TITLE
Remove separator from Settings.xml

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#390]
![image](https://user-images.githubusercontent.com/17484252/73433840-d85d0280-4345-11ea-8403-c740d01606f4.png) 

             ``

`<!--<Setter Target="Divider.Visibility" Value="Visible" />-->`

Looks much better when those lines are removed.

**Comment by yaichenbaum** [comment]
This is because there is acrylic in the sidebar, this is not meant to show in the settings page and will be turned off in the future. Once the settings page is done it will be very similar to how its done in Microsoft Edge.

**Comment by yaichenbaum** [comment]
This is how it looks without acrylic.

![image](https://user-images.githubusercontent.com/39923744/74098308-b0f3fb80-4ae4-11ea-9c4e-adb97b2316e9.png)
