### ISSUE TITLE
CMD ignores starting folder when ran through Files

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#392]
**Describe the bug**
CMD doesn't use the folder from which you launch it in Files as the starting path

**To Reproduce**
Right click on an empty spot inside a folder, then "Open in terminal"

**Expected behavior**
The starting path should be the folder from which you launched CMD, instead of System32

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 x64
 - App version: v0.7.1

**Additional context**
I tried other profiles as well. Powershell Core 6 works fine, but it doesn't like folders with spaces in their name (duh). I also tried creating two profiles for Powershell Core 5 (since Core 6 is an optional package and not everyone have it I guess, also for backwards compatibility) and Windows Terminal but that's another story. I'm posting my terminal.json as well so you can check syntax and arguments as requested by @lampenlampen:

{
  "version": 1,
  "terminals": [
    {
      "id": 1,
      "name": "CMD",
      "path": "cmd.exe",
      "arguments": "-WorkingDirectory {0}",
      "icon": "C:\\Users\\felix\\Pictures\\BingImageOfTheDay_20190730.jpg"
    },
    {
      "id": 2,
      "name": "PowerShell Core 5",
      "path": "powershell.exe",
      "arguments": "-WorkingDirectory {0}",
      "icon": "C:\\Users\\felix\\Pictures\\BingImageOfTheDay_20190730.jpg"
    },
    {
      "id": 3,
      "name": "PowerShell Core 6",
      "path": "pwsh.exe",
      "arguments": "-WorkingDirectory {0}",
      "icon": "C:\\Users\\felix\\Pictures\\BingImageOfTheDay_20190730.jpg"
    },
    {
      "id": 4,
      "name": "Windows Terminal",
      "path": "wt.exe",
      "arguments": "-WorkingDirectory {0}",
      "icon": "C:\\Users\\felix\\Pictures\\BingImageOfTheDay_20190730.jpg"
    }
  ]
}

**Comment by lampenlampen** [comment]
There is something wrong with your arguments.

Try this `profiles.json` file:
``` json
{
    "version": 1,
    "terminals": [{
            "id": 1,
            "name": "CMD",
            "path": "cmd.exe",
            "arguments": "/k \"cd /d {0} && title Command Prompt\"",
            "icon": ""
        },
        {
            "id": 2,
            "name": "PowerShell Core 6",
            "path": "pwsh.exe",
            "arguments": "-WorkingDirectory {0}",
            "icon": ""
        }
    ]
}
```

**Comment by lampenlampen** [comment]
Did you alter the cmd profile?
Because it should look like mine.

**Comment by lampenlampen** [comment]
I had a look into the `v07.1`-branch and the default cmd profile there also looks like mine.

**Comment by SOI7** [comment]
Apart from creating the two extra profiles for the old PowerShell and Windows Terminal, I didn't change anything else since I built 0.7.1. The stranger thing is, changing the CMD arguments with yours makes the app crash

**Comment by lampenlampen** [comment]
You can test if the arguments are correct by launching `cmd.exe /k \"cd /d C:\Users\ && title Command Prompt\"` via Win+R

**Comment by SOI7** [comment]
Oh God, I'm an idiot. The argument has already an " at the end, so in my json file it should have ended with two. Now it works 😓

**Comment by lampenlampen** [comment]
The problem with the spaces in paths is easily solved by putting the `{0}` in "".

**Comment by SOI7** [comment]
Got it, thanks! You can close this issue I guess

**Comment by yaichenbaum** [comment]
@lampenlampen many thanks for resolving this!
