### ISSUE TITLE
executable files

### ISSUE THREAD

**Issue by Salnikoff** [duke7553/files-uwp#395]
Hello! 
I like your application. But, some executable files can't running from "files uwp". Don't know why...

Little video, how it's happenning  

 https://1drv.ms/v/s!Aic9SgC0Kq5Gx2uu1lr3b_DvnnQT?e=ou4Hpx

not very well speak English. Hope you understand me -:)

**Comment by yaichenbaum** [comment]
Thanks for reporting this, we have a potential fix that has not yet rolled out to the store yet.

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).

**Comment by Salnikoff** [comment]
ok, thanks guys!

**Comment by Salnikoff** [comment]
will be testing it...
