### ISSUE TITLE
USE KEYBOARD TO SEARCH A FOLDER

### ISSUE THREAD

**Issue by deredita25** [duke7553/files-uwp#398]
**Describe the bug**
HOLA!! DEBERIA PODER USARSE EL TECLADO PARA ENCONTRAR CARPETAS POR LETRAS, POR EJEMPLO SI PRESIONO LA TECLA"S" TENDRÍA QUE MOSTRAR TODAS LAS CARPETAS QUE COMIENZAN CON "S"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by deredita25** [comment]
HOLA!! DEBERIA PODER USARSE EL TECLADO PARA ENCONTRAR CARPETAS POR LETRAS, POR EJEMPLO SI PRESIONO LA TECLA"S" TENDRÍA QUE MOSTRAR TODAS LAS CARPETAS QUE COMIENZAN CON "S"

**Comment by R3voA3** [comment]
> HELLO!! YOU SHOULD BE ABLE TO USE THE KEYBOARD TO FIND FOLDERS BY LETTERS, FOR EXAMPLE IF I PRESS THE "S" KEY IT SHOULD SHOW ALL THE FOLDERS THAT START WITH "S"
(Translated with DeepL)

**Comment by yaichenbaum** [comment]
> HELLO!! YOU SHOULD BE ABLE TO USE THE KEYBOARD TO FIND FOLDERS BY LETTERS, FOR EXAMPLE IF I PRESS THE "S" KEY IT SHOULD SHOW ALL THE FOLDERS THAT START WITH "S"
> (Translated with DeepL)

It should already jump to the folders starting with the letter you press. If you don't see that behavior you might want to try updating to the latest version.

**Comment by yaichenbaum** [comment]
If you can still reproduce this issue with the latest release please feel free to reopen this issue.
