### ISSUE TITLE
error trying to read disk SSD

### ISSUE THREAD

**Issue by deredita25** [duke7553/files-uwp#399]
Hi...first of all Great job!!
I found an error trying to read an SSD (sent pic)....I have the last version (0.6.6.0) on the other hand the behavior to press any key don't show me any folder  🤔 I'll would be grateful if you explain to me how to do that... Good luck
I
![2020-02-07_13h43_53](https://user-images.githubusercontent.com/60778522/74049088-2f9c4c00-49b2-11ea-81f4-ed8e2c98a0c3.jpg)

**Comment by yaichenbaum** [comment]
@deredita25 Thanks for the report, there is a potential fix in the `develop` branch for the drives not reading correctly.
>  on the other hand the behavior to press any key don't show me any folder

Are you talking about the feature that hitting a key will jump to a folder or file that starts with the character?

**Comment by deredita25** [comment]
Yes I am !! that feature isn’t work…. Sent from Mail for Windows 10 From: Yair yair100: viernes, 7 de febrero de 2020 14:05To: duke7553/files-uwpCc: deredita25; MentionSubject: Re: [duke7553/files-uwp] error trying to read disk SSD (#399) @deredita25 Thanks for the report, there is a potential fix in the develop branch for the drives not reading correctly.on the other hand the behavior to press any key don't show me any folderAre you talking about the feature that hitting a key will jump to a folder or file that starts with the character?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by duke7553** [comment]
@deredita25 Can you please let us know if this is still an issue in the v0.7.1 Store release?

**Comment by duke7553** [comment]
@deredita25 We made some changes with v0.7.1 which hide unsupported drives. Please reopen if this is still an issue.
