### ISSUE TITLE
No Custom Library Locations

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#4]
Marked as still in development, just thought it would be beneficial to have here.

Feel free to close if you don't want the clutter.

**Comment by duke7553** [comment]
Good feedback. 
Because many have a need for this, I will likely implement this feature at the same time as external storage support lands.

**Comment by duke7553** [comment]
@z0oinks I've pushed this change to the newui branch, so it should appear in the next snapshot I release. Sorry for the delay.
