### ISSUE TITLE
feature request: add used/free space

### ISSUE THREAD

**Issue by SimonTek27** [duke7553/files-uwp#40]
sorry if i write this topic on a wrong section of the project.

here the question: is it possible to add the bar which shows free/used space below each driver?

**Comment by duke7553** [comment]
There already is a page in Windows Settings that provides this information. I don't think adding this information would fit well with the current aesthetic of Files. 
Not promising anything, but maybe in the future we'll add a pro-mode with a ribbon and drive storage info.

**Comment by ATecSolution** [comment]
If there was a 'this pc' page in the app, it would make sense to have the information there.

**Comment by SimonTek27** [comment]
> 
> 
> If there was a 'this pc' page in the app, it would make sense to have the information there.

Yes, i agree with you cause i see this app as a very good alternative to 'this pc' so here the reason why i wrote the previous post

**Comment by duke7553** [comment]
Change of plans. There won't be any unused space indicator on the Favorites page, but I will include this information within the Properties dialog.

**Comment by yaichenbaum** [comment]
What about making a 'This PC' page?

**Comment by yaira2** [comment]
@SimonTek27 this information is now available in the properties window. You can download the latest version of Files from https://files.community/download.
