### ISSUE TITLE
[Not Urgent] Native support for zip files

### ISSUE THREAD

**Issue by MrErikDev** [duke7553/files-uwp#403]
Hey
I think it would be nice to add built in support to open zip files (and similar), the same way it is built in to explorer. For now you _can_ just use something like 7zip but its nice to have it all in one imo.
:)

**Comment by duke7553** [comment]
This remains a priority for us. No deadlines yet, but the work to support extracting ZIP files will be done eventually.

**Comment by duke7553** [comment]
Moving this to #45
