### ISSUE TITLE
Opening a folder with an .ink file inside it will cause the app to crash

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#409]
The crash happens every time an .ink file is visible. The version I tested this on is the latest beta release, 0.7.0

**Comment by duke7553** [comment]
@SOI7 I'm having trouble reproducing this, so exactly what program produces these files? Do you mean .LNK rather than .ink?

**Comment by SOI7** [comment]
No, I meant .ink as shortcut files

**Comment by duke7553** [comment]
Thanks. I've changed it to not display the shell link files which we don't support opening.

**Comment by duke7553** [comment]
Please reopen this issue if you can reproduce this with the latest develop branch changes.
