### ISSUE TITLE
Files UWP 0.7 production packages

### ISSUE THREAD

**Issue by KaKi87** [duke7553/files-uwp#413]
**Is your feature request related to a problem? Please describe.**

The package provided for Files UWP v0.7 requires development dependencies to be installed, but I do not want to install these.

**Describe the solution you'd like**

Create a similar package in production mode instead of debug mode.

**Describe alternatives you've considered**

There is not.

**Additional context**

![2020-02-13 20_18_26-Files 0 7 0 beta](https://user-images.githubusercontent.com/21284089/74470047-0f7ef800-4e9e-11ea-9bf1-490d5c698bb6.png)

**Comment by yaichenbaum** [comment]
Run the powershell script.

**Comment by KaKi87** [comment]
I understand, but you can compile the APPX in production mode instead of debug mode.

**Comment by yaichenbaum** [comment]
@KaKi87 Unfortunately that's where the problem is. There is an issue with the .NET Native toolchain which is required to create a production package.

**Comment by KaKi87** [comment]
So you can't build a prod APPX even without publishing on Windows Store ?
How does the others developers ?

**Comment by yaichenbaum** [comment]
We have a Win32 component with a full trust process, that is what's causing this issue. Other developers have run into the issue as well and the Visual Studio team is looking into it.

**Comment by KaKi87** [comment]
Why is that component working in debug mode but not in production mode ?

**Comment by yaichenbaum** [comment]
It has something to do with the .NET Native toolchain, I don't know why it is but this has been blocking us from doing a normal release for a few months.

**Comment by lampenlampen** [comment]
Because the .Net Native toolchain is only used in production mode. In debug mode the code is compiled to IL code running on the CoreCLR.

**Comment by KaKi87** [comment]
I understand. Thanks. I'll be waiting for the production version.

**Comment by duke7553** [comment]
@KaKi87 Thank you for your patience. This is a confirmed bug with VS 2019 where we got a supposed fix which actually wasn't the correct solution. When, we can build production packages, you can bet they'll be released immediately as there are many noticeable improvements in v0.7.

**Comment by KaKi87** [comment]
Could you please link the Microsoft issue ?

**Comment by duke7553** [comment]
@KaKi87 Of course! Here you go: https://developercommunity.visualstudio.com/content/problem/871255/packaging-project-microsoftdesktopbridgetargets591.html

**Comment by KaKi87** [comment]
It's not even on GitHub 😂

**Comment by yaichenbaum** [comment]
@KaKi87 0.7 has been released on the store.

**Comment by KaKi87** [comment]
Finally ! I'm looking into it right now :)

**Comment by yaichenbaum** [comment]
We hope to have another build soon with some bug fixes, hopefully you don't run into any before that.

**Comment by KaKi87** [comment]
Let's say that, at least, I get to contemplate the home screen xD

**Comment by yaichenbaum** [comment]
This new release is not going to be getting release notes since its a minor patch, but I will outline the basics of what's included.
- potential fix for the crash at startup
- includes a fix for the pathbar not letting you enter a custom location
- includes a fix for navigating in setting
- fixes text getting cut off in some regions

**Comment by KaKi87** [comment]
What do you mean by "not getting release notes" ?

**Comment by yaichenbaum** [comment]
@KaKi87 We usually do a GitHub release for updates and include a sideload package. This time we will be skipping that and just releasing it on the store

**Comment by KaKi87** [comment]
That is against open source spirit.

**Comment by yaichenbaum** [comment]
@KaKi87 The code is all available, the only difference is that it won't be recorded because it's just a minor patch.

**Comment by KaKi87** [comment]
Well, using git is pointless if you don't record even the smallest patches.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, I will keep this in mind and when we get a working package we will upload it 🙂
