### ISSUE TITLE
Feedback on touch usage

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#414]
Touching files mimics Win32 explorer
so when you touch on the name of a file it renames when you might not want to
Another slight issue is that the tabs mimic new Edge, where the close button is shown on every tab, instead of only the current tab, which might cause you to accidentally close tabs
I actually think MS should move the close button to the left of the tab, since I sometimes accidentally close the right-most tab, when I want to open a new tab with touch.
Anyway, I can adapt to the current behaviors, so don't change things just because of my feedback
Overall, I like it.
Also, nice to see a QuickLook item in the context menu.
So it can be used with touch
It would be nice to also have a QuickLook button in the toolbar
and maybe a way to active it with some gesture.
or a way to open with quicklook by default
Just how FineBits FIles & Folders opens files with its built-in viewer by default

**Comment by duke7553** [comment]
I think #261 and #100 will address this one. Please re-open if you've got anything else in mind.
