### ISSUE TITLE
Suggestion: put the file explorer commands in a scrollviewer

### ISSUE THREAD

**Issue by imthewiseguy** [duke7553/files-uwp#417]
**Is your feature request related to a problem? Please describe.**
the file explorer commands get cut off when the window is small
![image](https://user-images.githubusercontent.com/25320332/74603200-e9a44f80-5065-11ea-8df6-55912fe1fa74.png)

**Describe the solution you'd like**
put the commands in a ScrollViewer control

**Describe alternatives you've considered**
remove labels via Visualstates

**Comment by yaichenbaum** [comment]
@imthewiseguy What version of the app do you have? In the latest [release ](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0) the labels already hide when the window is sized smaller.

**Comment by imthewiseguy** [comment]
Oh ok I was using the store version

Sent from my iPhone

On Feb 16, 2020, at 7:18 AM, Yair Aichenbaum <notifications@github.com> wrote:

﻿

@imthewiseguy<https://github.com/imthewiseguy> What version of the app do you have? In the latest release <https://github.com/duke7553/files-uwp/releases/tag/v0.7.0> the labels already hide when the window is sized smaller.

**Comment by yaichenbaum** [comment]
@imthewiseguy Thanks for letting me know if you find it's still an issue feel free to reopen this issue.
