### ISSUE TITLE
Clicking folders twice in sidebar navigates to wrong location

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#418]
When clicking on a folder in the sidebar twice, OneDrive location is automatically selected. Might be because OneDrive is the last entry in the sidebar for me.

This is in version 7.1

**Comment by yaichenbaum** [comment]
This is something already on our roadmap to fix, thank you for opening the issue so we can track it.

**Comment by yaichenbaum** [comment]
This has been fixed with 96492dd4f257ca3fc35327766e3e20d600935496. It will roll out with v0.7.2.

**Comment by yaichenbaum** [comment]
This issue crept back up and it looks like it will need to be fixed differently. It is still on our roadmap to fix with v0.7.2.

**Comment by yaichenbaum** [comment]
This issue has been fixed, it should roll out with `v0.7.2`.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
