### ISSUE TITLE
Width of the acrylic sidebar label in appearance.xml is too narrow for the German localisation

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#419]
Width of the acrylic sidebar label in appearance.xml is too narrow for the German localisation.

![image](https://user-images.githubusercontent.com/17484252/74694362-256b2080-51f0-11ea-9851-06b233583558.png)

**Comment by yaichenbaum** [comment]
Thank you for catching this, I will go through these labels and make sure they can fit longer text.

**Comment by yaichenbaum** [comment]
I have made some improvements to fix this with 1c741a014a2d6378eaa942daf29ac2bfd2e90375.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
