### ISSUE TITLE
The app closes when I click on "Downloads"

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#421]
When I open the "downloads" folder from the sidebar, the app closes

OS: W10 1909
App v0.7.0

**Comment by xPoppyx** [comment]
**update:** 
- For some reason, now this is happening with the "Desktop" folder too
- If I click on other folders / drives and then click on downloads or desktop, the app no ​​longer closes.

**Comment by yaichenbaum** [comment]
There is some inconsistent behavior around opening items from the sidebar where opening them sometimes causes a crash, we are aware of this issue and are looking into it.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
