### ISSUE TITLE
Opening the Desktop folder crashes the app

### ISSUE THREAD

**Issue by Spyromaniac31** [duke7553/files-uwp#428]
**Describe the bug**
Upon opening the Desktop folder immediately through the side bar crashes the app

**To Reproduce**
1. Open Files UWP
2. Click on Desktop on the sidebar
3. The app crashes

Steps to prevent the behavior from occuring:
1. Open Files UWP
2. Navigate to This PC\...\Desktop manually
3. Click on another folder in the sidebar
4. Click on Desktop in the sidebar
5. The app is fine

**Expected behavior**
The app should not crash

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home Insider Preview build 19569
 - App version: v0.7.0.0

**Additional context**
Problem occurs after restarting computer
Desktop folder contains .lnk files, .url files and a folder

**Comment by SOI7** [comment]
It may be related to .ink files as reported on #409

**Comment by yaichenbaum** [comment]
@SOI7 That is a possibility, another possible reason for this is that some parameters are set wrong. We are working on resolving both possible causes.

**Comment by duke7553** [comment]
#409 should have fixed this in v0.7.1. Thanks for reporting.
