### ISSUE TITLE
Right click on favorites causes Files UWP to crash

### ISSUE THREAD

**Issue by pat-san** [duke7553/files-uwp#429]
Hi,
Just to see if there were options by right clicking on favorites in sidebar, it make FUWP crash.

**Comment by yaichenbaum** [comment]
@pat-san Thank you for opening the bug report.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
