### ISSUE TITLE
No hover shadows on cards in dark mode

### ISSUE THREAD

**Issue by ATecSolution** [duke7553/files-uwp#43]
I only see shadows when hovering over the cards in home in light mode.

**Comment by duke7553** [comment]
Yes, right now this is intentional, but in the near future, I plan on making the dark theme a little less dark. Right now, it's mostly pitch black. I would like to start a discussion on usability for this. I'll keep you posted, and please tell me what you think.

**Comment by ATecSolution** [comment]
@duke7553 you can close this issue now since you addressed this issue already 👍
