### ISSUE TITLE
Only appearance tab accessible in parameters.

### ISSUE THREAD

**Issue by pat-san** [duke7553/files-uwp#430]
Hi,
In parameters, I'm blocked on appearance tab, can go to start, preferences, files & folders, about.
And the text is shortened (see image) whatever the window's size.

![image](https://user-images.githubusercontent.com/44109252/75611443-e48dd880-5b1a-11ea-8c50-8ca59369cad3.png)

Desktop
 - W10 1909 up to date
 - Files UWP beta

**Comment by yaichenbaum** [comment]
A fix for this is already implemented and should roll out with the next update.

**Comment by KaKi87** [comment]
I'm experiencing the same issue. Besides tabs not switching, please notice the text being cut.

**Comment by yaichenbaum** [comment]
@KaKi87 Both of those issues have been fixed in the `develop` branch.

**Comment by yaichenbaum** [comment]
v0.7.1 is in the process of rolling out.
