### ISSUE TITLE
Ctrl+A with no selected files or folders

### ISSUE THREAD

**Issue by pat-san** [duke7553/files-uwp#431]
Hi,
If no files or folders are selected in a window, I need to press Ctrl+A two times to select all

To Reproduce:
Open FUWP, go to a folder with files or subfolders, nothing selected, press Ctrl+A to "select all".

Expected behavior:
This should select all files and/or folders

 - W10 1909
 - FUWP beta

**Comment by yaichenbaum** [comment]
@pat-san Thank you for opening this issue. We already have an open issue #9 for this, make sure to subscribe to the issue to get updated when its implemented.
