### ISSUE TITLE
Settings Not Work

### ISSUE THREAD

**Issue by KiriKirby** [duke7553/files-uwp#432]
||No matter you choose what in the settings' sidebar, it will go to Appearance settings.||

-Steps to reproduce the behavior-
1. Go to 'Settings'
2. Click on other options in the sidebar, such as "startup, preferences, about..."
3. Whatever you choose it will go to "Appearance"

-Screenshots-
![2](https://user-images.githubusercontent.com/60438557/75619530-130dc100-5bb8-11ea-9f88-d1b8c56f726b.gif)

 -OS Version-
Windows 10 1909 18363.657

**Comment by yaichenbaum** [comment]
Duplicate of #430. A fix for this is already in the `develop` branch.
