### ISSUE TITLE
Crash if mostRecentlyUsed file is deleted

### ISSUE THREAD

**Issue by lampenlampen** [duke7553/files-uwp#435]
**Describe the bug**
Files tries to populate the mostRecentlyUsed list with files and crashes if one of these files was deleted with `FileNotFoundException`.

**Comment by duke7553** [comment]
@lampenlampen I cannot reproduce this one with the latest develop branch changes. Can you?

**Comment by yaichenbaum** [comment]
I wrapped it in a try\catch just so I can run the application but the issue is still there.

**Comment by lukeblevins** [comment]
@yair100 
![image](https://user-images.githubusercontent.com/20365014/76460218-03f6f200-63b4-11ea-9675-a16e880c2d20.png)
This one?

**Comment by yaichenbaum** [comment]
@duke7553 Yes, that is the one.

**Comment by yaichenbaum** [comment]
@lampenlampen Can you still reproduce this? I believe the try\catch was enough.

**Comment by lampenlampen** [comment]
can't reproduce anymore 👍.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
