### ISSUE TITLE
The first opening of a new window is really slow

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#438]
**Is your feature request related to a problem? Please describe.**
I really like the speed of the files app 0.7.0 now but the first opening of a window is really slow: it takes around 3 seconds on my machine (Microsoft Surface Pro 3 with i5 on Windows 10 1909)

**Describe the solution you'd like**
would be really nice, if you would match the speed of the file explorer as well, which opens instantly.

**Describe alternatives you've considered**
Nothing currently.

**Additional context**
It hangs here for around 3 seconds until it opens the UI, which feels like a small eternity.
![image](https://user-images.githubusercontent.com/42591237/76128507-cd605680-6004-11ea-8863-156bd9d14a4b.png)

**Comment by yaichenbaum** [comment]
Are you running the debug version I uploaded, or is it the version from the store?

**Comment by szaimen** [comment]
I've installed the 0.7.0 version directly from github via the provisioned powershell script.

**Comment by yaichenbaum** [comment]
@szaimen I would recommend getting it from the store, the launch speed should be a lot faster.

**Comment by szaimen** [comment]
Ah, I haven't seen that it is finally in the store again. Yes, the version from the store is much faster 👍
Closing!

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
