### ISSUE TITLE
Right-clicking on an item in the favorites-bar crashes the app

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#439]
**Describe the bug**
Right-clicking on an item in the favorites-bar crashes the app

**To Reproduce**
1. open the files app
2. Right-click on an item in the favorites-bar
3. the app crashes.

**Expected behavior**
The app shouldn't crash

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: 0.7.0

**Comment by yaichenbaum** [comment]
Can you confirm if this is the same issue as #429?

**Comment by szaimen** [comment]
It seems like 👍
Closing!
