### ISSUE TITLE
The program will crash when using the shortcut(.lnk)

### ISSUE THREAD

**Issue by HaoTian22** [duke7553/files-uwp#441]
**Describe the bug**
The program will crash when using the shortcut(.lnk)

**To Reproduce**
1. Double-Click on a shortcut(.lnk)
2. About 3 sec later, the program crash

**Expected behavior**
I think it can open the folder in the shortcut in the normal situation.

**Screenshots**
![image](https://user-images.githubusercontent.com/48882584/76155708-bf0c5a80-612a-11ea-8be2-37f413228143.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004 19041.113]
 - App version: [v0.7.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes

**Comment by yaichenbaum** [comment]
We do not support shortcut files yet, in the meantime, it's recommended to avoid opening them.

**Comment by lukeblevins** [comment]
@yair100 @HaoTian22 These will be hidden in the next version until we can properly support them.

**Comment by duke7553** [comment]
@HaoTian22 We'll have proper support for viewing and opening these types of items when https://github.com/duke7553/files-uwp/issues/177 is implemented, so please subscribe to that one.

**Comment by yaichenbaum** [comment]
v0.7.1 is in the process of rolling out.
