### ISSUE TITLE
Error when trying to install 7.1.0

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#452]
Running the Install.ps1 script leads to this error. I tried with both updating Files and doing a clean install

![image](https://user-images.githubusercontent.com/50930970/76435740-b086a300-63b7-11ea-9754-58e48e6fbd4b.png)

**Comment by yaichenbaum** [comment]
You might need to wait for the store version to be released if the sideload package isn't working.

**Comment by SOI7** [comment]
Oh? So the VS bug that prevented you to compile Store builds is gone, I guess

**Comment by yaichenbaum** [comment]
The bug is still there, but we have been able to find a temporary workaround.

**Comment by WinObs** [comment]
Seeing the same issue here.
![Annotation 2020-03-11 121226](https://user-images.githubusercontent.com/40800748/76438775-d13c0200-6391-11ea-88ea-316209b1193a.png)

**Comment by yaichenbaum** [comment]
It might help to restart your computer and try sideloading again.

**Comment by WinObs** [comment]
Thanks for the suggestion – I did try that and received the same error. For now have installed the 0.7.0 Microsoft Store version waiting on the update to come once it is available.

Thanks.

Rich

**Comment by yaichenbaum** [comment]
Sorry about the inconvenience with the sideload package. The store update is still finishing certification and will be out as soon as that is done.

**Comment by Crocodile73** [comment]
could be its the wrong file in the zip, as it says arm_arm64. may just need updating.

**Comment by WinObs** [comment]
Appreciate the update. Just grabbed Quick Pad to work with in the meantime.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by yaichenbaum** [comment]
v0.7.1 is no available on the Microsoft Store.

**Comment by WinObs** [comment]
Superb – downloaded, installed and working!
