### ISSUE TITLE
Crash when quickly moving between folders

### ISSUE THREAD

**Issue by leyheart** [duke7553/files-uwp#454]
Example: Open the app, and just click each folder listed on the left in rapid succession. It'll crash almost instantly.

**Comment by yaichenbaum** [comment]
@leyheart Thank you for reporting this issue, a potential fix for this issue will be coming when we release v0.7.2. We will make sure to let you know when that's released.

**Comment by yaichenbaum** [comment]
I believe this issue is connected to #422 and #421. The behavior doesn't happen 100% of the time but it does happen occasionally. Make sure to subscribe to both of those issues to get notified when v0.7.2 is rolling out.
