### ISSUE TITLE
A video(gif) showing problems I found

### ISSUE THREAD

**Issue by leyheart** [duke7553/files-uwp#455]
First, can you not disable "recent files" from showing? I've done that on the original File Explorer and I'd love for it to be the same way here. Second problem shown, I didn't even knew existed until I found accidentally when recording. I went to Pictures folder, clicked empty space in the folder and it sent me straight back to the Home tab. Third, which is kind of a large deal-breaker, is that you cannot drag and highlight multiple items. Fourth, going into a sub-folder of Pictures and back to Pictures, it set the layout to details instead of icons. Lastly, I cannot change layout from detail to icons on anything, and it does not change after restarting app.
![2020-03-11-20-47-49](https://user-images.githubusercontent.com/62083456/76479729-cc4f7080-63da-11ea-953d-58bd2e094ace.gif)

**Comment by leyheart** [comment]
One thing I wanted to add: do you have a discord server for this app?

**Comment by yaichenbaum** [comment]
There is a channel for Files UWP in the [UWP Community Discord](https://discord.gg/SzpkFNU).
> First, can you not disable "recent files" from showing?

I need more information on what you're requesting here.

> I went to Pictures folder, clicked empty space in the folder and it sent me straight back to the Home tab.

Did you click and drag the mouse very quickly? There is a gesture implemented that may be causing this issue.

> Third, which is kind of a large deal-breaker, is that you cannot drag and highlight multiple items.

- Drag and drop support is on our roadmap for the near future #88 
- A selection rectangle is planned but there is no timeframe for that yet #94 

> Fourth, going into a sub-folder of Pictures and back to Pictures, it set the layout to details instead of icons. Lastly, I cannot change layout from detail to icons on anything, and it does not change after restarting app.

Layout modes have not been implemented yet #214.

Keep opening issues and commenting on existing ones to let us know which features you would like to see next 🙂

**Comment by leyheart** [comment]
![image](https://user-images.githubusercontent.com/62083456/76483848-1b4ed300-63e6-11ea-804f-54be4eaa5a7f.png)
I'd like to be able to remove this, and I can't find anything related to this in the settings.
And no, just as seen in the gif, I just randomly left clicked and it happened. I'm unsure what happened.

**Comment by yaichenbaum** [comment]
Home page customization is on the roadmap #366. I am not able to reproduce the other error though 🤔

**Comment by Jaiganeshkumaran** [comment]
@leyheart We now have a Discord server: https://discord.com/invite/mr5hVu8
