### ISSUE TITLE
Halo appearing on the selection of drives is distracting

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#461]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/9064351/76699340-78e56700-66e7-11ea-9404-b2b3bdfd3d51.png)

**Describe the solution you'd like**
Remove the halo

**Additional context**
app version 0.7.1.0

**Comment by yaichenbaum** [comment]
The effect is called "reveal", and it can be found throughout Windows 10. I think the reason why it is distracting here is that it has a double effect from the item above and bellow in the list. We should spend some time improving this so it only shows reveal on the actual item that has the focus.

**Comment by tomyan112** [comment]
> The effect is called "reveal", and it can be found throughout Windows 10. I think the reason why it is distracting here is that it has a double effect from the item above and bellow in the list. We should spend some time improving this so it only shows reveal on the actual item that has the focus.

You are right, the start menu has it too. It is much thinner than the one in files uwp.

**Comment by yaichenbaum** [comment]
The reveal effect has been toned down with d9856ebcbde16ef5e3885ba741288554174579b5. When v0.7.2 rolls out, it will include this change.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
