### ISSUE TITLE
Compressed File Support needed

### ISSUE THREAD

**Issue by TheMayhem6328** [duke7553/files-uwp#462]
### **Files UWP is a buggy app, but I will say that it is a beautiful one!**

Nevertheless, I it isn't a complete replacement for explorer.exe. I would be glad to see compressed file support so that I don't have to use 7-Zip or any other third-party apps to open ZIPs or 7Zs or RARs.

Apart from this, I see no other problems (except random crashes)! Keep it up, @duke7553 !

**Comment by duke7553** [comment]
@TheMayhem6328 Thanks for reporting this. Regarding the random crashes, what version of the app is this, and what device is this running on?

**Comment by yaichenbaum** [comment]
@TheMayhem6328 The next release we are working on will fix a couple of crashes, it would be helpful to know if there are specific actions that are causing the app to crash.

**Comment by yaichenbaum** [comment]
v0.7.2 added the option to extract files, we are still working on improving this functionality and are tracking it in #45.
