### ISSUE TITLE
Please add inset (projecting from the main content onto the left pane) shadow to sidebar

### ISSUE THREAD

**Issue by carmellolb** [duke7553/files-uwp#466]
Michael West's concepts included this and it was perfect.

Add an inset shadow to the sidebar, it will assist with visual hierarchy and will look more visually appealing as well.

screenshot: https://mspoweruser.com/wp-content/uploads/2019/03/File-Explorer-1.jpg

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by carmellolb** [comment]
Just want to point out that Microsoft actually uses this on the new File Explorer that is being developed, which you can see in the app in Windows 10X and the image that MS showed of it on the redesigned Windows 10 in the video last week showcasing the new UI.

**Comment by yaichenbaum** [comment]
@carmellolb The video the showed was just a concept, the actual File Explorer looks very different than that and will likely end up looking more like the OneDrive website. In any case, we will be closely watching development on that end and take inspiration. I will also explore adding a shadow to the sidebar to see how it looks.

**Comment by carmellolb** [comment]
> @carmellolb The video the showed was just a concept, the actual File Explorer looks very different than that and will likely end up looking more like the OneDrive website. In any case, we will be closely watching development on that end and take inspiration. I will also explore adding a shadow to the sidebar to see how it looks.

okay, and also keep in mind that a standard shadow would mess up the visual hierarchy, instead, an inset shadow (like I mentioned before) would be better in my opinion. 

PS - the File Explorer w/ the inset shadow wasn't just on the concept, it is also currently present in the new app in Windows 10X

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/77712755-1d4e8f80-6fab-11ea-8d28-0d50206d5b80.png)

Let me know what you think. Personally I think it looks kind of crowded gives the appearance of too many layers.

**Comment by carmellolb** [comment]
> ![image](https://user-images.githubusercontent.com/39923744/77712755-1d4e8f80-6fab-11ea-8d28-0d50206d5b80.png)
> 
> Let me know what you think. Personally I think it looks kind of crowded gives the appearance of too many layers.

I strongly disagree, I think this is perfect! This is what Microsoft seems to be going for in their concepts, and it’s no wonder. It provides visual hierarchy, because users’ attention should be drawn to the main content and using this kind of shadow in this manner does just that. It makes it appear as if it is recessed, which is ideal. In my opinion, this is perfect.

**Comment by duke7553** [comment]
@carmellolb Is there anything else about the Windows 10X design that would add value to the app? Also, is there anything about our current design which seems redundant or poorly designed? Which design is better?

**Comment by yaichenbaum** [comment]
Changes will roll out with v0.7.3 to address this issue.
