### ISSUE TITLE
Add more leading (vertical line space) between items on the sidebar

### ISSUE THREAD

**Issue by carmellolb** [duke7553/files-uwp#467]
The current sidebar looks very cramped with the items so close together.

The older version of Files UWP had more space between the items.

**Comment by yaichenbaum** [comment]
I personally like the compact view, even in the compact view, the items in the list are about 20% bigger than the sidebar items in File Explorer.
I am marking this as a discussion so we can get other users feedback on this area.

**Comment by yaichenbaum** [comment]
This will be addressed when v0.7.3 rolls out.
