### ISSUE TITLE
WIN + E keyboard combination to open files-uwp

### ISSUE THREAD

**Issue by Ryan-Efendy** [duke7553/files-uwp#468]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Shortcut/hotkey pressing WIN + E open files-uwp vs. files explorer

**Comment by yaichenbaum** [comment]
You can already do this with existing keyboard remapping software, but I will see if there is an easier way to get this set up 🙂

**Comment by yaichenbaum** [comment]
Everything I found points to a piece of software called AutoHotKey, I recommend checking it out to see if it can do what you are interested in.

**Comment by Pandaver** [comment]
1. Create a backup of the registry.
2. Open the registry editor.
3. Navigate to `Computer\HKEY_CLASSES_ROOT\Folder\shell\opennewwindow\command`
4. Set the default keys value to `C:\Users\!YOURUSERNAME!\AppData\Local\Microsoft\WindowsApps\files.exe -Directory %1`
5. Delete the DelegateExecute key

**Comment by skyduy** [comment]
You can do this by compiling this script with AutoHotKey:
```ahk
#e::

    ; If there is no explorer already running
    IfWinNotExist, Files
    {
        ; Start FilesUWP
        Run %USERPROFILE%\AppData\Local\Microsoft\WindowsApps\files.exe
        ; Wait for it ...
        WinWait Files
        ; Set focus
        WinActivate
    }

    ; If explorer is already running
    Else{
        ; Set focus
        WinActivate
        ; Send CTRL + t shortcut to open a new tab
        ; ^ = CTRL
        SendInput ^t
    }

return
```

**Comment by VampireMonkey** [comment]
For anybody interested here's a Autohotkey snippet that will open folders with Files:

```
; Opens the specified folder in the Files explorer program
OpenWithFiles(Folder)
{
	Run "shell:AppsFolder\Files_1y0xx7n9077q4!App:" %Folder%
}
Return

#E::OpenWithFiles("F:\")
```

If files is already opened, a new tab will automatically be created with your folder.
