### ISSUE TITLE
RecentItemOpenFileLocation.Text is interchanged with RecentItemDescription.Text 

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#470]
![image](https://user-images.githubusercontent.com/17484252/77155135-61b6c880-6a9d-11ea-974b-4d2d3808b8d9.png)

**Comment by yaichenbaum** [comment]
Thank you for reporting this issue.

**Comment by yaichenbaum** [comment]
Is this still an issue in v0.7.4?

**Comment by R3voA3** [comment]
Seems to be fixed

**Comment by yaichenbaum** [comment]
@R3voA3 Thank you for letting us know.
