### ISSUE TITLE
Strange animation when clicking on items on the sidebar in v0.7.2

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#472]
There is a strange animation when clicking on items in the sidebar, this only affects the first tab that is loaded.
The animation issue is because we are using a WinUI pre-release. It should be fixed with a future WinUI update.

**Comment by Spyromaniac31** [comment]
I have the same issue. Windows Insider build 19587.
[Files UWP - Preview 2020-03-23 16-56-49.zip](https://github.com/duke7553/files-uwp/files/4372277/Files.UWP.-.Preview.2020-03-23.16-56-49.zip)
 Here is a video:

**Comment by yaichenbaum** [comment]
This is a known issue due to using a pre-release for WinUI, we decided to go through with v0.7.2 even though it has this issue since it contained many bug fixes. This issue should be fixed with a future WinUI release.

**Comment by yaichenbaum** [comment]
Changes that address this will roll out with v0.7.3.
