### ISSUE TITLE
App crashes upon opening

### ISSUE THREAD

**Issue by Spyromaniac31** [duke7553/files-uwp#475]
**Describe the bug**
The app crashes within seconds of being opened, regardless of where I open it from. For those split-seconds that it is opened, the mouse cursor has the blue wheel next to it.

**To Reproduce**
1. Open Files UWP from the Start Menu or Search.
2. The app hangs for a little and then crashes

**Expected behavior**
The app opens and remains open during use.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 Insider Build 19587.1000
 - App version: v0.7.1.0

**Additional context**
Using the Microsoft Store version of the app

**Comment by duke7553** [comment]
@Spyromaniac31 This will be fixed in v0.7.2 which is in certification now.
