### ISSUE TITLE
Application does not launch at all! HELP

### ISSUE THREAD

**Issue by Uxusk1** [duke7553/files-uwp#476]
**Describe the bug**
I installed it from the MS Store, but when done I launch opens and immediately crashes!

**To Reproduce**
1. Go to 'Microsoft Store'
2. Click on 'Get, Install'
3. Click on 'Windows Key'
4. Find 'Files UWP BETA'
5. Open the application

**Expected behavior**
Expected to launch and let me browse through my files, but didn't

**Screenshots**
No Screenshots since it doesn't open at all!

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903, Build 18362.535
 - App version: Latest

**Additional context**
not building from source code, directly from Microsoft Store, want to test out looks beautiful!

**Comment by duke7553** [comment]
@Uxusk1 Hello there. This is fixed already and will come soon, as the update is in certification.

**Comment by duke7553** [comment]
FYI, building from source code will include the fix, if you don't want to wait.
