### ISSUE TITLE
Enter key should open the file or folder

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#48]
- Pressing the enter key should open the file or folder selected
- if multiple files are selected open all of them
- if multiple folders are selected open all the folders in new windows

**Comment by duke7553** [comment]
Moved to https://github.com/duke7553/files-uwp/issues/9

**Comment by szaimen** [comment]
When will this be added?
Sry don't want to spam https://github.com/duke7553/files-uwp/issues/9.
I think this feature is quite essential.

**Comment by yaichenbaum** [comment]
@szaimen Thanks for keeping this issue active! I just added it to the list of things to do, I hope we can get this done fairly soon. @jeffsieu is this something you would be interested in working on?

**Comment by jeffsieu** [comment]
@yaichenbaum Sure! I think it'll be best to work on it on top of the sort and rename commits, as the enter key may interfere with the renaming process. When will the sort and rename branches be merged into master?

**Comment by yaichenbaum** [comment]
As soon as @duke7553 reviews them.

**Comment by szaimen** [comment]
> Multi-selection
> Open files in respective applications
> Open folders in a new tab each

Maybe shift+enter could open the folders in new windows each?

**Comment by yaichenbaum** [comment]
@szaimen As opposed to a new tab?

**Comment by szaimen** [comment]
Yes 👍

**Comment by yaichenbaum** [comment]
@duke7553 would it make sense for this to add this behavior?
