### ISSUE TITLE
A severe experiencing bug in the sidebar

### ISSUE THREAD

**Issue by ACoderWu** [duke7553/files-uwp#484]
**Describe the bug**
The experience is greatly affected by the fact that each click flashes as me switch directories in the sidebar

**To Reproduce**
1. Go to 'new table'
2. Click on 'any directory in the sidebar'
3. See error

**Expected behavior**
Toggle the effect normally

**Screenshots**
https://ae04.alicdn.com/kf/Haa5b0f0d82514b6abac9441a5eaeca256.png

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363.657]
 - App version: [v0.7.2.0]

**Additional context**
Download in the Microsoft store

**Comment by yaichenbaum** [comment]
This was a known issue before we shipped v0.7.2. It is due to the specific version of WinUI we are using, but we decided to go through with it anyways since v0.7.2 included many other bug fixes. We are tracking this issue in #472.
