### ISSUE TITLE
New Folder creation looses focus with each letter

### ISSUE THREAD

**Issue by ewandalen** [duke7553/files-uwp#486]
**Describe the bug**
The text box in the Create new folder dialog keeps losing focus after every character is typed.

**To Reproduce**
1. Open the app
2. Select any folder and right click
3. Select 'New', then select 'Folder'
4. Start typing the folder name.
5. The textbox will lose focus and you have to click on it again to type the next character.

**Expected behavior**
We should be able to type the complete folder name completely withou the field losing focus.

**Screenshots**
Video: https://1drv.ms/v/s!AqsGAQzCgk9kr7Ux6DQyxLppkCKpww

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro Insider Preview 2004 Build 19592.1001
 - App version: [0.7.2.0]

**Additional context**
Happens always when trying to create a folder

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, I think by implementing inline editing for this functionality, it will not only fix the issue but it will improve the experience as well.
