### ISSUE TITLE
right clicking in blank area

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#49]
right clicking on a blank area should have a few options such as

- [x] new items
- [x] open powershell (maybe only for users who will choose a setting for advanced options)
- [x] open properties for the directory

**Comment by duke7553** [comment]
Right click menu is now added.

**Comment by Henboy10** [comment]
It does not appear that we can create new files as we can on the default file explorer.
![image](https://user-images.githubusercontent.com/22181579/62741242-d9991c80-b9ff-11e9-9b3e-e1047511aa88.png)

**Comment by yaichenbaum** [comment]
This has been added to master.

**Comment by jeffsieu** [comment]
I'll work on this

**Comment by yaichenbaum** [comment]
Thank you @jeffsieu for your amazing work on this!

**Comment by yaichenbaum** [comment]
You can download v0.7.0 [here](https://github.com/duke7553/files-uwp/releases/tag/v0.7.0).
