### ISSUE TITLE
[Feature Request] Add hash value in file properties

### ISSUE THREAD

**Issue by xpirad** [duke7553/files-uwp#491]
File uwp is very good but i think it's missing one feature, that is displaying hash value of files
![image](https://user-images.githubusercontent.com/24430064/78194541-0bd81c80-74b0-11ea-9140-b29fc5fbc799.png)

In windows explorer, this can be achieved by installing an extension called hashtab
![image](https://user-images.githubusercontent.com/24430064/78194590-2e6a3580-74b0-11ea-8a8a-d26e440e58f1.png)

I wonder if this feature can be added to files uwp as well. Could be really useful.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. This feature would definitely come in handy, it shouldn't be so hard to add this since there are APIs already built into C# for this.

**Comment by xpirad** [comment]
Thanks! That would be nice!

**Comment by yaichenbaum** [comment]
This has been implemented with 60147862cb5c9ef780fb6b25924b957dd10042c4. These changes will roll out when v0.7.6 is released.
