### ISSUE TITLE
[Bug Report] files-uwp crash when entering  "py" in address bar

### ISSUE THREAD

**Issue by xpirad** [duke7553/files-uwp#492]
Demonstration:
![image](https://user-images.githubusercontent.com/24430064/78194837-c6681f00-74b0-11ea-8f71-a37e4c170423.png)

I don't know why, but it doesn't crash every single time, just from time to time

Expected behavior:
Start python in the current directory
![image](https://user-images.githubusercontent.com/24430064/78194963-18a94000-74b1-11ea-81c4-0cda04bcb753.png)

**Comment by yaichenbaum** [comment]
Did you try adding a profile for python? We currently do not support opening terminal shells from the address bar but you can add a terminal profile that will let you right-click in the directory and open the default terminal from there.

**Comment by xpirad** [comment]
Thanks for the info, i will try that!

**Comment by xpirad** [comment]
@yair100 although, i think there should be some error-handling to prevent the crash. You know, in case user put in some strange stuff in the address bar

**Comment by yaichenbaum** [comment]
There actually is error handling, that is why that message comes up. I am not sure why it is sometimes crashing.

**Comment by xpirad** [comment]
yeah, i guess that's weird. It crashed 2 out of 5 times in my test
