### ISSUE TITLE
Delete file command is triggered when renaming files

### ISSUE THREAD

**Issue by GavinYou082** [duke7553/files-uwp#493]
**Describe the bug**
When renaming a file, deleting letters in the file name triggers the Delete File command with the confirmation dialog popped up.

**To Reproduce**
1. Select a file
2. Click on the file name to rename the file
3. Press 'Delete' in the TextBox showing the file name
4. Delete confirmation dialog is shown

**Expected behavior**
Delete command should be disabled when editing a file name.

**Screenshots**
![Snipaste_2020-04-02_22-52-51](https://user-images.githubusercontent.com/38808970/78263602-c0b41d00-7534-11ea-8531-1fa20d2ad01f.png)
![Snipaste_2020-04-02_22-53-04](https://user-images.githubusercontent.com/38808970/78263606-c1e54a00-7534-11ea-98c5-9643e3bb2fe8.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.720]
 - App version: [v0.7.2.0]

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by yaichenbaum** [comment]
This has been fixed with dd118dcc066031bfeb13682a86c1b1fc82ee974f and will roll out with the v0.7.3 release.
