### ISSUE TITLE
鼠标无法划选多个文件、文件夹

### ISSUE THREAD

**Issue by Bdeciduous** [duke7553/files-uwp#494]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
We are tracking a selection rectangle in #94.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. We are tracking a selection rectangle in #94.
