### ISSUE TITLE
Icon Layout is not working

### ISSUE THREAD

**Issue by bhupathi189** [duke7553/files-uwp#496]
**Describe the bug**
Icon Layout is not working. Whatever the layout model is we chose, items are still in list layout only. 

**To Reproduce**
1. Go to 'View'
2. Click on 'Layout Mode'
3. Scroll down to 'Icons'
4. See error (the files don't change into icons mode)

**Expected behavior**
The files must change into icons from list layout.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.752]
 - App version: [v0.7.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. Layout modes is not yet implemented. We are tracking this issue in #214.
