### ISSUE TITLE
Fluent Terminal Support?

### ISSUE THREAD

**Issue by EmiyaBestBoy** [duke7553/files-uwp#499]
I know you added open in terminal support but you could explain to me how I could possibly add Fluent Terminal as an option? Fluent Terminal is a UWP app just like this one. I don't know what path or argument I should put.

**Comment by yaichenbaum** [comment]
cc @lampenlampen

**Comment by lampenlampen** [comment]
According to https://github.com/felixse/FluentTerminal/pull/194:

``` json
{
      "id": 5,
      "name": "Fluent Terminal",
      "path": "flute.exe",
      "arguments": "new \"{0\}",
      "icon": ""
}
```

**Comment by lampenlampen** [comment]
@EmiyaBestBoy does it work?

**Comment by lampenlampen** [comment]
It works. Tested it.

**Comment by yaichenbaum** [comment]
@lampenlampen Thank you for testing.
@EmiyaBestBoy I hope your issue has been resolved, feel free to reopen this issue or open a new one if you run into additional issues or if you have feedback for Files UWP.
