### ISSUE TITLE
No access to Windows Drive

### ISSUE THREAD

**Issue by konsyr11** [duke7553/files-uwp#504]
**Describe the bug**
The explorer will not show drive C:\ in the drives list, the related option in Settings is grayed out, and trying to type the path manually returns an "Access Denied" error.

**To Reproduce**
1. Go to Files UWP
2. Click on the path bar
3. Type "C:\" and press Enter

**Expected behavior**
Drive C:\ opens up and I can see the files.

**Screenshots**
C:\ will not appear:
![image](https://user-images.githubusercontent.com/28728855/78453160-9bd8ba80-7698-11ea-82ee-bb5c4dd52e78.png)
Option grayed out:
![image](https://user-images.githubusercontent.com/28728855/78453177-b1e67b00-7698-11ea-8d78-762a0e3aaaaf.png)
Access Denied Error:
![image](https://user-images.githubusercontent.com/28728855/78453190-c165c400-7698-11ea-84e2-1a3b4cb99195.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1809 17763.1098]
 - App version: v0.7.2.0

**Additional context**
The problem is persistent, the only thing I have not attempted is restarting the machine.

**Comment by konsyr11** [comment]
Let me also add that I am the computer administrator, and the computer does not belong in a domain/network, so no special security policies apply.

**Comment by yaichenbaum** [comment]
Have you given Files UWP access to the file system on your device?

**Comment by duke7553** [comment]
@konsyr11

**Comment by konsyr11** [comment]
Yea that was the stupid error. Great job :)
