### ISSUE TITLE
0.7.3 Issues

### ISSUE THREAD

**Issue by Crocodile73** [duke7553/files-uwp#511]
Quick look round, looks ok, are preferences in settings, supposed to work? The app crashes when i select it.

**Comment by yaichenbaum** [comment]
We have a fix coming for the crash, were you able to get v0.7.3 from the store?

**Comment by duke7553** [comment]
And whatever you do, don't try to press TAB in the app because a fix is on the way for the Tab Focus bug also.

**Comment by Crocodile73** [comment]
@yair100 no i cloned it from the source file

**Comment by yaichenbaum** [comment]
Thanks for letting me know, there was an issue with the pipeline that caused it to not upload the release so v0.7.3 isn't actually in the store yet.

**Comment by Crocodile73** [comment]
> Thanks for letting me know, there was an issue with the pipeline that caused it to not upload the release so v0.7.3 isn't actually in the store yet.

i cloned 0.7.4 and preferences works ok now.

**Comment by yaichenbaum** [comment]
@Crocodile73 Great! Make sure to open issues if you have any other issues or feedback.
