### ISSUE TITLE
right-clicking on an item in a folder crashes files uwp when not selecting the item first 

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#532]
**Describe the bug**
right-clicking on an item in a folder crashes files uwp when not selecting the item first

**To Reproduce**
1. Open a folder
2. right-click on an item without selecting the item first
3. Crash

**Expected behavior**
Shouldn't crash but instead show the context menu of that item

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: 0.7.3

**Comment by duke7553** [comment]
@szaimen Thanks for reporting this. We have found the root cause and have prepared a fix for the next release.
