### ISSUE TITLE
When clicking enter in the navigation bar, it should get closed automatically

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#535]
**Is your feature request related to a problem? Please describe.**
When clicking enter in the navigation bar, it should get closed automatically.

**Describe the solution you'd like**
when typing a path into the navigation bar and pressing enter, the new directory gets opened but I think it would be better to directly escaping the navigation bar like it is in the file explorer (would also look better)

**Comment by yaichenbaum** [comment]
This has been fixed with v0.7.5.
