### ISSUE TITLE
add colourful icons instead of monocolor icons

### ISSUE THREAD

**Issue by bhupathi189** [duke7553/files-uwp#545]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
The issue I have with doing this is that we are using the MDL2 Assets which are part of the fluent design system. However, Fluent is shifting towards colorful icons and there is the chance the MDL2 icons will shift to more colorful icons as well.
It will also be interesting to see how the File Explorer on Windows 10X does this.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, there are no plans to change the icon design as we want to continue using the MDL2 Assets, if the assets are updated to include colored icons, we will be one of the first to start using them.
