### ISSUE TITLE
bug with creating a new folder

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#546]
**Describe the bug**
bug with creating a new folder: the input box where you can enter the new folder name seems to get unfocussed after aftere character, which is a bit annoying

BTW: clicking on "cancel" seems to create a new folder with default name nonetheless...

**To Reproduce**
1. create a new folder
2. try to enter the foldername
3. unfocus the inputbox after every character which does make this process a bit annoying; shortcus don't seem to work either.

**Expected behavior**
inputbox should stay in focus;
clicking on cancel should abort the folder creation process

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: 0.7.5

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, we are tracking this same issue in #486. Make sure to subscribe to that issue to get updated when it's fixed.
