### ISSUE TITLE
copying an empty folder into itself seems to create an infinity amount of empty folder in itself

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#547]
**Describe the bug**
copying an empty folder into itself seems to create an infinity amount of empty folder in itself

**To Reproduce**
1. copy an empty folder
2. open this folder
3. paste the folder from the clipboard
4. files uwp crashes

**Expected behavior**
files uwp shouldn*t crash, instead there should be only one copy of the folder in this folder and not an infinity amount

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: 0.7.5

**Comment by yaichenbaum** [comment]
This has been fixed with 0ace5ecc98cab6b5c0fdc4d80c7c7ba7ee078dfc. These changes should roll out when v0.7.6 is released.
