### ISSUE TITLE
when updating files uwp over the store, it gets forced-closed and asks after a new opening for sending a crash-report

### ISSUE THREAD

**Issue by szaimen** [duke7553/files-uwp#548]
**Describe the bug**
when updating files uwp over the store, it gets forced-closed and asks after a new opening for sending a crash-report

**To Reproduce**
1. open the app
2. update the app over the store -> gets force-closed
3. app gets automatically opened again and asks for sending a crash-report

**Expected behavior**
shouldn*t ask for sending a crash-report since the update was expected

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: 0.7.5

**Comment by yaichenbaum** [comment]
What is asking for the crash report, Files UWP or Windows?

**Comment by szaimen** [comment]
I think it was files uwp but is a bit hard to replicate. Will try to reproduce on the next update and make a screenshot ;)

**Comment by yaichenbaum** [comment]
You can try to force crash the app and see if a message comes up when opening it again. As far as I know Files UWP doesn't have a message come up after crashing, but it could be I missed it.

**Comment by szaimen** [comment]
hm... when doing that through the task manager and opening again no message appears. So I think this has to get tested when the new update arrives...

**Comment by szaimen** [comment]
But actually this is so a rare case, that I don't think it is important to get fixed...
So I would say you can close this issue if you like.

**Comment by yaichenbaum** [comment]
Technically when the store closes the app it is considered a crash, if a dialog does come up, I wounder if there is a way to detect how the app was closed and stop showing it in this case.

**Comment by szaimen** [comment]
I had it open today and updated again and there was no popup window with a crash report. So I would say this issue is fixed.
