### ISSUE TITLE
Concept design V2 - Different icons and a few more things

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#552]
This time the font size of the sidebar is the original, I just changed the icons, replaced "Home" with "This PC", added "Quick Access" and moved them a bit to the right leaving a little more space between the red bar and icons, also reduces the size of the navigation bar.

![Captura de pantalla (178)](https://user-images.githubusercontent.com/61259627/78794232-780bc200-7981-11ea-9086-113202eaefcf.jpg)

**Comment by SOI7** [comment]
It would be a gigantic task for the devs, but personally I wouldn't mind if we could choose between MDL2 icons and Shell32 icons

**Comment by szaimen** [comment]
I think I overall like the new porposal 👍
But maybe we should think about adding new designed colorful icons instead of the old Win10 legacy file explorer icons to the sidebar?
BTW: shouldn't e.g. the music icon then also be on top of the tab? Seems to me like a mistake...

**Comment by xPoppyx** [comment]
> BTW: shouldn't e.g. the music icon then also be on top of the tab? Seems to me like a mistake...
forgot to change it xd

**Comment by xPoppyx** [comment]
> But maybe we should think about adding new designed colorful icons instead of the old Win10 legacy file explorer icons to the sidebar?

in fact I was thinking of putting new icons instead of the old ones, I only used these because it was quicker to find them, anyway I also agree with putting the new icon designs

**Comment by szaimen** [comment]
> > But maybe we should think about adding new designed colorful icons instead of the old Win10 legacy file explorer icons to the sidebar?
> 
> in fact I was thinking of putting new icons instead of the old ones, I only used these because it was quicker to find them, anyway I also agree with putting the new icon designs

I think those would also fit better to the new designed app icons by microsoft for Windows 10 x...

**Comment by szaimen** [comment]
> It would be a gigantic task for the devs, but personally I wouldn't mind if we could choose between MDL2 icons and Shell32 icons

I wouldn't say this has to be an settings option: if I understand correctly this is a mockup how colorful icons would look like...

**Comment by yaichenbaum** [comment]
I like how you added the header, about the icons, the issue I have with it is that we are using the MDL2 Assets which are part of the fluent design system. However, Fluent is shifting towards colorful icons and there is the chance the MDL2 icons will shift to more colorful icons as well.
It will also be interesting to see how the File Explorer on Windows 10X does this.

**Comment by yaichenbaum** [comment]
Let's continue tacking this in #545.

**Comment by szaimen** [comment]
> Let's continue tacking this in #545.

What about the Quick access header? and other edits to the navigation bar?

**Comment by yaichenbaum** [comment]
The quick access header will be done in a future update.
