### ISSUE TITLE
Open in new tab causes temporary freezing

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#558]
**Describe the bug**
If I right-click on a folder and click "Open in new tab" it causes the program to either freeze, freeze then close or freeze and after a while manages to open it in the new tab but freezes again for a while afterwards. While this is happening it also spikes in CPU usage.

**To Reproduce**
1. Right-click on a folder
2. Click on "open in new tab" in the context menu
3. *freezing*

**Expected behavior**
The folder to open in a new tab without any real issues

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 1909 18363.657
 - App version: v0.7.5

**Comment by lukeblevins** [comment]
@yair100 Maybe he tried to open multiple items at once?

**Comment by duke7553** [comment]
@Darhagonable Just in case: the performance should be better on builds from the Store, so please try to stay on those unless you're prepared to deal with performance not being up to par.

**Comment by Darhagonable** [comment]
> Maybe he tried to open multiple items at once?

nope, only one folder.

> Just in case: the performance should be better on builds from the Store, so please try to stay on those unless you're prepared to deal with performance not being up to par.

Oh I might try that 🤔

**Comment by generalguy41** [comment]
I can reproduce this issue on the current store version as well.

**Comment by duke7553** [comment]
I did some work in v0.7.6 which should reduce the freezing. Once it is in the Store (currently in certification), you can test it out and let me know if it's any better

**Comment by Darhagonable** [comment]
> I did some work in v0.7.6 which should reduce the freezing. Once it is in the Store (currently in certification), you can test it out and let me know if it's any better

Just built from master branch and it seems to be fixed! 😃

**Comment by yaichenbaum** [comment]
@Darhagonable Thank you for the updated information 🎉
