### ISSUE TITLE
Clicking OneDrive tab puts marker on Local Drive

### ISSUE THREAD

**Issue by BlaT2512** [duke7553/files-uwp#559]
**Describe the bug**
When clicking on the OneDrive location on the sidebar, it opens OneDrive in the file viewer but the blue marker that indicated which folder is open on the sidebar goes onto Local Drive (C:). When clicking on the OneDrive location again, the marker correctly goes to OneDrive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a random folder
2. Click on OneDrive
3. See that the open location appears to be Local Drive (C:) but OneDrive folders are showing
4. Click on OneDrive again
5. See that the open location correctly appears to be OneDrive

**Expected behaviour**
When clicking on the OneDrive icon the first time, the marker goes to OneDrive.

**Screenshots**
[https://screenrec.com/share/s7ijSTL4Yz](https://screenrec.com/share/s7ijSTL4Yz)
Screen recording ^

**Desktop**
 - OS Version: Windows 10 2004 19041.172
 - App version: v0.7.5

**Additional context**
This problem always occurs while using the app

**Comment by GavinYou082** [comment]
![image](https://user-images.githubusercontent.com/38808970/78895577-ada7cc80-7aa1-11ea-8355-e9b67d20ae36.png)
Sometimes event two markers appear on the sidebar. It occurs randomly when navigating between tabs, at least I didn't find a certain way to reproduce this.

**Comment by yaichenbaum** [comment]
This issue has been resolved with #816.
