### ISSUE TITLE
Make path bar more visible

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#56]
Make it more noticeable that a file path bar exists.

**Comment by z0oinks** [comment]
Oh wow, I didn't even realize it was a filepath bar. Thought it was just the title of the folder!

**Comment by duke7553** [comment]
"Sometimes a surprise or two really makes the experience better, huh?"
In all seriousness, the new file path bar was designed to be an advanced feature of sorts. Invisible to users who may not need it. However, I do plan on adding a [TeachingTip](https://github.com/Microsoft/microsoft-ui-xaml/issues/21) for things like this when it's eventually released.

**Comment by SavoySchuler** [comment]
Hey, @duke7553, [TeachingTip is now available via prerelease](https://github.com/Microsoft/microsoft-ui-xaml/releases/tag/v2.1.190219001-prerelease) and the guidance is being drafted [here](https://github.com/Microsoft/microsoft-ui-xaml-specs/blob/user/savoyschuler/teachingtip/active/teachingtip/TeachingTipSpec.md). Let me know if you need any help hooking it up!

**Comment by duke7553** [comment]
@SavoySchuler Thanks. I was able to implement it as per the drafted docs, but ran into an exception which is reported here: https://github.com/Microsoft/microsoft-ui-xaml/issues/349 . I'm going to try to update from build 18342 to 18343 to see if there were any changes that fix it.

**Comment by duke7553** [comment]
The next pre-release will change the look of the path bar, improving the visibility.
