### ISSUE TITLE
when the settings tab is opened, the tabs on the top are shifting towards complete left. So, when we switch between normal tab and setting tab, tabs on top are shifting. this irritates me a little bit becuase the tabs are not present where i expected them to be. 

### ISSUE THREAD

**Issue by bhupathi189** [duke7553/files-uwp#560]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by szaimen** [comment]
This could get solved by opening the settings tab always on the left: 
![image](https://user-images.githubusercontent.com/42591237/78883761-3a2e9c80-7a5a-11ea-8103-68dcecef68fb.png)
And don't show the settings tab when returning to a normal tab. (so that you would have to click on the settings button again to go into settings again. (Maybe you could remember the state of the settings tab nonetheless...)

**Comment by Darhagonable** [comment]
IMO it should look more like this:
![Files UWP settings mockup](https://user-images.githubusercontent.com/14127357/78892360-86350d80-7a69-11ea-94a0-eef42ad93521.png)

**Comment by szaimen** [comment]
> IMO it should look more like this:
> ![Files UWP settings mockup](https://user-images.githubusercontent.com/14127357/78892360-86350d80-7a69-11ea-94a0-eef42ad93521.png)

Yes, that would look better but wouldn't solve the reported problem of moving tabs...

**Comment by Darhagonable** [comment]
> Yes, that would look better but wouldn't solve the reported problem of moving tabs...
Yes it would. The tabs wouldn't be shifting in any way.

**Comment by bhupathi189** [comment]
yes, wherever the setting tab is whole tabs are shifting towards left

**Comment by xPoppyx** [comment]
what if it appears as a popup?

![Anotación 2020-04-09 101353](https://user-images.githubusercontent.com/61259627/78905433-fcc31280-7a4b-11ea-9a0c-fcb500490faf.jpg)

**Comment by szaimen** [comment]
> what if it appears as a popup?
> 
> ![Anotación 2020-04-09 101353](https://user-images.githubusercontent.com/61259627/78905626-4b70ac80-7a4c-11ea-94b3-7b3c166ec48e.jpg)

I would be okay with that 👍
Maybe to make it easier for the developers just open this in a new window?

**Comment by xPoppyx** [comment]
maybe it is not difficult to put it in a popup, better wait for them to respond to see what they say about it

**Comment by generalguy41** [comment]
Alternatively, couldn't it just open at the end like a new tab typically would (see: Microsoft Edge)? That way it just acts as a normal tab, and doesn't move any of the others around.

**Comment by Darhagonable** [comment]
> Alternatively, couldn't it just open at the end like a new tab typically would (see: Microsoft Edge)? That way it just acts as a normal tab, and doesn't move any of the others around.

Like my concept? Just that mine changes the options in the side menu too.

**Comment by szaimen** [comment]
> > Alternatively, couldn't it just open at the end like a new tab typically would (see: Microsoft Edge)? That way it just acts as a normal tab, and doesn't move any of the others around.
> 
> Like my concept? Just that mine changes the options in the side menu too.

Yes, I think your concept with opening the tab at the end of the list would also work👍

**Comment by bhupathi189** [comment]
i would be much better

**Comment by duke7553** [comment]
Hello there. I've felt for a long time that Settings should be a separate experience from the instance tabs, and understand that our current solution (shifting the tabs over) is not a very good one. 

We've seen success with AppWindow for the Properties dialog, so that looks like what we'll do, but I'm going to leave this open for more feedback.

**Comment by xPoppyx** [comment]
mmm it is unlikely that more people than us will come to give their opinion on this

**Comment by tsvietOK** [comment]
What do you think about moving all controls under their captions like all other Windows apps settings?
![image](https://user-images.githubusercontent.com/20501502/79021401-11a2c180-7b84-11ea-8391-8879be878750.png)

**Comment by yaichenbaum** [comment]
I just want to mention that most users are not opening the settings page on a day to day basis. That being said I think it is extremely important to have a good experience for those few times. A simple way to solve this would be to extend the settings sidebar into the title bar.

**Comment by R3voA3** [comment]
In my opinion I think the navigation bar of the settings pages should be identical (visually) with the default navigation bar. There shouldn't be  a harsh translation.

**Comment by yaichenbaum** [comment]
@R3voA3 #582 includes some changes to address this issue that are inspired by the link you shared.
