### ISSUE TITLE
The app takes too long to open

### ISSUE THREAD

**Issue by MarcAnt01** [duke7553/files-uwp#561]
**Describe the bug**
The first time I open Files Uwp it takes 3/4 secs (Windows automatically disables splash screen, since I have good hardware and their opening is instanteous) 

**To Reproduce**
Open the app

**Expected behavior**
Take less than 2 seconds

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175] Windows 10 Pro 1909
 - App version: [v0.5.0] 0.7.1.0

**Additional context**
None

**Comment by duke7553** [comment]
Hello @MarcAnt01 Please make sure that you're running the latest version of the app, v0.7.5 from the Store.

**Comment by MarcAnt01** [comment]
> Hello @MarcAnt01 Please make sure that you're running the latest version of the app, v0.7.5 from the Store.

Sorry, I installed the version you sent me on Discord some weeks ago for testing it and I have just noticed that it doesn't update automatically from the Store.

**Comment by MarcAnt01** [comment]
Looks fixed now👍
