### ISSUE TITLE
Drives disappear from side menu

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#563]
**Describe the bug**
Sometimes when starting the Files UWP app the the drives section of the side menu is missing.

**To Reproduce**
Not sure. It just happens sometimes when i start the program. Is there anything i could do to test it further?

**Expected behavior**
The section with the drives to exist in the side menu.

**Screenshots**

**Desktop:**
 - OS Version: Windows 10 1909 18363.657
 - App version: v0.7.5

**Additional context**
![image](https://user-images.githubusercontent.com/14127357/78938503-a1783b00-7ab2-11ea-8a32-5d0e892088df.png)

**Comment by duke7553** [comment]
@Darhagonable Yes! Could you please paste your log file? You can get it by going to the folder %localappdata%/Packages, search there for the folder Files and there in the folder LocalState should be a file debug.txt, which contains a stacktrace.

**Comment by Darhagonable** [comment]
I don't seem to have any Files folder that updated recently. I built it myself in VS and didn't install it through MS Store if that could be why?
I don't know much about VS but maybe there's a log in there?

**Comment by tsvietOK** [comment]
@duke7553 Log file is not useful.
Start with disks loaded
`2020-04-11 04:09:09.1492|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed
2020-04-11 04:09:09.2066|INFO|Files.Filesystem.DrivesManager|Drive added: S:\, Fixed
2020-04-11 04:09:09.2273|INFO|Files.Filesystem.DrivesManager|Drive added: V:\, Fixed
2020-04-11 04:09:09.2471|INFO|Files.App|App launched`

Start without disks loaded
`2020-04-11 04:09:13.1606|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed
2020-04-11 04:09:13.2205|INFO|Files.Filesystem.DrivesManager|Drive added: S:\, Fixed
2020-04-11 04:09:13.2400|INFO|Files.Filesystem.DrivesManager|Drive added: V:\, Fixed
2020-04-11 04:09:13.4978|INFO|Files.App|App launched`

**Comment by Darhagonable** [comment]
I seem to be able to temporarily fix it by doing this:
- Turning off access to the file system for the app while it's running.
- Start Files UWP again.
- Turning on access to the file system for the app while it's running.
- Start Files UWP again.
- Close it.
- Start it again and it's fixed

**Comment by yaichenbaum** [comment]
I have seen this behavior a few times. Restarting the app shows the drives again.

**Comment by Darhagonable** [comment]
> Restarting the app shows the drives again.

Not for me. I have to do my trick or if I'm lucky it will be fixed later when i start it. Simply restarting the app does not fix it for me.

**Comment by yaichenbaum** [comment]
Is this still an issue with the latest v0.8.2 release?

**Comment by Darhagonable** [comment]
@yair100 It seems to be fixed now :D
