### ISSUE TITLE
switch ci to build debug mode

### ISSUE THREAD

**Issue by lampenlampen** [duke7553/files-uwp#566]
Consider changing the ci pipeline to build the app in debug mode.

I for myself could lower the build time from 17 min to 2,5 min with this change.

Especially for the `develop`-branch, i think a release build is not necessary.

I think for the `develop`-branch, we can also skip the appx-package creation.

**Comment by lampenlampen** [comment]
So i tested it with this repo and i have a build time of 7 min ([see](https://dev.azure.com/lampenlampen/Files-UWP/_build)).

**Comment by lukeblevins** [comment]
@lampenlampen Thanks for this testing. I think I'll wait for @yair100 to review this one.

**Comment by yaichenbaum** [comment]
I specifically use the release build since many issues have come up in release mode that are not in debug mode, that we don't catch until we are ready for a release.
