### ISSUE TITLE
Has issues noticing some files.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [duke7553/files-uwp#57]
![image](https://user-images.githubusercontent.com/13170204/53031203-aae8b300-346c-11e9-82c6-ed543f0937a2.png)
As you can see, while comparing with the Windows 10 WM explorer, the classical explorer (With Clover Hooked) and the current version of Files v0.4.8, He is unable to found certain files. Refreshing wouldn't fix that.
The real fix I've found for the moment, is to make a change from that folder (Add/Rename/Remove a file etc...)

~~(Btw, You can see that the file address is overlapping a bit too much, Might think of make it resize itself automatically, or to have a horizontal scroll)~~

**Comment by duke7553** [comment]
@PoorPocketsMcNewHold There is actually a horizontal scroll for the Path Bar. Files can't discover hidden items, so was the missing item marked as hidden?

**Comment by PoorPocketsMcNewHold** [comment]
Indeed, I should have taken more a look at the path bar.
 However, I can confirm that this file isn't, and wasn't hidden.

**Comment by duke7553** [comment]
@PoorPocketsMcNewHold It may be because the file is NTFS compressed.

**Comment by PoorPocketsMcNewHold** [comment]
I since ain’t using Windows 10 anymore (And tho, logically your app) so I can’t still test it out, but if by ¨Compressed¨ you mean the option that you had when right clicking on a Hard Drive properties, and have to compress its files, then yeah. I can confirm it was NTFS compressed. (I can confirm the NTFS part for sure anyway)

**Comment by duke7553** [comment]
After doing some research, I determined the Windows.Storage APIs can't display hidden or compressed items. I'll have to close this now.

**Comment by yaira2** [comment]
@PoorPocketsMcNewHold support for hidden and compressed items is available in the latest version of Files. You can download Files from our website https://files.community/download.
