### ISSUE TITLE
Update .net framework version for launcher project

### ISSUE THREAD

**Issue by lampenlampen** [duke7553/files-uwp#570]
Is there any reason, why the launcher project references .net 4.6.1?

**Comment by duke7553** [comment]
The initial reason was to stay at the version of .NET Framework that ships with Windows, but I'm not against any of the following:
- Upgrading it
- Converting it to a C++ Project
- Moving to .NET Core as long as everything works

**Comment by yaichenbaum** [comment]
I recall that we had previously moved the Launcher project to .NET Core, but had to revert afterwards because it caused an issue. I think it caused an issue with launching applications but I don't remember if that was the only issue.

**Comment by lampenlampen** [comment]
On my machine .net 4.6.1 is not installed, so every time i upgrade to the latest (4.8 i think) and discard this change before pushing.

**Comment by yaichenbaum** [comment]
This has been addressed with #588.
