### ISSUE TITLE
[Minor] Acrylic sidebar doesn't update for already opened tabs

### ISSUE THREAD

**Issue by jeffsieu** [duke7553/files-uwp#575]
**Describe the bug**
When the acrylic sidebar option is toggled, existing tabs' sidebars do not update.

**To Reproduce**
1. Open a new tab
![image](https://user-images.githubusercontent.com/8487294/79065936-a1608100-7ce6-11ea-9114-6eaf018d41c0.png)
2. Go to Settings and toggle the acrylic sidebar option
![image](https://user-images.githubusercontent.com/8487294/79065958-b3daba80-7ce6-11ea-87d6-ba7f6d63c611.png)
3. Go back to the previously opened tab and see that its sidebar is the same as before
![image](https://user-images.githubusercontent.com/8487294/79065963-bdfcb900-7ce6-11ea-8eeb-fe9a0b1061bc.png)
4. Newly opened tabs will have the correct sidebar
![image](https://user-images.githubusercontent.com/8487294/79065965-c523c700-7ce6-11ea-90cf-5622f3de913a.png)

**Expected behavior**
Existing tabs' sidebars should update whenever the acrylic sidebar option is toggled

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.657
 - App version: v0.7.5

**Comment by yaichenbaum** [comment]
Another issue is that the tabs don't update until the app is restarted, so this results in a weird situation where some of the app has acrylic and some of the app does not.

**Comment by yaichenbaum** [comment]
Merging this issue with #577.
