### ISSUE TITLE
Apply changes to theme settings without restarting the application

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#577]
It should display a message when changing theme mode or activating / deactivating the acrylic sidebar, saying that the changes will be applied the next time the app is opened or something like that

**Comment by yaichenbaum** [comment]
Better yet, we should actually apply the changes right away.

**Comment by xPoppyx** [comment]
perfect

**Comment by yaichenbaum** [comment]
- Turning on or off the acrylic sidebar setting should automatically apply for the sidebar and tabs.
- Changing the theme should work without restarting the app.

**Comment by tsvietOK** [comment]
@yaichenbaum Should the AcrylicSidebar parameter affect the properties window? I am currently working on theme change and acrylic mode on/off without app restart.

**Comment by duke7553** [comment]
@tsvietOK Most likely, yes. That setting should disable all background acrylic surfaces.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
