### ISSUE TITLE
New Folder creation looses focus with each letter

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#579]
**Describe the bug**
When I create a new folder and start typing its name, the popup keeps loosing focus and I have to click again on it after each letter

**To Reproduce**
Create a new folder and start typing the name. Doesn't matter if the folder is created through the toolbar or the right-click menu

**Expected behavior**
The focus should be kept on the popup, so that you can type the full name without issues

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: v0.7.5.0

**Comment by yaichenbaum** [comment]
We are planning on fixing this issue with the v0.7.7 release https://github.com/duke7553/files-uwp/issues/486.
