### ISSUE TITLE
Custom documents / download folder not found

### ISSUE THREAD

**Issue by xtprion** [duke7553/files-uwp#585]
**Describe the bug**
When using documents, download etc with custom location, file explorer can't find the path

**To Reproduce**
1. Change the location of download folder to custom folder
2. Open download on file explorer
3. File explorer say "did you delete the folder? The folder you've navigated to was not found

**Expected behavior**
File explorer could open custom location on documents, download, etc without problem

**Screenshots**
![image](https://user-images.githubusercontent.com/46372297/79084609-df998700-7d5e-11ea-9d53-0c7623b70d57.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H1 19592
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by duke7553** [comment]
@xtprion What app version is this?

**Comment by yaichenbaum** [comment]
@duke7553 @xtprion This issue should be fixed when v0.7.6 rolls out.
