### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by duke7553** [duke7553/files-uwp#593]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by zain24420043-design** [comment]
aoakya hal ha muje ap sa ek bat discuss krne ha to plz mare bat ko zara tor dhayan sa synaye g acuitally muje apne system ma window activate krne ha thk ha byut jo mre profile ha vo lcal ha irmre system ke jo main profile h os ka password ma bhol gya or na he vo reset ho raha ha to plz ap mre help kr dam mre liye ya awindow activate krna bohat zaroroe a g i hope ap mre bat ko samje ga muje ap ka reply ka wait rahe ga

**Comment by Josh65-2201** [comment]
@zain24420043-design Stop posting random messages here. it isn't the place for it
