### ISSUE TITLE
Auto-Refresh Directories

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#6]
Currently, making a change Windows Explorer will not reflect in Files until you manually refresh the directory.

**Comment by duke7553** [comment]
I still can't think of a good way to implement this without refreshing the entire thing.

**Comment by ashikns** [comment]
Take a look at https://msdn.microsoft.com/en-us/magazine/mt790201.aspx.

**Comment by duke7553** [comment]
@ashikns I've read that article, too. ;) However, the problem I currently have can be described as follows:
- StorageLibraryChange tracking is only for StorageLibraries, and I ideally want the refresh to apply to all directories
- The second option, the event that fires when a file is added or deleted would only apply to a subset of the files in a large directory because Files gathers StorageFiles/Folders in batches to reduce memory usage and keep the UI responsive. (See ItemViewModel.cs)

Thanks for your help!

**Comment by duke7553** [comment]
I may just have to bite the bullet, and implement a separate query of the entire current folder in order to fire when one is added or deleted.

**Comment by ashikns** [comment]
Initially I thought it applied to only Library folders, but seems that it can be applied to any folder with [StorageFileQueryResult](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.storagefilequeryresult.contentschanged). Not sure though I'll take a look tonight (I live half way across the world so :)).

ItemViewModel is the root of what you are displaying in the UI correct? And a new ItemViewModel is created whenever navigation is done so it is enough to refresh only the subset that an ItemViewModel represents since that is all that is visible in the UI.

**Comment by duke7553** [comment]
@ashikns True, but which part of ItemViewModel has the ContentsChangedEvent? Because the query only holds 250 items at a time. Thus, the event would only fire for the 250 items it holds at once.
the step value is always 250, and the index initially starts from 0, then 250, 500,750, etc.
```
IReadOnlyList<StorageFolder> folders = await folderQueryResult.GetFoldersAsync(index, step);
int foldersCountSnapshot = folders.Count;
while (folders.Count != 0)
 {
       foreach (StorageFolder folder in folders)
       {
                        if (token.IsCancellationRequested)
                        {
                            return;
                        }

                        gotFolName = folder.Name.ToString();
                        gotFolDate = folder.DateCreated.ToString();
                        gotFolPath = folder.Path.ToString();
                        gotFolType = "Folder";
                        gotFolImg = Visibility.Visible;
                        gotFileImgVis = Visibility.Collapsed;
                        gotEmptyImgVis = Visibility.Collapsed;


                        if (pageName == "ClassicModePage")
                        {
                            ClassicFolderList.Add(new Classic_ListedFolderItem() { FileName = gotFolName, FileDate = gotFolDate, FileExtension = gotFolType, FilePath = gotFolPath });
                        }
                        else
                        {
                            FilesAndFolders.Add(new ListedItem() { EmptyImgVis = gotEmptyImgVis, ItemIndex = FilesAndFolders.Count, FileImg = null, FileIconVis = gotFileImgVis, FolderImg = gotFolImg, FileName = gotFolName, FileDate = gotFolDate, FileExtension = gotFolType, FilePath = gotFolPath });
                        }
                    }
                    index += step;
                    folders = await folderQueryResult.GetFoldersAsync(index, step);
                }
```

**Comment by ashikns** [comment]
In the snippet above folderQueryResult has the ContentChanged event. Going by common sense that event should fire for everything, doesn't matter what you are passing for step. The docs does say you have to call GetFoldersAsync at least once before the event will fire on changes. But it still should fire for everything which is what we want. Again this is unverified but hopefully it works.

**Comment by ashikns** [comment]
I tried this out using a simple Debug.WriteLine. It works :) Folder and file creation and deletion are fired on the event. Haven't checked if it fires for modifying as well.

**Comment by ashikns** [comment]
In a more general note, back in the xaml/wpf days there used to be some fancy usercontrols that query only the required number of directories and kept track of changes too. I can't quite remember if we wrote it in house or from public domain, but check the uwp community toolkit if something like this exists.

**Comment by duke7553** [comment]
@ashikns Thanks for this information. However, I just tried to add a method that gets called at the very end of the ItemViewModel's method that gets the items, and the results are quite interesting.
**Added method:**
```
public async void RegisterSmartRefreshEvent(string PathToGet)
        {
            QueryOptions options = new QueryOptions();
            options.FolderDepth = FolderDepth.Shallow;
            options.IndexerOption = IndexerOption.UseIndexerWhenAvailable;
            StorageFolder folder = await StorageFolder.GetFolderFromPathAsync(PathToGet);
            StorageItemQueryResult storageItemQueryResult = folder.CreateItemQueryWithOptions(options);
            await storageItemQueryResult.GetItemsAsync();
            storageItemQueryResult.ContentsChanged += StorageItemQueryResult_ContentsChanged;
        }
```

This method creates a separate query for testing purposes, but when the code is finally executed, I get very weird results. So far, the event simply prints a message to the screen, but it does this many times per file deletion. [Output below] I would only expect it to fire once per event. Not to mention, it took nearly a minute to fire at all. 

**Output for one file deletion**
```
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
Smart Refresh Requested...
```

**Comment by ashikns** [comment]
Hmm that's to be expected I guess. It's a new api that was introduced in Anniversary update and MSFT sometimes takes a while to get an api working properly. I'll take a look at this soon.

**Comment by ATecSolution** [comment]
Any updates on this issue?

**Comment by ashikns** [comment]
Not yet. The api discussed above does work so that is the way forward.

**Comment by ATecSolution** [comment]
Looking forward!
