### ISSUE TITLE
The new sorting feature introduced with v0.7.6 crashes the app when navigating to a directory 

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#601]
To reproduce this issue, build the app with release mode and try navigating to a directory.

**Comment by yaichenbaum** [comment]
cc @jeffsieu

**Comment by tsvietOK** [comment]
@yair100 look at this [space ](https://github.com/duke7553/files-uwp/blob/6c00418f75d856683f55fa44dea1e34422aae786/Files/Helpers/NaturalStringComparer.cs#L24) before .dll
