### ISSUE TITLE
Crashes when trying to open most folders

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#602]
Files UWP often crashes when trying to open a folder.
see video:
https://youtu.be/7Xt3k2TOF0c

**Desktop:**
 - OS: Windows 10 1909 18363.657
 - App version: v0.7.6

**Comment by jeffsieu** [comment]
May be related to #601

**Comment by Crocodile73** [comment]
yeah can confirm this happens on Windows 1909 (1863.778)
Click into a folder, expect folder to open
App crashes.
0.7.6 (External Drives attached)
File Permission granted

**Comment by Darhagonable** [comment]
id say this is a critical bug but the labels didn't get applied even if i chose the critical bug option

**Comment by duke7553** [comment]
@Darhagonable The new update, which is in certification for the Store, may address this issue.

**Comment by Crocodile73** [comment]
@duke7553 If its same as master branch, the issue is still there.

**Comment by yaichenbaum** [comment]
@Crocodile73 Does Visual Studio have an exception?

**Comment by tsvietOK** [comment]
@yair100 
![image](https://user-images.githubusercontent.com/20501502/79579540-6092ae80-80d0-11ea-9425-2420683af11c.png)
"parameter set incorrectly" After call SetSelectedItemsOnUi in PhotoAlbum
Opening folders in generic file browser mode working fine

**Comment by yaichenbaum** [comment]
I am not seeing this issue, can it have something to do with localization?

**Comment by tsvietOK** [comment]
@yair100 To reproduce: start debug, set grid view and try to open folder

**Comment by Crocodile73** [comment]
> @Crocodile73 Does Visual Studio have an exception?

i didn't see anything, will have another look. I went back to 0.7.5

**Comment by tsvietOK** [comment]
For me it is not working only in Downloads folder

**Comment by yaichenbaum** [comment]
@tsvietOK I have tried that and didn't have any issues with it crashing, however I did notice that I can't open the first folder listed in the grid view layout.

**Comment by tsvietOK** [comment]
@yair100 you can open first folder after select and unselect any other element next to this folder

**Comment by tsvietOK** [comment]
@yair100 Null check fixes opening folder
![image](https://user-images.githubusercontent.com/20501502/79587708-9b4e1400-80db-11ea-9660-1a42c4e5b21b.png)

**Comment by tsvietOK** [comment]
@yair100 For some reason first folder can't be opened because of these lines. Without them first folder opens fine. but drag is not working.
![image](https://user-images.githubusercontent.com/20501502/79599186-c2154600-80ed-11ea-9b02-300b87dae751.png)

**Comment by duke7553** [comment]
@Darhagonable Is this still an issue for you?

**Comment by Darhagonable** [comment]
> @Darhagonable Is this still an issue for you?

Just built version 0.7.9 and it seems to fixed now! :D
