### ISSUE TITLE
Automatically expand the hamburger menu when hovering over it

### ISSUE THREAD

**Issue by StrongholdFan** [duke7553/files-uwp#61]
I'd appreciate, if the hambuger menu/navigation pane on the left hand side of the app would automatically expand, when the user hovers over it with the mouse cursor. This was implemented in the Windows 10 start menu for "19H1" builds (source and more details: (_https://www.windowslatest.com/2018/11/15/windows-10-19h1-to-change-start-menus-navigation-pane-behaviour_).

Maybe adding the ability to turn this feature on and off via the app's settings would be a good idea, because not everyone will like it, I guess. Still, I consider it very useful and hope it will be implemented in the future.
Thanks for your work.

**Comment by StrongholdFan** [comment]
Something I just noticed as an addition: when expanding the menu with a mouse click, the elements _Refresh_ _Add Item_ and the _..._ are also "affected" by the expanding animation, while not changing their position at all. Would be a little, but nice polishing, if the expanding animation wasn't applied to these three UI elements, because it doesn't make any sense there, just looks weird.

Hope it's clear what I mean. Otherwise, let me know any I will go into more detail/make a .gif or something. :)

**Comment by duke7553** [comment]
Sorry, but I don't think this feature would be very practical for the NavigationView.
