### ISSUE TITLE
Error: The package or bundle is not digitally signed or its signature is corrupted.

### ISSUE THREAD

**Issue by dexbyte** [duke7553/files-uwp#62]
I am getting this message while running the install script.

**Comment by KartSriv** [comment]
Same here. Tried the powershell script. Still gives an error.

**Comment by KartSriv** [comment]
Well, @dexbyte try the powershell script and see if it installs

**Comment by duke7553** [comment]
Please let me know if it works because I would like to investigate this issue.

**Comment by KartSriv** [comment]
Nope, @duke7553 it's not working. I couldn't install the new version yet.

**Comment by duke7553** [comment]
Rest assured, Files is going to be published as a beta release to the Store soon. That way, you can take advantage of automatic updates to the latest release, which can fix critical bugs. I’ll keep everyone posted on this.

**Comment by Jviix** [comment]
I've solved this and installed the new version. Just install the certificate on trusted warehouses (I don't know if this is the correct translation, but I hope that you'll understand it)

**Comment by owgus** [comment]
I've tried to install and there is no way. I've manually installed the certificate on all warehouses and the same error was thrown. 🤷‍♂️

**Comment by EWBG29** [comment]
This what I did and it worked:

1. Open the security certificate and click on "Install Certificate".
2. Leave it on "Current user" and click Next.
3. Select the radio button that says "Place all certificates in the following store" and click "Browse", then select the directory called "Trusted Root Certification Authorities" and click "OK" (Probably you will get a Warning message just click "Ok, Yes, etc").

Now you should be able to install it with the "Windows App Installer"

**Comment by Pima-Dev** [comment]
I have the same error even if I installed the certificate manually.

**Comment by EWBG29** [comment]
> I have the same error even if I installed the certificate manually.

Try installing the certificate on "Local Machine"...

**Comment by KartSriv** [comment]
@EWBG29 Sorry, I shut down my Windows Server so can't test Files-UWP anymore.

**Comment by duke7553** [comment]
@KartSriv Switched to Linux, huh?

**Comment by KartSriv** [comment]
@duke7553 Well, I didn't switch to Linux. I always had Linux for a lifetime. I was just running Windows Server for some Django Projects I had before. It's actually a Social Media for my school. I just moved out so I shut it down.

**Comment by duke7553** [comment]
@KartSriv Neat. I've played around with Linux myself. I probably like Fedora the most, but... 
It is quite hard to juggle around school and this project, so that's why I have been AFK a lot lately. Still have some big plans for Files coming eventually. Here's a WIP teaser
![Annotation 2019-04-10 010327](https://user-images.githubusercontent.com/20365014/55852823-77510d80-5b2c-11e9-9896-2cd3442eb771.png)

**Comment by KartSriv** [comment]
@duke7553 Files-UWP look soo clean! This intrigues me to install Windows in a VM to try it. Why don't you name it Project Shanghai cause Shanghai is the most populated city in the world? I'll surely come back to test it. All the best!

**Comment by duke7553** [comment]
Moved to https://github.com/duke7553/files-uwp/issues/68 for now.

**Comment by yaira2** [comment]
A signed installer is now available on our website https://files.community/download
