### ISSUE TITLE
Space for "Double tap to rename files" text does not adjust automatically

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#636]
**Screenshots**
![Anotación 2020-04-22 082246](https://user-images.githubusercontent.com/61259627/79982256-08630000-8474-11ea-937a-8e675ba705af.png)

**Desktop:**
 - OS Version: Windows 10 1909
 - App version: [v0.7.7]

**Comment by yaichenbaum** [comment]
This should be fixed with #646.
