### ISSUE TITLE
Why drop the ARM version?

### ISSUE THREAD

**Issue by KartSriv** [duke7553/files-uwp#64]
### Why drop the ARM version?

Hey, @duke7553! In my opinion, it's a stupid idea (No Offence) _to drop the ARM Version_ because **ARM** and **IoT** are the _future_ and when I was trying to install Files in my Rasp Pi, I was searching for the ARM version _until I read and understood that you stopped support for ARM_. I know it's tough for developing a version for ARM and to create new certificates for it but **please try to keep the ARM version alive.** Just an opinion and would be nice if you start developing again. Thanks and sorry for mentioning it was a stupid idea.

**Comment by duke7553** [comment]
Hey, thanks for your feedback. The new functionality added for running EXEs currently only supports x86 and x64. I plan on eventually compiling this for ARM also, and you can expect a great effort to achieve this before the Store release.

**Comment by duke7553** [comment]
P.S. A raspberry Pi isn’t necessarily the best device to run Windows 10 on either, but the ARM releases are likely being dropped temporarily ;)

**Comment by duke7553** [comment]
@KartSriv I'll bring back the ARM version now, but it may have bugs. Please read the note on this page: https://github.com/duke7553/files-uwp/releases/tag/v0.4.8 .
Download should be up now for ARM

**Comment by KartSriv** [comment]
Thanks. @duke7553! It's very nice of you. I have a small tip: Focus mainly on the x86 and x64 Arch for now. Once you've perfected the code then make one for the ARM Arch. It'll make the delivery time quick and you can have a much more stable code for the consumer.
