### ISSUE TITLE
In grid view, the icon of the first file is not displayed correctly

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#641]
![Anotación 2020-04-22 145248](https://user-images.githubusercontent.com/61259627/80021750-fea7bf80-84a8-11ea-93b4-993c4f766db1.png)
![Anotación 2020-04-22 145301](https://user-images.githubusercontent.com/61259627/80021753-ffd8ec80-84a8-11ea-9e08-c0b9c96e8eba.png)

v0.7.7

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
