### ISSUE TITLE
Visual suggestions for properties dialog

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#647]
- [x] The icon should be aligned to the left side.
- [x] The OK button should not stretch, but have a fixed width
- [ ] The window's corners should have a radius

![alignment](https://user-images.githubusercontent.com/17484252/80033467-15700580-84ed-11ea-8227-21e76b7361a4.PNG)
![buttonSize](https://user-images.githubusercontent.com/17484252/80033469-16089c00-84ed-11ea-94ca-ee2831bc23aa.PNG)

**Comment by yaichenbaum** [comment]
1. Some icons are square, that is why there is extra space on the edges.
2. Thank you for pointing this out 😂.
3. Unfortunately this one isn't possible since this is a regular window which doesn't let you set the corner radius.

**Comment by yaichenbaum** [comment]
Besides for the corner radius, the feedback in this issue should be addressed with #648.
