### ISSUE TITLE
Several fields in Settings are cut in Italian localization

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#650]
In the Italian localization, several fields in Settings are cut and you can't read the whole phrase

![image](https://user-images.githubusercontent.com/50930970/80079562-bcd25400-8550-11ea-9216-ade97900fd6f.png)

![image](https://user-images.githubusercontent.com/50930970/80079456-97dde100-8550-11ea-98e4-c523f9f7bf47.png)

Side Note: "RCerca" (equivalent of "Search") may be a typo, the correct translation should be "Cerca"

Windows version: Windows 10 1909
Files version: 0.7.7

**Comment by xPoppyx** [comment]
one of those was fixed with #646 
![80079562-bcd25400-8550-11ea-9216-ade97900fd6f](https://user-images.githubusercontent.com/61259627/80099178-0ebcaf00-853c-11ea-8a97-0830db3be956.png)

**Comment by yaichenbaum** [comment]
This should be fixed with https://github.com/duke7553/files-uwp/pull/653.
