### ISSUE TITLE
Sometimes i can't open the first folder/file in grid view mode

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#660]
As shown in the gif, it works if I click on another folder first

![folder](https://user-images.githubusercontent.com/61259627/80142490-39792880-8579-11ea-8d0c-3460098b8766.gif)

_I go back using the side mouse buttons, that's not part of the bug_

**Comment by yaichenbaum** [comment]
Is this still an issue in v0.8.0?

**Comment by xPoppyx** [comment]
v0.7.8
![folder](https://user-images.githubusercontent.com/61259627/80306643-83892680-8792-11ea-85d6-efec6fb16128.gif)

**Comment by AdrianP25** [comment]
I have the same bug, even so good App!

**Comment by yaichenbaum** [comment]
This issue was fixed with #787.
