### ISSUE TITLE
The app crashes when trying to interact with a .url file

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#661]
It crashes when trying to open, copy, cut, share, view properties, it cannot be renamed, and when trying to delete it, this happens:
![Anotación 2020-04-23 160457](https://user-images.githubusercontent.com/61259627/80144507-a17d3e00-857c-11ea-842b-89856529f32b.png)

**Comment by yaichenbaum** [comment]
I think the issue is that Files UWP doesn't support shortcut files yet. The solution would be to hide url files until they are supported.

**Comment by yaichenbaum** [comment]
#662 Disables loading url files. We will re-enable shortcut files when we can properly support them.
