### ISSUE TITLE
Is the "Up" button really useful?

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#667]
I thought that its function was to go back to the top, but I realized that it only goes back in the same way that I would do using the navigation bar.

**Comment by R3voA3** [comment]
The top button is used to go one level up in the folder hierarchy, so it does what it' supposed to.

**Comment by yaichenbaum** [comment]
The up button is very useful, while you can do that from the navigation bar as well, many users are used to using the up button. It is also useful if the path in the navigation bar is very long and you would have to scroll to find the path you want to switch to.
