### ISSUE TITLE
Acylic effect is too subtle

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#671]
In my opinion the acrylic effect is too weak/dark. It looks really dull to me. For comparison:
![acrylic_old](https://user-images.githubusercontent.com/17484252/80189511-113e0800-8613-11ea-98fc-a51ba569e107.PNG)

![acrylic_new](https://user-images.githubusercontent.com/17484252/80189509-10a57180-8613-11ea-9795-af303b6c9543.PNG)

**Comment by yaichenbaum** [comment]
It is done this way to limit distractions. When it lets too much through it can lead to issues like this
![image](https://user-images.githubusercontent.com/39923744/80223482-5879c800-8616-11ea-9442-d5f5d7837a90.png)
