### ISSUE TITLE
Slow scrolling speed (mouse)

### ISSUE THREAD

**Issue by XeZrunner** [duke7553/files-uwp#675]
**Describe the bug**
Compared to other applications, Files UWP's scrolling speed is very slow with a mouse.

**To Reproduce**
1. Open the application and navigate to a folder with many files and/or folders.
2. Open the Windows File Explorer at the same path or other applications that support scrolling.
3. Keep scrolling and switching between the two applications to compare.

**Expected behavior**
The application should try to follow the user's system mouse settings for mouse scrolling speed.

**Screenshots**
[Video comparing scrolling speed between Files UWP and Windows File Explorer](https://youtu.be/rtDrGlJE3FA)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.778
 - App version: v0.7.7.0

**Additional context**
None. (?)

**Comment by yaichenbaum** [comment]
Unfortunately this isn't something we can control right now, it is the behavior of the Community Toolkit DataGrid control. The good news is that a new one is going to be made by WinUI which will fix many of the issues with the Toolkit version.
You can add your feedback to the open issue on the WinUI repo here https://github.com/microsoft/microsoft-ui-xaml/issues/1500.
