### ISSUE TITLE
If you select and deselect a folder or file, you can't open it

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#678]
![bug](https://user-images.githubusercontent.com/61259627/80240000-2c1e7580-862f-11ea-8673-9a5770526311.gif)

**Comment by XeZrunner** [comment]
Can confirm. It prompts me to rename the file instead.
By turning off the Double tap to rename files option in Settings -> Experimental, I can't reproduce the issue anymore.

**Comment by yaichenbaum** [comment]
That is a different issues, the issue reported here is an issue with something in the photo album layout mode that was introduced after we added the drag and drop feature.
The issue you mentioned is a bug with the Toolkit Data Grid control that we use for the list view layout mode. While we are waiting for the toolkit to fix this issue we added an option to turn of the double click to rename feature.

**Comment by yaichenbaum** [comment]
@tsvietOK Can you confirm that you fixed this issue?

**Comment by tsvietOK** [comment]
@yaichenbaum it is not my patch 😁, but issue has been fixed.

**Comment by yaichenbaum** [comment]
Thank you @Dylan-Osborne for fixing this issue!
