### ISSUE TITLE
Changes to files should refresh the directory 

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#679]
After creating a new file the extension doesn't show until you refresh the directory, if you try interacting with the file before refreshing the directory the app will crash.
After creating a new folder, it adds it to the bottom of the list, copying and pasting the folder will crash the app unless you refresh the directory.

If you know of any other actions that have this issue, add them as a comment.

**Comment by xPoppyx** [comment]
if you rename a file and try to interact with it without refreshing, the app crashes too

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.

**Comment by xPoppyx** [comment]
after renaming you still need to refresh manually
