### ISSUE TITLE
Investigate Installation Issues

### ISSUE THREAD

**Issue by MikotoF** [duke7553/files-uwp#68]
I've turned developer mode on and tried to install it with Add-AppDevPackage.ps1 and then got this:

![2](https://user-images.githubusercontent.com/47990017/53362606-42ee0d00-3943-11e9-9381-3b5663f214ec.PNG)

Further tries don't show any results.

![1](https://user-images.githubusercontent.com/47990017/53362645-5600dd00-3943-11e9-8154-cb9aceb05c87.PNG)

What should i do?

**Comment by MikotoF** [comment]
PowerShell installation worked with 0.4.7.0 version.

**Comment by duke7553** [comment]
@MikotoF What Windows 10 version and architecture are you trying to run Files on?

**Comment by kaylinDevelopment** [comment]
I've had the same issue with Windows 10 Home 1804 x64

**Comment by MikotoF** [comment]
> @MikotoF What Windows 10 version and architecture are you trying to run Files on?

Windows 10 Pro 1803 x64

**Comment by duke7553** [comment]
@MikotoF @kaylinDevelopment I'm going to explore this issue, and do some further testing. We may have to make Files compatible with 1809+ only. I'll see.

**Comment by kaylinDevelopment** [comment]
@dexbyte Thanks! That works.

**Comment by duke7553** [comment]
Sorry about this guys. Glad to hear you've found a way around it. I can't replicate this with my current hardware, so I'm going to test this out with other machines and update the installation instructions for the next pre-release.

**Comment by duke7553** [comment]
According to the Microsoft Documentation for signing UWP apps, it is not recommended to distribute a pre-release sideload package with a test certificate, so the next pre-release will be distributed from the Microsoft Store. Closing this bug.
