### ISSUE TITLE
Alternative to "Home" tab

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#683]
**Don't give much importance to the style of icons and bars.**

![Captura de pantalla (196)](https://user-images.githubusercontent.com/61259627/80251188-334f7e80-8643-11ea-8aa0-77e12edaab16.png)

With "Recents":

![Captura de pantalla (196) 2](https://user-images.githubusercontent.com/61259627/80252322-15831900-8645-11ea-83e1-bb89fac56fb0.png)

Bigger drives:

![Captura de pantalla (196)3](https://user-images.githubusercontent.com/61259627/80251640-f2a43500-8643-11ea-9a19-456d376a9638.png)

Bigger drives + "Recents":

![Captura de pantalla (196)4](https://user-images.githubusercontent.com/61259627/80252380-27fd5280-8645-11ea-83f2-a81a2f2a9317.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, please see #366.

**Comment by xPoppyx** [comment]
#692
