### ISSUE TITLE
App crashes when opening a file with .url extension (OneNote)

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#685]
**Describe the bug**
App crashes when opening a file with .url extension (OneNote)

**To Reproduce**
1. Double Click on a .url file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
- App: 0.7.7.0

**Comment by yaichenbaum** [comment]
Can you try updating to v0.8.0? v0.8.0 disabled loading url files since we do not support shortcut files yet.
