### ISSUE TITLE
Double click to rename generally strange behavior

### ISSUE THREAD

**Issue by Chaoticoz** [duke7553/files-uwp#689]
**Describe the bug**
Double click to rename gets activated, even when you click on empty space in between the two clicks.

**To Reproduce**
-Click an item
-Click in empty space
-Click the item again

**Expected behavior**
In this case, double click to rename should not be activated

**Screenshots**
![EJ4wMqKnZc](https://user-images.githubusercontent.com/6023076/80261287-4f2a4300-868a-11ea-96a7-8ef928ea3150.gif)

**Desktop (please complete the following information):**
-OS Version: Windows 10 1909 18363.778
-App version: 0.7.8.0

**Comment by yaichenbaum** [comment]
This is a bug with the community toolkit data grid control, while we wait for a fix you can disabling this feature from the experimental settings page. I hope this help.
