### ISSUE TITLE
personalization Not Show preview

### ISSUE THREAD

**Issue by hamerstandr** [duke7553/files-uwp#69]
personalization Not Show preview.

**Comment by ATecSolution** [comment]
Do you mean the photo does not change to indicate how dark or light theme looks?

**Comment by PoorPocketsMcNewHold** [comment]
@ATecSolution is talking about that in the application settings. 
![image](https://user-images.githubusercontent.com/13170204/53527303-e6c3ee00-3ae6-11e9-81ff-8f73af56ceaa.png)
_(I hope you didn't expected the application to show up in the Win 10 settings panels)_

**Comment by duke7553** [comment]
Not enough information.
