### ISSUE TITLE
List view flickers when changing to grid view

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#694]
**Describe the bug**
The list view flickers once the button in the start menu is pressed.

**To Reproduce**
1. Open a folder and select list view
2. Click on the button used to switch the view

**Expected behavior**
It should be a smooth transition.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004
 - App version: 0.7.7.7

Additional Information:
It's working fine when changing from grid to list view.

**Comment by yaichenbaum** [comment]
This is actually an issue in recent insider builds, I noticed it in other areas of Windows. It will hopefully be fixed in a future insider build.
