### ISSUE TITLE
Ctrl+C, Ctrl+V, and Ctrl+X shortcuts

### ISSUE THREAD

**Issue by seohyun1108** [duke7553/files-uwp#695]
**Is your feature request related to a problem? Please describe.**
I want these shortcuts because I want to copy and paste easily.

**Comment by xPoppyx** [comment]
They actually work, just not very well, I need to hold "Ctrl + v" for a second to make it work and sometimes the app crashes when pasting a file

**Comment by yaichenbaum** [comment]
@seohyun1108 Can you add information like the app version number and layout mode?

**Comment by yaichenbaum** [comment]
I can't reproduce this issue, please make sure you are running the latest version of the app and that you gave the app file access permissions.

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
