### ISSUE TITLE
"Add Item" Does Not Work

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#7]
Clicking on "Add Item" will bring you to the add item menu, but nothing happens when you click on any of the options.

Also, there is no way to escape that menu.

**Comment by duke7553** [comment]
This functionality is unimplemented so far, which would explain why it flat-out does not work. I plan on transitioning this menu to a ContentDialog and adding these options eventually, I'll prioritize critical function bugs like item paste collision, etc. over this.

**Comment by duke7553** [comment]
Fixed in v0.4.7
