### ISSUE TITLE
A Less-Dark Dark Theme

### ISSUE THREAD

**Issue by duke7553** [duke7553/files-uwp#71]
Let's keep this short and simple. These are screenshots of something that has not been released to testers yet. Please let me know what you think, and what other themes you would want in the future.
![802be4a3-d9da-45d4-9fb1-93a8cf869a9d png](https://user-images.githubusercontent.com/20365014/53528014-70a79300-3ab6-11e9-8835-445980ce66b4.jpg)
![4f2a929a-114a-468a-9321-c878bcf9108b png](https://user-images.githubusercontent.com/20365014/53528074-8e74f800-3ab6-11e9-81fa-90c56f8485a3.jpg)

PS: The darker DataGrid headers are a bug in the DataGrid which is likely out of my control.

**Comment by duke7553** [comment]
Also, apologies for no testing release recently, as I have been busy fixing bugs and with school.

**Comment by ATecSolution** [comment]
I think those cards in the top screenshot are a group improvement!
