### ISSUE TITLE
Selection Bug

### ISSUE THREAD

**Issue by Mahan3340** [duke7553/files-uwp#723]
**Describe the bug**
File/Folder Select All Bug
**To Reproduce**
1. Select all from the bottom menu
2.  Click Somewhere blank to clear the selection
3. now the normal click and the long click do not work at all for all files and folders

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18363.815]
 - App version: [v0.7.8.0]

**Comment by Mahan3340** [comment]
This also happens when a single file or folder is long pressed ( when the menu opens once this happens regardless of actually selecting an action or just dismissing the menu). By the way, I am using a surface with a touch screen.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
