### ISSUE TITLE
无法打开部分子文件夹

### ISSUE THREAD

**Issue by Alex-Ricardo** [duke7553/files-uwp#730]
用的是win10应用商店的uwp版本，已经打开win10设置里的读取系统文件选项。可是无法打开部分子文件夹。部分如快捷方式等文件不显示。
![QQ截图20200501144210](https://user-images.githubusercontent.com/45425384/80787773-060e4d80-8bba-11ea-9d03-3b365b70c6c6.png)

**Comment by xPoppyx** [comment]
目前该应用程序不支持快捷方式

_--google translator--_

**Comment by duke7553** [comment]
Moved to #177
