### ISSUE TITLE
Ability to change the default downloads folder

### ISSUE THREAD

**Issue by GameSpeck** [duke7553/files-uwp#733]
**Is your feature request related to a problem? Please describe.**
My Windows OS is installed on my SSD but all my downloaded stuff is in my HDD because it has more space. 

**Describe the solution you'd like**
Abiltity to change the default download folder, instead of C:\Downloads

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by yaichenbaum** [comment]
@GameSpeck Can you check if changing the location from File Explorer addresses this issue?

**Comment by Daksh777** [comment]
@yair100 Can you please explain what do you mean by changing the location? I didn't get it.
Edit: Yes, it worked! I am going to close my issue.
