### ISSUE TITLE
Can't build app from source code

### ISSUE THREAD

**Issue by brukbrhane** [duke7553/files-uwp#735]
Whenever I try to build files-uwp from source, It keeps telling me that I'm missing the assembly references "Windows" from the **Files.Launcher** project and "Windows Desktop Extensions for the UWP" on the **Files** project.

**Steps to reproduce the behavior:**
1. Open `Files.sln` file.
2. Change the CPU arch to x64
3. Run on local machine

**Expected behavior**
The program builds and shows me the working UWP app

**Screenshots**
![image](https://user-images.githubusercontent.com/20716815/80889756-69d26c80-8cc7-11ea-839d-94742c613118.png)

**Desktop:**
 - OS Version: Windows 10 1909 18363.778]
 - App version: [v0.7.8]

**Additional context**
It also says that It can't find the Windows SDK version 10.0.18362.0 (I have `10.0.18362.1`)I'm not sure where I can get upgrade the SDK within the project so it would stop throwing this error...

**Comment by lampenlampen** [comment]
Did you install it to the standard location?

**Comment by brukbrhane** [comment]
@lampenlampen I likely did not

**Comment by yaichenbaum** [comment]
@brukbrhane Make sure that you have the right dependencies installed, if you don't Visual Studio should prompt you to download them.

**Comment by brukberhane** [comment]
@yair100 I didn't get any prompts. I'll try reinstalling VS to see if that helps

**Comment by lampenlampen** [comment]
Then this is the reason.

I had the same problem with the extension sdks.

VS couldn't find the extension sdk and on some microsoft forum the suggestion was to reinstall or copy the extension sdks from the custom location to the default one.

**Comment by duke7553** [comment]
Also make sure to select the Files.Package project before you build

**Comment by brukbrhane** [comment]
Alright I've been AFK for a little while but I'll try reinstalling VS and trying what you've all told me. Thanks
