### ISSUE TITLE
Show disk usage

### ISSUE THREAD

**Issue by Ombrelin** [duke7553/files-uwp#736]
In the old windows Files Explorer there is a view that shows the disks usage (occupied space and remaining space). Files UWP doesn't have this feature (or I have found it ?)
![image](https://user-images.githubusercontent.com/47502331/80892388-f120df80-8cc9-11ea-9e2c-56f7ed91cb76.png)

When you click on "Drives" show a view with the usage of disks using progress bars

Would love to have this feature, but the app is already very nice !

**Comment by yaichenbaum** [comment]
@Ombrelin Thank you for opening this issue, a page for displaying drives is something we are exploring in #210. We are also looking into the possibility to add a widget to see drives on the home page in #366. I am going to be closing this issue in favor of the existing ones, but please add your feedback to each of them.
