### ISSUE TITLE
Suggestion New For Files UWP

### ISSUE THREAD

**Issue by MichelEngel** [duke7553/files-uwp#739]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by MichelEngel** [comment]
![InkedScreenshot_6_LI](https://user-images.githubusercontent.com/60907149/80925461-46aaca00-8d66-11ea-9051-324de3ce71c3.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/60907149/80925463-47436080-8d66-11ea-8086-bbe17e994b83.png)
![Screenshot_3](https://user-images.githubusercontent.com/60907149/80925464-47dbf700-8d66-11ea-8640-ab993de8c15d.png)
![Screenshot_4](https://user-images.githubusercontent.com/60907149/80925465-47dbf700-8d66-11ea-81cb-fafbf3bb230e.png)
![Screenshot_5](https://user-images.githubusercontent.com/60907149/80925466-47dbf700-8d66-11ea-9cf1-03ae5d3d1964.png)

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.

**Comment by xPoppyx** [comment]
maybe these:
- specify what type of file you want to search
- when dragging and dropping a tab, open in a new window
