### ISSUE TITLE
The app crashes when starting [v0.7.9]

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#741]
![crash](https://user-images.githubusercontent.com/61259627/80984298-abfcca80-8dfb-11ea-8d7e-9be40c6bbea1.gif)

**Comment by yaichenbaum** [comment]
Does this issue still exist after resetting the app?

**Comment by xPoppyx** [comment]
I used the repair and reset options, it keeps crashing, I also tried to reinstall and restart Windows

**Comment by SOI7** [comment]
To me the app starts crashing on boot after opening a new tab. If I reinstall the app it opens again but the new tab causes the crash on boot again

**Comment by yaichenbaum** [comment]
New tab crashes it for me as well.

**Comment by yarikvv** [comment]
I have same issue as well. App crashes right after launch.

**Comment by yaichenbaum** [comment]
@yarikvv Try to reset the app.

**Comment by yarikvv** [comment]
@yaichenbaum I tried both resetting and reinstalling. Nothing really helped.

**Comment by yaichenbaum** [comment]
You might need to reopen the app a few times after resetting it, in any case @tsvietOK already has a fix and we hope to deploy it in the next few hours.

**Comment by xPoppyx** [comment]
in my case, after trying to open several times it works, but if I close and try to open, it crashes again

**Comment by yarikvv** [comment]
@yaichenbaum Yeah, on the third start it didn't crashed tho

**Comment by luandersonn** [comment]
Same where

**Comment by luandersonn** [comment]
Same here

**Comment by yaichenbaum** [comment]
This issue should be fixed with v0.8.0.

**Comment by yaichenbaum** [comment]
@ADeltaX @tsvietOK Thank you for all your help on fixing this issue.
