### ISSUE TITLE
Can't open some folders in grid layout

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#745]
**Describe the bug**
When in grid layout sometimes double clicking a folder sometimes does nothing, opening in new tab works though. 

**To Reproduce**
1. Set to grid layout.
2. Open folder within folder within folder.
3. At some point it no longer opens the folder.

**Expected behavior**
the folder to open like normal

**Desktop**
 - OS Version: Windows 10 1909 18363.815
 - App version: v0.7.9

**Comment by yaichenbaum** [comment]
This might be related to #660.

**Comment by Darhagonable** [comment]
@yair100 maybe but mine is not limited to the first folder but seems to be more random.

**Comment by Darhagonable** [comment]
this seems to be fixed now as well

**Comment by yaichenbaum** [comment]
@Darhagonable Thank you for letting us know.
