### ISSUE TITLE
Rename file does not work

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#747]
**Describe the bug**
It would open the folder or the file

**To Reproduce**
1. Right click a folder or a file
2. Rename

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.207]
 - App version: [v0.7.9.0]

**Comment by duke7553** [comment]
Does this occur after creating the item?

**Comment by duke7553** [comment]
Also, what are you naming the file? Can you send us a screenshot of the issue?

**Comment by xPoppyx** [comment]
maybe it is related to #651

**Comment by tomyan112** [comment]
> Also, what are you naming the file? Can you send us a screenshot of the issue?

It is like @xPoppyx #651 issue, I too disabled Experimental double tap to rename files

**Comment by yaichenbaum** [comment]
@tomyan112 Thank you for reporting this issue, lets move it over to #651.
