### ISSUE TITLE
Hard drives disappearing + other

### ISSUE THREAD

**Issue by astalavista5000** [duke7553/files-uwp#750]
There is a bug that when I start the app the Hard Disks and Onedrive disappear from view.
At first everytime the app gets updated they show but when I close the app and start it they disappear.
Also the search button doesn't work.
Right-click on recent items doesn't work.

**Comment by xPoppyx** [comment]
searches have not yet been implemented, it was supposed to be disabled

**Comment by yaichenbaum** [comment]
@astalavista5000 What version of the app are you running? Did you give the app permission to access the file system?

**Comment by astalavista5000** [comment]
I’m running the latest version 0.8.0.0 and yes because other files are being read.
They do appear on startup AFTER and update but after a second run they disappear.
I’ve noticed on GitHub that there are other reports like this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yaichenbaum** [comment]
Checking to see if files are visible is not always a reliable way to know if the app has permissions to access the file system, I would recommend checking in the Windows 10 settings app to confirm.

**Comment by astalavista5000** [comment]
Hi,

I tried searching for Permissions but I can’t seem to find the option from the Windows 10 Settings.
Can you kindly help?

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xPoppyx** [comment]
Settings > privacy > file system

**Comment by astalavista5000** [comment]
Hi,

Found it, it's enabled.
Still the app randomly shows One drive and other Drives but upon closing and starting the app those disappear again.

Thanks

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by xPoppyx** [comment]
- sometimes the app starts without loading drives

**Comment by yaichenbaum** [comment]
@tsvietOK I believe you fixed this issue in a recent pull request, can you confirm?

**Comment by tsvietOK** [comment]
@yaichenbaum From my side it is working fine. I launched app in release mode 20 times, and all time drives has been loaded.

**Comment by astalavista5000** [comment]
[Image]
Hi,

As you cans see mine still showing like this :/
________________________________

**Comment by xPoppyx** [comment]
![Anotación 2020-05-11 135153](https://user-images.githubusercontent.com/61259627/81594928-a53bfd80-938f-11ea-8a9e-c87cb5dd1f2a.png)

**Comment by yaichenbaum** [comment]
The reason you don't see it is that the update with the fix has not been released yet.

**Comment by astalavista5000** [comment]
What version are you on since in the previous email there was written that it was tried 20x and all drivers appeared without a problem?
Mine is 0.8.0.0

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yaichenbaum** [comment]
There is no version number yet since this update is still not complete. We will update this issue when the next update is released.

**Comment by astalavista5000** [comment]
Oh I see no problem then, this wasn’t a complain, just feedback, thanks for the work 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.

**Comment by astalavista5000** [comment]
Just received the update, wonderful :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by astalavista5000** [comment]
Hi,

I noticed that there seems to be new testing with the UI which currently makes the app look odd.
I’ve been looking around at the Microsoft new approach (if they don’t change everything again) and I made the below
<made with paint since I don’t have knowledge with Adobes>

[cid:image001.png@01D6732A.0A6C78F0]

The sidebar can be made (if Microsoft released the APIs) like the new Dashboard of Office 365.
For the side the hovering effect can be done like the Vertical Tabs on Edge.
The hovering effect can be done like a pop-up like it shows in Office applications.
Search it seems from what is being shown will be placed in the middle like Teams and Office.
And lastly like the Outlook in the trailer you can notice that where you have the Mails and Mail Preview are like on a different pane from the side bar leaving the top and side together.

Hope the above is understandable.
Below you have the links from where I got the ideas:

  *   https://en.buradabiliyorum.com/microsoft-edge-has-got-vertical-tabs/
  *   https://news.yahoo.com/microsoft-changes-office-ui-103509698.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAAmQg0FbsTRfcpPmYcjEEegt3S722rnYzsSn5mhXpZKk-6e477hSUDgDfhkF-DfjCXfNO36HXQ89ZEyJ_WSp7Ac0ZnNa8dFrCsvA-cU38rv7DCNs_ZMSbM7TakDDBUwca7L0AjCo44HLN3FJKNz7UdS_dAnJ98R-kPMuFii0zBCM
  *   https://www.onmsft.com/news/microsoft-365-home-dashboard-updated-with-a-beautiful-new-design
  *   https://www.office.com/

Thanks

Miklos Schembri

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Miklos Schembri<mailto:miklosschembri@hotmail.com>
Sent: 18 May 2020 15:49
To: duke7553/files-uwp<mailto:reply@reply.github.com>; duke7553/files-uwp<mailto:files-uwp@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [duke7553/files-uwp] Hard drives disappearing + other (#750)

Just received the update, wonderful :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
