### ISSUE TITLE
Deselect with Ctrl + click

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#752]
![crash](https://user-images.githubusercontent.com/61259627/81246803-84b62100-8fe6-11ea-97e6-83aa9ede2783.gif)

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.

**Comment by yaichenbaum** [comment]
I was able to reproduce this issue. If you ctrl + click on something it should select or deselect it.

**Comment by xPoppyx** [comment]
@duke7553 you can select multiple files with Ctrl + click, but you should also be able to deselect
![deselect](https://user-images.githubusercontent.com/61259627/81882382-9d7f8300-9560-11ea-9967-42d015440755.gif)

**Comment by yaichenbaum** [comment]
This issue has been fixed with #788

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
