### ISSUE TITLE
Make it closer to explorer.exe

### ISSUE THREAD

**Issue by diligamer** [duke7553/files-uwp#757]
# Feedback

## Making Close To Explorer
1. There are some view switching shortcuts not in Files UWP  `ctrl+shift+1 through 6` 
2. Allow us to switch the pinned sidebar items (#289)
4. Add a preview and details pane
5. Add folder icon support
6. Scrolling while viewing in QuickLook doesn't cause QuickLook to show the new selected file
7. Files appear twice
8. Add grouping support
9. Use a ribbon
10. Add third-party and some windows context menu options
<#644> 
11. Add more new file options 
12. Move some stuff around to look closer
13. The … menu should be opened when I right click, remove the new and … menu from the top area, and make new file creation be submenu from the right click
</#654>
14. Make the search bar next to the path bar, and make search a box
15. Add recycle bin support (#669 
16. Change the friendlyAppName to `Explorer`
17. Add the same Properties functionality in explorer (#645)
18. The folder size doesn't appear in properties
19. The properties window shouldn't have a fullscreen or minimize button
20. Trying to open properties using the shortcut goes to the next item
21. Add tree support in sidebar (closely related to #289)
22. Better alert prompts (#221)
23. Make `About Box` more like winver but instead of the msft license terms its the lgpl
24. Add open with

## Other Feedback
1. Add link to explorer settings
2. When an action fails, allow the user to open explorer on the same location
3. Auto size columns

**Comment by xPoppyx** [comment]
17. #645

**Comment by yaichenbaum** [comment]
@diligamer A lot of the issues you mentioned already have open issues, I would recommend subscribing or commenting on the other ones in order to get notified when the issues are fixed.

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
