### ISSUE TITLE
Files UWP in Windows version 1607

### ISSUE THREAD

**Issue by fakerat** [duke7553/files-uwp#759]
Maybe I am missing something, does Files UWP run in Windows build 14393 (1607)?

Is there some plans to cover if if not?

**Comment by duke7553** [comment]
@fakerat Unfortunately, we're only targeting the latest versions of Windows (1809+ currently) because Files leverages UI and filesystem capabilities that only work on that release and higher. I would recommend upgrading to 1909 as it is very stable now that v2004 is almost finalized.
