### ISSUE TITLE
We need a design team.

### ISSUE THREAD

**Issue by diligamer** [duke7553/files-uwp#764]
Without a design team, we will have a spaghetti based app. A design team will also help in deciding the future of the app.

**Comment by duke7553** [comment]
Hello there. 

I understand you concern. Right now we're extremely understaffed, so if you can find some like minded people to help us with the design, I'd definitely be open to working with them to make the app more coherent.

**Comment by diligamer** [comment]
I have a lot of experience using figma and would probably be able to be the head of design, I'll also be in charge of the UI (I don't touch the code).

**Comment by yaichenbaum** [comment]
I disagree, Files UWP has had a lot of thought on every single detail, we have gone through multiple iterations and both @duke7553 and I spend a lot of time on the design of the app. We have had many great discussions and some very good design concepts from different users, especially @xPoppyx. If you feel an area needs work, make sure to comment on an existing issue or open a new one.
