### ISSUE TITLE
App crashes when I navigate to the "Preferences" setting

### ISSUE THREAD

**Issue by olehmisar** [duke7553/files-uwp#766]
**Describe the bug**
The app crashes whenever I click on the "Preferences" button in the settings.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Preferences'
3. App crashes

**Expected behavior**
The app shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/29802592/81486061-e7afee00-925a-11ea-9934-b5972805f322.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903 18363.815
 - App version: 0.8.0.0

**Additional context**
\-

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
