### ISSUE TITLE
Time zone bug

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [duke7553/files-uwp#773]
Windows internally stores timestamps in UTC, however the File Explorer converts it to the current timezone to avoid confusion. Files UWP is not aware of this and shows wrong time for last modfied and created time.

**Comment by duke7553** [comment]
@Jaiganeshkumaran Thank you for opening this feedback item.

Can you please elaborate on why this could be causing the display of negative timestamps? (e.g. -51 seconds)

**Comment by Jaiganeshkumaran** [comment]
I think that this could be because of the calculation. Windows stores timestamps in UTC, not local time.
However Files UWP calculates relative time using DateTime.Now which returns the local time, and that may cause the display of negative timestamps if the time zone is behind UTC.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
