### ISSUE TITLE
Change icon to win10x file explorer icon

### ISSUE THREAD

**Issue by diligamer** [duke7553/files-uwp#774]
I think the current one doesn't look microsofty at all. Using this one would give it a familiar face. You could also change a little to give the app a personality.

![image](https://user-images.githubusercontent.com/32780515/81557724-22b63c80-9395-11ea-962a-e00f1b17f031.png)

**Comment by yaichenbaum** [comment]
The current icon is just the preview icon, the actual icon was designed by the community, take a look at #136 to see the process we went through to get the final icon.

**Comment by diligamer** [comment]
> The current icon is just the preview icon, the actual icon was designed by the community, take a look at #136 to see the process we went through to get the final icon.

I personally think yellow is a dated color in windows file explorer, considering the yellow has been here since 3.1, I think blue would give the app a personality.

**Comment by yaichenbaum** [comment]
Thank you for sharing your thoughts, at this point there are no plans to change the icon.
