### ISSUE TITLE
Concept for explorer 

### ISSUE THREAD

**Issue by diligamer** [duke7553/files-uwp#777]
This is a concept made for explorer's new design, could this be taken on as files's uwp design. 
![image](https://user-images.githubusercontent.com/32780515/81692754-8b6de980-9467-11ea-8baa-48ebd79c9818.png)

**Comment by yaichenbaum** [comment]
Thank you for taking the time to make this concept, **most** users are very happy with the current design and the plan is to keep improving what we already have rather than doing a redesign. Feel free to let us know what you feel is lacking in the current design to help us improve the design further.

**Comment by diligamer** [comment]
This cleans up some inconsistencies and makes it closer to the new edge and adds a tree structure and a preview and details pane.

**Comment by xPoppyx** [comment]
https://github.com/duke7553/files-uwp/issues/692#issuecomment-619397873

**Comment by SOI7** [comment]
Iirc the new WinUI now supports tree-view for side panels (https://twitter.com/gus33000/status/1255152407450796033?s=20), as for colored icons, sadly that can't be done since they rely on MDL2 Assets

**Comment by diligamer** [comment]
Colored icons are in DLLs

**Comment by SOI7** [comment]
Yeah but UWPs can't reference them for sidebars, iirc @yair100 referenced that in another issue

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
