### ISSUE TITLE
Add option to set images as wallpaper

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#78]
Not sure if this functionality is possible with uwp restrictions but if it is please add option to right click on images to set it as default wallpaper.

**Comment by ATecSolution** [comment]
Looks like it is possible with https://docs.microsoft.com/en-us/uwp/api/Windows.System.UserProfile.UserProfilePersonalizationSettings#Windows_System_UserProfile_UserProfilePersonalizationSettings_TrySetWallpaperImageAsync_Windows_Storage_StorageFile_

**Comment by duke7553** [comment]
Until I receive more feedback that this feature is necessary, I will likely not implement it anytime soon. Still should be considered for the future.

**Comment by ATecSolution** [comment]
100% I meant it as a bonus feature once the main functions are implemented.

**Comment by duke7553** [comment]
@yaichenbaum Ideally, this feature should only be visible in the context menu for image files. Has it been implemented yet?

**Comment by yaichenbaum** [comment]
@duke7553 Not yet.

**Comment by yaichenbaum** [comment]
This feature has been implemented and will roll out with v0.7.2.

**Comment by yaichenbaum** [comment]
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.
