### ISSUE TITLE
"Date modified" does not display correctly

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#786]
![Anotación 2020-05-14 230101](https://user-images.githubusercontent.com/61259627/82007140-7cd62c80-9637-11ea-99b3-b4549da69bd7.png)

![seconds](https://user-images.githubusercontent.com/61259627/82007393-1a316080-9638-11ea-8496-5550b0182e78.gif)

-----------------------------------------------
"Date modified" Format #700

**Comment by Jaiganeshkumaran** [comment]
I this this is related to #773
