### ISSUE TITLE
On StartUp options are greyed out

### ISSUE THREAD

**Issue by ChelaruCatalin** [duke7553/files-uwp#793]
![Annotation 2020-05-17 041703](https://user-images.githubusercontent.com/9988172/82133479-480fd400-97f5-11ea-8847-e4d084e5b02e.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, the reasons these options are greyed out is because they have not been implemented yet.
