### ISSUE TITLE
Buttons That Don't Work

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#8]
- [x] Copy Full Path
- [x] Cut
- [x] Copy
- [x] Properties
- [x] Clear all
- [x] Open in new Window
- [ ] Layout Mode
- [ ] Search box / button
- [ ] Edit Columns
- [ ] Size all columns to fit

**Comment by duke7553** [comment]
This is very helpful for me! It is high on my priority list to get the essentials implemented.

**Comment by duke7553** [comment]
Edited to reflect changes

**Comment by ATecSolution** [comment]
waiting for layout mode...

**Comment by yaichenbaum** [comment]
We are going to continue tracking these items in separate issues
- You can see layout mode here https://github.com/duke7553/files-uwp/issues/214
- Search is being tracked here https://github.com/duke7553/files-uwp/issues/333
- Column options is being tracked here https://github.com/duke7553/files-uwp/issues/380
