### ISSUE TITLE
Some thumbnails do not load

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#800]
**updated:** v0.8.2

![Anotación 2020-05-19 112859](https://user-images.githubusercontent.com/61259627/82346074-084b1700-99c4-11ea-9cd3-80b8d7be8152.png)

**Comment by Darhagonable** [comment]
to add to this if one clears thumbnails Files UWP doesn't seem to be able to make new ones so one has to first open the folder in file explorer so the thumbnails get created.

**Comment by duke7553** [comment]
@Darhagonable Thanks for this feedback. I know what the problem is, and will fix it soon based on this information.

**Comment by yaichenbaum** [comment]
This issue has been fixed with #812 and will roll out in the next update to Files UWP.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
