### ISSUE TITLE
Thoughts on opening pull requests directly to master

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#805]
Right now, pull requests are meant to target `develop`. This can lead to merge conflicts when merging `develop` into `master`. I also noticed that when pull requests are merged into `develop` it doesn't show the creator of the changes as a contributor even after merging `develop` into `master`.
What are the communities thoughts on targeting `master` with their pull requests?

**Comment by tsvietOK** [comment]
@yair100 What do you men under "it doesn't show the creator of the changes as a contributor"? Commit info already contain info about all authors
![image](https://user-images.githubusercontent.com/20501502/82269826-8505d300-997b-11ea-88a4-34079ca603c0.png)

**Comment by yaichenbaum** [comment]
@tsvietOK https://github.com/duke7553/files-uwp/graphs/contributors.

**Comment by yaichenbaum** [comment]
All pull requests should now target `master`.
