### ISSUE TITLE
New Ideas/Inspirations from Windows mobile UWP built into Windows 10

### ISSUE THREAD

**Issue by bingeitall** [duke7553/files-uwp#81]
Perhaps this subreddit will explain what I am trying to convey. 

[https://www.reddit.com/r/Windows10/comments/69qbqj/trick_to_open_uwp_file_explorer_on_windows_10/](url)
![screenshot 350](https://user-images.githubusercontent.com/47589555/53884128-d6f55e00-4040-11e9-84f6-ac9124dc9b83.png)
![screenshot 351](https://user-images.githubusercontent.com/47589555/53884129-d78df480-4040-11e9-957e-fe7866fbeaa5.png)
![screenshot 352](https://user-images.githubusercontent.com/47589555/53884130-d78df480-4040-11e9-92e8-5d9a5fe25868.png)

**Comment by ATecSolution** [comment]
@bingeitall please explain more in detail what you want so others can get to work on it ☺

**Comment by bingeitall** [comment]
It is an idea to add those simple buttons for cut/copy and paste commands as well as a sort option.
The link provided tells you how to access the inbuilt UWP file explorer which is more or less Windows mobile file explorer but it could prove to provide some design ideas.

**Comment by ATecSolution** [comment]
Ok, thanks for the information.

**Comment by duke7553** [comment]
Work on exposing these commands is on the roadmap. I'll keep you posted.
