### ISSUE TITLE
Blurry low res image thumbnails

### ISSUE THREAD

**Issue by Darhagonable** [duke7553/files-uwp#810]
v0.8.2

In grid view the thumbnails of low res images appear blurry. This might be intentional when scaling but if one does pixel art or Minecraft textures etc it's not really ideal.
![image](https://user-images.githubusercontent.com/14127357/82351780-53cde700-99fd-11ea-9316-69587586159e.png)
(these are 16x16)

If the thumbnails would use integer scaling instead that would be much preferred.

**Comment by yaichenbaum** [comment]
This issue has been fixed with #812 and will roll out in the next update to Files UWP.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.

**Comment by Darhagonable** [comment]
just built from the master branch and this doesn't seem to be fixed...
![image](https://user-images.githubusercontent.com/14127357/82760953-55315200-9df7-11ea-9862-84ce9cab9d4c.png)
images with low resolution still looks blurry.

**Comment by Darhagonable** [comment]
This is still an issue on v0.9.0
