### ISSUE TITLE
New app icon for light theme

### ISSUE THREAD

**Issue by ATecSolution** [duke7553/files-uwp#82]
Right now the icon for the app has a blue background and border around it when Windows has the light theme selected, can you add a new one that will look better?

**Comment by duke7553** [comment]
This is now in master

**Comment by ATecSolution** [comment]
Thanks

**Comment by amirrammari** [comment]
![image](https://user-images.githubusercontent.com/23485114/61788337-1cb39700-ae27-11e9-8c0c-c6a901b1609d.png)

**Comment by yaichenbaum** [comment]
Can you try reinstalling Files UWP?
