### ISSUE TITLE
Add title for the app

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#83]
Nothing too major but it would be good to add a title to the title bar of Files.

**Comment by duke7553** [comment]
With tabs now on my roadmap, I don't see a way to add this to the titlebar.

**Comment by yaichenbaum** [comment]
Will the tabs be in the titelbar?

**Comment by duke7553** [comment]
Yes, still in development. Will be part of Mumbai

**Comment by yaichenbaum** [comment]
Do you think you can give a roadmap of when features will be added?

**Comment by duke7553** [comment]
I used to have a formal roadmap. Perhaps I should prepare another one.
