### ISSUE TITLE
Wrong date of modification for files

### ISSUE THREAD

**Issue by xumepoc** [duke7553/files-uwp#836]
**Describe the bug**
Apologies if this is already reported.
The date of modification is not taking into account the local time set on Windows 10. I live in timezone which is UTC +2  (+1 with Summer Time). The date of modification shows 3 hours ago for files which I just modified 

**To Reproduce**
1. Change the time zone to UTC +2
2. Modify a file
3. Check data of modification of that file in Files UWP

**Expected behavior**
The Files UWP should use the local time in Windows 10

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.657
 - App version: v0.8.2.0

**Comment by xPoppyx** [comment]
fixed: #831

**Comment by yaichenbaum** [comment]
There is a potential fix for this issue in the fast ring, sign up [here ](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Qw_X6FUM0pUSzMxNUlCWE1FVENKVlVNVUNTRVpOUS4u)to get early access to updates.

**Comment by xumepoc** [comment]
O this is great to hear :D :D :D
