### ISSUE TITLE
Files uwp directory crashes

### ISSUE THREAD

**Issue by ATecSolution** [duke7553/files-uwp#85]
I have the folder where the source code for files is saved in the downloads page, not sure if this is something that cant be fixed because of the way the app works but when opening the folder it crashes.
This is on the latest fast ring build of Windows and the latest version of Files.

**Comment by duke7553** [comment]
Hmm... I can't seem to replicate this. What version of Files are you using, or did you build from source code?

**Comment by ATecSolution** [comment]
I built from the source code.

**Comment by duke7553** [comment]
Since you can build it from source, try running the app from the Visual Studio debugger and reproducing this issue. Then, you can provide me the error displayed.

**Comment by ATecSolution** [comment]
I just updated with to the latest version of master and I cant reproduce this issue anymore.

**Comment by mkmukund** [comment]
could you possibly design UI like as showed in this link....
https://www.behance.net/gallery/74300939/Windows-10-File-Explorer
