### ISSUE TITLE
Where is ClassicMode used? Is it necessary?

### ISSUE THREAD

**Issue by ashikns** [duke7553/files-uwp#87]
I could only find one place where ClassicMode is used - to list C drive contents. Is it only used there?

**Comment by duke7553** [comment]
ClassicMode will eventually be a legacy-like experience with Fluent Design featuring a TreeView.

**Comment by duke7553** [comment]
There is a corresponding XAML page

**Comment by duke7553** [comment]
It is nowhere near done btw.
