### ISSUE TITLE
Allow copying and pasting in and out of the app

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#89]
It would be very helpful to be able to cut, copy and paste files from files to explorer and visa versa.

**Comment by duke7553** [comment]
You should currently be able to copy/paste to and from Files. However, I am investigating a bug where Paste won't light up when an item is on the clipboard.

**Comment by duke7553** [comment]
You should notice that Paste is more reliable in the next preview, as we now check for items on the clipboard upon app launch. Please reopen if you can confirm the bug persists.

**Comment by duke7553** [comment]
The upcoming preview will completely squash this bug.
