### ISSUE TITLE
Unsupported Device

### ISSUE THREAD

**Issue by ugurozturk** [duke7553/files-uwp#91]
The details : 

![image](https://user-images.githubusercontent.com/7994408/54194860-4b5f4f80-44ce-11e9-94f2-36e2d4c07846.png)

**Comment by duke7553** [comment]
Did you grant the app permission to access your filesystem yet?

**Comment by duke7553** [comment]
Go to C:\ and grant it permission if you’re not sure.

**Comment by ugurozturk** [comment]
i did and it fixed it thanks
