### ISSUE TITLE
Cannot Install  v0.4.9 due to Certificate Error

### ISSUE THREAD

**Issue by hujan86** [duke7553/files-uwp#92]
Installation v0.4.9 failed on Windows 10 1903 (Build 18356.16). The installer gave the following error:
"Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)"

**Comment by ATecSolution** [comment]
You need to install using powershell.

**Comment by hujan86** [comment]
> 
> 
> You need to install using powershell.

How do I do that? What are the instructions?

**Comment by ATecSolution** [comment]
https://youtu.be/1wSA8PYKhpA?t=124

**Comment by hujan86** [comment]
> 
> 
> https://youtu.be/1wSA8PYKhpA?t=124
Still getting error pertaining to the certificate. 

_Found package: C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\FilesUwp.Package_0.4.9.0_x64.msix

Installing app...                                                                                                       Found dependency package(s):                                                                                            C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x86\Microsoft.NET.Native.Framework.2.1.appx        C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x86\Microsoft.NET.Native.Runtime.2.1.appx          C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.1.appx
C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.1.appx
C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but terminated in a root
certificate which is not trusted by the trust provider.

error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.

NOTE: For additional information, look for [ActivityId] c7c53de6-e3bd-0003-7216-b7ccbde3d401 in the Event Log or use
the command line Get-AppPackageLog -ActivityID c7c53de6-e3bd-0003-7216-b7ccbde3d401

At C:\Users\Acer\Desktop\FilesUwp.Package_0.4.9.0_x64_Test\Add-AppDevPackage.ps1:416 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Acer\D....4.9.0_x64.msix:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.
Press Enter to continue...:_

**Comment by ATecSolution** [comment]
Do you have developer mode on?

**Comment by hujan86** [comment]
> 
> 
> Do you have developer mode on?

Developer mode activated beforehand.

**Comment by ATecSolution** [comment]
I have no idea then, perhaps @duke7553 can help.

**Comment by hujan86** [comment]
Resolved by installing the certificate before app installation. Selected Trusted People from the certificate store, then installed for both Current User & Local Machine.

**Comment by yaichenbaum** [comment]
You can close the issue if it is resolved :)

**Comment by duke7553** [comment]
Closing this since it is resolved.
