### ISSUE TITLE
Hamburger button overlaps other UI elements

### ISSUE THREAD

**Issue by AndreasWebdev** [duke7553/files-uwp#93]
Hey, I've tried out using Files in the smalles possible aspect ratio. I noticed that the hamburger button on the top left is transparent and hovering over it can look confusing.

![image](https://user-images.githubusercontent.com/7365286/55006232-b1bf9400-4fdd-11e9-8768-6924a66562f9.png)

**Comment by duke7553** [comment]
This behavior will be changed with the next pre-release.
