### ISSUE TITLE
The Future of Files UWP

### ISSUE THREAD

**Issue by duke7553** [duke7553/files-uwp#97]
If you haven't already, check out https://github.com/duke7553/files-uwp/pull/96 for a sneak-peak at the new designs for Files UWP. Your feedback and concerns are welcome! Please discuss high-level, conceptual ideas here and lower-level, code-related ideas on the PR itself.

Thanks everybody,
Luke Blevins
Developer of Files UWP

**Comment by yaichenbaum** [comment]
Just a thought, you might want to implement rounded corners around the app as that seems to be the current things in Windows.

**Comment by duke7553** [comment]
@yaichenbaum  Perfect timing. I just issued a commit ~5 minutes ago that starts this process. Also, instance tabs are nearing completion unless I run into a bug. I'll update the picture on the PR to reflect these design changes so far.

**Comment by duke7553** [comment]
@yaichenbaum Not done yet... ;) In case you were wondering, the ribbon item selection indicator, Favorites item cards, and PathBar are now rounded. Drop shadow will come back eventually to the Ribbon pane.
![Annotation 2019-05-08 215041](https://user-images.githubusercontent.com/20365014/57421940-e5482d80-71db-11e9-860f-db81dbb54faf.png)

**Comment by yaichenbaum** [comment]
Looking really nice!

**Comment by duke7553** [comment]
First newui snapshot is now available.

**Comment by fauzie811** [comment]
I think the sidebar should be less transparent. Maybe like the Settings app.

**Comment by yaichenbaum** [comment]
@fauzie811 I like it how it is now.

**Comment by duke7553** [comment]
newui has been completely merged into master now that it's stable.

**Comment by UltimateSky** [comment]
I would like an option in the settings to disable the "Recent Items"

**Comment by duke7553** [comment]
Hello @UltimateSky, 
Please open an issue report for ideas 1-3. Idea 4 would not be practical because going through a folder and its sub-items is computationally intensive, and would slow down the loading of larger directories. This will, however, come to the properties dialog. 

Thanks!

**Comment by duke7553** [comment]
Closing this - since the first phase of the `newui` has shipped.
