### ISSUE TITLE
v0.5.0 dont run

### ISSUE THREAD

**Issue by pglionnexx** [duke7553/files-uwp#98]
Install like as usual old versions. but v0.5.0 dont run. No errors. Just closing on run.
My config x64 ver, Windows 1809

**Comment by JGeek00** [comment]
I have the same problem. v0.5.0 x64 doesn't work on my computer with Windows 10 1809.

**Comment by yaichenbaum** [comment]
You might need to be on the May 2019 update.

**Comment by duke7553** [comment]
I'm going to investigate this issue. If anyone can replicate this bug, and is comfortable obtaining a stack trace please do so. Also, are there any install errors in the powershell script? Further, you can try uninstalling the old version of Files first.

**Comment by duke7553** [comment]
It should work on 1809.

**Comment by pglionnexx** [comment]
There is no install erorrs  in the script and im try clean install.

**Comment by duke7553** [comment]
@pglionnexx Ok. The next preview snapshot will include a better system to display error messages. Rather than just aborting the app.

**Comment by JGeek00** [comment]
> It should work on 1809.
Here you have a clip wich I have recorded on my PC with the problem. I execute the PowerShell script and when I attemp to open the app, it crashes.

[files crash.zip](https://github.com/duke7553/files-uwp/files/3180458/files.crash.zip)

**Comment by duke7553** [comment]
@JGeek00 Thanks. Today's snapshot will help us with debugging this issue.

**Comment by duke7553** [comment]
Okay guys. Please try to download [today's snapshot](https://github.com/duke7553/files-uwp/releases/tag/v0.5.0-newui_snapshot1) . Which contains a new page to display errors to the user rather than just crash. This will help me figure out what type of problem this is.

**Comment by pglionnexx** [comment]
@duke7553 New snapshot run app, but there is only pre-load screen with logo.

**Comment by duke7553** [comment]
It doesn't load past this? Even when closing and trying again?

**Comment by pglionnexx** [comment]
no, just see screen with logo

**Comment by duke7553** [comment]
Ok, can you try to check in Reliability History to see if any entries came from Files?

**Comment by pglionnexx** [comment]
here the log 
[perfmon.zip](https://github.com/duke7553/files-uwp/files/3184233/perfmon.zip)

**Comment by duke7553** [comment]
Thanks. Unfortunately, that log didn't contain very much related to Files. I'll investigate this issue to see what could be causing it.

**Comment by JGeek00** [comment]
With the new versión, the app doesn't crash, but also doesn't pass of the logo screen. Yesterday I tried it on a virtual machine with Windows 10 1903 and there, the app works fine.

**Comment by duke7553** [comment]
@JGeek00 That makes sense. I remain committed to compatibility with every version after 1803, so I'll test this in a VM then.

**Comment by JGeek00** [comment]
> @JGeek00 That makes sense. I remain committed to compatibility with every version after 1803, so I'll test this in a VM then.

Ok. Thanks for your good job.

**Comment by duke7553** [comment]
Sorry about that. I have narrowed down the bug and made the necessary changes. I will release a snapshot with the fix soon.

**Comment by duke7553** [comment]
![53F17863-79F4-4EF0-9E9C-52EEF0B0DD4E](https://user-images.githubusercontent.com/20365014/57897487-f66bec80-7822-11e9-9368-cddde20998d0.jpeg)

**Comment by pglionnexx** [comment]
Thank you!

**Comment by duke7553** [comment]
A snapshot containing a fix for the issue we suspected has been released. Please reopen if this same issue continues to occur.
